// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

/**
 * Manages the autogenerated route configuration for a specific Lagoon environment, overriding the project-level config for that environment.
 */
export class EnvironmentAutogeneratedRouteConfig extends pulumi.CustomResource {
    /**
     * Get an existing EnvironmentAutogeneratedRouteConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): EnvironmentAutogeneratedRouteConfig {
        return new EnvironmentAutogeneratedRouteConfig(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lagoon:lagoon:EnvironmentAutogeneratedRouteConfig';

    /**
     * Returns true if the given object is an instance of EnvironmentAutogeneratedRouteConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EnvironmentAutogeneratedRouteConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EnvironmentAutogeneratedRouteConfig.__pulumiType;
    }

    /**
     * Whether to generate routes for pull request environments.
     */
    declare public readonly allowPullRequests: pulumi.Output<boolean | undefined>;
    /**
     * Whether to disable request verification on autogenerated routes.
     */
    declare public readonly disableRequestVerification: pulumi.Output<boolean | undefined>;
    /**
     * Whether autogenerated routes are enabled for this environment.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    /**
     * The Lagoon environment name. Changing this forces replacement.
     */
    declare public readonly environmentName: pulumi.Output<string>;
    /**
     * How to handle insecure (HTTP) traffic: Allow, Redirect, or None.
     */
    declare public readonly insecure: pulumi.Output<string | undefined>;
    /**
     * Path-based routing rules for autogenerated routes.
     */
    declare public readonly pathRoutes: pulumi.Output<outputs.resources.AutogeneratedPathRouteInput[] | undefined>;
    /**
     * Custom prefixes for autogenerated route domains.
     */
    declare public readonly prefixes: pulumi.Output<string[] | undefined>;
    /**
     * The Lagoon project name. Changing this forces replacement.
     */
    declare public readonly projectName: pulumi.Output<string>;
    /**
     * Whether to use Let's Encrypt for autogenerated route TLS.
     */
    declare public readonly tlsAcme: pulumi.Output<boolean | undefined>;

    /**
     * Create a EnvironmentAutogeneratedRouteConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EnvironmentAutogeneratedRouteConfigArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.environmentName === undefined && !opts.urn) {
                throw new Error("Missing required property 'environmentName'");
            }
            if (args?.projectName === undefined && !opts.urn) {
                throw new Error("Missing required property 'projectName'");
            }
            resourceInputs["allowPullRequests"] = args?.allowPullRequests;
            resourceInputs["disableRequestVerification"] = args?.disableRequestVerification;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["environmentName"] = args?.environmentName;
            resourceInputs["insecure"] = args?.insecure;
            resourceInputs["pathRoutes"] = args?.pathRoutes;
            resourceInputs["prefixes"] = args?.prefixes;
            resourceInputs["projectName"] = args?.projectName;
            resourceInputs["tlsAcme"] = args?.tlsAcme;
        } else {
            resourceInputs["allowPullRequests"] = undefined /*out*/;
            resourceInputs["disableRequestVerification"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["environmentName"] = undefined /*out*/;
            resourceInputs["insecure"] = undefined /*out*/;
            resourceInputs["pathRoutes"] = undefined /*out*/;
            resourceInputs["prefixes"] = undefined /*out*/;
            resourceInputs["projectName"] = undefined /*out*/;
            resourceInputs["tlsAcme"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EnvironmentAutogeneratedRouteConfig.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a EnvironmentAutogeneratedRouteConfig resource.
 */
export interface EnvironmentAutogeneratedRouteConfigArgs {
    /**
     * Whether to generate routes for pull request environments.
     */
    allowPullRequests?: pulumi.Input<boolean>;
    /**
     * Whether to disable request verification on autogenerated routes.
     */
    disableRequestVerification?: pulumi.Input<boolean>;
    /**
     * Whether autogenerated routes are enabled for this environment.
     */
    enabled?: pulumi.Input<boolean>;
    /**
     * The Lagoon environment name. Changing this forces replacement.
     */
    environmentName: pulumi.Input<string>;
    /**
     * How to handle insecure (HTTP) traffic: Allow, Redirect, or None.
     */
    insecure?: pulumi.Input<string>;
    /**
     * Path-based routing rules for autogenerated routes.
     */
    pathRoutes?: pulumi.Input<pulumi.Input<inputs.resources.AutogeneratedPathRouteInputArgs>[]>;
    /**
     * Custom prefixes for autogenerated route domains.
     */
    prefixes?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The Lagoon project name. Changing this forces replacement.
     */
    projectName: pulumi.Input<string>;
    /**
     * Whether to use Let's Encrypt for autogenerated route TLS.
     */
    tlsAcme?: pulumi.Input<boolean>;
}
