// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Manages a Lagoon project (application/site).
 */
export class Project extends pulumi.CustomResource {
    /**
     * Get an existing Project resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Project {
        return new Project(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lagoon:lagoon:Project';

    /**
     * Returns true if the given object is an instance of Project.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Project {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Project.__pulumiType;
    }

    /**
     * Whether to auto-idle environments (1=yes, 0=no).
     */
    declare public readonly autoIdle: pulumi.Output<number | undefined>;
    /**
     * Regex pattern for branches to deploy.
     */
    declare public readonly branches: pulumi.Output<string | undefined>;
    /**
     * The creation timestamp of the project.
     */
    declare public /*out*/ readonly created: pulumi.Output<string>;
    /**
     * The deploy target (Kubernetes cluster) ID.
     */
    declare public readonly deploytargetId: pulumi.Output<number>;
    /**
     * The Git repository URL (SSH or HTTPS format).
     */
    declare public readonly gitUrl: pulumi.Output<string>;
    /**
     * The Lagoon-assigned numeric ID of the project.
     */
    declare public /*out*/ readonly lagoonId: pulumi.Output<number>;
    /**
     * The project name. Must be unique, lowercase alphanumeric with hyphens.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Namespace pattern for the project on the cluster.
     */
    declare public readonly openshiftProjectPattern: pulumi.Output<string | undefined>;
    /**
     * Name of the production branch/environment.
     */
    declare public readonly productionEnvironment: pulumi.Output<string | undefined>;
    /**
     * Regex pattern for pull requests to deploy.
     */
    declare public readonly pullrequests: pulumi.Output<string | undefined>;
    /**
     * Whether to calculate storage (1=yes, 0=no).
     */
    declare public readonly storageCalc: pulumi.Output<number | undefined>;

    /**
     * Create a Project resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProjectArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.deploytargetId === undefined && !opts.urn) {
                throw new Error("Missing required property 'deploytargetId'");
            }
            if (args?.gitUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'gitUrl'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["autoIdle"] = args?.autoIdle;
            resourceInputs["branches"] = args?.branches;
            resourceInputs["deploytargetId"] = args?.deploytargetId;
            resourceInputs["gitUrl"] = args?.gitUrl;
            resourceInputs["name"] = args?.name;
            resourceInputs["openshiftProjectPattern"] = args?.openshiftProjectPattern;
            resourceInputs["productionEnvironment"] = args?.productionEnvironment;
            resourceInputs["pullrequests"] = args?.pullrequests;
            resourceInputs["storageCalc"] = args?.storageCalc;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["lagoonId"] = undefined /*out*/;
        } else {
            resourceInputs["autoIdle"] = undefined /*out*/;
            resourceInputs["branches"] = undefined /*out*/;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["deploytargetId"] = undefined /*out*/;
            resourceInputs["gitUrl"] = undefined /*out*/;
            resourceInputs["lagoonId"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["openshiftProjectPattern"] = undefined /*out*/;
            resourceInputs["productionEnvironment"] = undefined /*out*/;
            resourceInputs["pullrequests"] = undefined /*out*/;
            resourceInputs["storageCalc"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Project.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Project resource.
 */
export interface ProjectArgs {
    /**
     * Whether to auto-idle environments (1=yes, 0=no).
     */
    autoIdle?: pulumi.Input<number>;
    /**
     * Regex pattern for branches to deploy.
     */
    branches?: pulumi.Input<string>;
    /**
     * The deploy target (Kubernetes cluster) ID.
     */
    deploytargetId: pulumi.Input<number>;
    /**
     * The Git repository URL (SSH or HTTPS format).
     */
    gitUrl: pulumi.Input<string>;
    /**
     * The project name. Must be unique, lowercase alphanumeric with hyphens.
     */
    name: pulumi.Input<string>;
    /**
     * Namespace pattern for the project on the cluster.
     */
    openshiftProjectPattern?: pulumi.Input<string>;
    /**
     * Name of the production branch/environment.
     */
    productionEnvironment?: pulumi.Input<string>;
    /**
     * Regex pattern for pull requests to deploy.
     */
    pullrequests?: pulumi.Input<string>;
    /**
     * Whether to calculate storage (1=yes, 0=no).
     */
    storageCalc?: pulumi.Input<number>;
}
