// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package lagoon

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/internal"
)

// Manages a Lagoon Kubernetes deploy target (cluster).
type DeployTarget struct {
	pulumi.CustomResourceState

	// Custom build image.
	BuildImage pulumi.StringPtrOutput `pulumi:"buildImage"`
	// Cloud provider (e.g., 'kind', 'aws', 'gcp'). Defaults to 'kind'.
	CloudProvider pulumi.StringPtrOutput `pulumi:"cloudProvider"`
	// Cloud region (e.g., 'us-east-1', 'local'). Defaults to 'local'.
	CloudRegion pulumi.StringPtrOutput `pulumi:"cloudRegion"`
	// The Kubernetes API URL.
	ConsoleUrl pulumi.StringOutput `pulumi:"consoleUrl"`
	Created    pulumi.StringOutput `pulumi:"created"`
	// Whether the deploy target is disabled.
	Disabled pulumi.BoolPtrOutput `pulumi:"disabled"`
	LagoonId pulumi.IntOutput     `pulumi:"lagoonId"`
	// The deploy target name.
	Name pulumi.StringOutput `pulumi:"name"`
	// Router pattern for the deploy target.
	RouterPattern       pulumi.StringPtrOutput `pulumi:"routerPattern"`
	SharedBastionSecret pulumi.StringPtrOutput `pulumi:"sharedBastionSecret"`
	// SSH host for builds.
	SshHost pulumi.StringPtrOutput `pulumi:"sshHost"`
	// SSH port for builds.
	SshPort pulumi.StringPtrOutput `pulumi:"sshPort"`
}

// NewDeployTarget registers a new resource with the given unique name, arguments, and options.
func NewDeployTarget(ctx *pulumi.Context,
	name string, args *DeployTargetArgs, opts ...pulumi.ResourceOption) (*DeployTarget, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ConsoleUrl == nil {
		return nil, errors.New("invalid value for required argument 'ConsoleUrl'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DeployTarget
	err := ctx.RegisterResource("lagoon:lagoon:DeployTarget", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDeployTarget gets an existing DeployTarget resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDeployTarget(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DeployTargetState, opts ...pulumi.ResourceOption) (*DeployTarget, error) {
	var resource DeployTarget
	err := ctx.ReadResource("lagoon:lagoon:DeployTarget", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DeployTarget resources.
type deployTargetState struct {
}

type DeployTargetState struct {
}

func (DeployTargetState) ElementType() reflect.Type {
	return reflect.TypeOf((*deployTargetState)(nil)).Elem()
}

type deployTargetArgs struct {
	// Custom build image.
	BuildImage *string `pulumi:"buildImage"`
	// Cloud provider (e.g., 'kind', 'aws', 'gcp'). Defaults to 'kind'.
	CloudProvider *string `pulumi:"cloudProvider"`
	// Cloud region (e.g., 'us-east-1', 'local'). Defaults to 'local'.
	CloudRegion *string `pulumi:"cloudRegion"`
	// The Kubernetes API URL.
	ConsoleUrl string `pulumi:"consoleUrl"`
	// Whether the deploy target is disabled.
	Disabled *bool `pulumi:"disabled"`
	// The deploy target name.
	Name string `pulumi:"name"`
	// Router pattern for the deploy target.
	RouterPattern       *string `pulumi:"routerPattern"`
	SharedBastionSecret *string `pulumi:"sharedBastionSecret"`
	// SSH host for builds.
	SshHost *string `pulumi:"sshHost"`
	// SSH port for builds.
	SshPort *string `pulumi:"sshPort"`
}

// The set of arguments for constructing a DeployTarget resource.
type DeployTargetArgs struct {
	// Custom build image.
	BuildImage pulumi.StringPtrInput
	// Cloud provider (e.g., 'kind', 'aws', 'gcp'). Defaults to 'kind'.
	CloudProvider pulumi.StringPtrInput
	// Cloud region (e.g., 'us-east-1', 'local'). Defaults to 'local'.
	CloudRegion pulumi.StringPtrInput
	// The Kubernetes API URL.
	ConsoleUrl pulumi.StringInput
	// Whether the deploy target is disabled.
	Disabled pulumi.BoolPtrInput
	// The deploy target name.
	Name pulumi.StringInput
	// Router pattern for the deploy target.
	RouterPattern       pulumi.StringPtrInput
	SharedBastionSecret pulumi.StringPtrInput
	// SSH host for builds.
	SshHost pulumi.StringPtrInput
	// SSH port for builds.
	SshPort pulumi.StringPtrInput
}

func (DeployTargetArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*deployTargetArgs)(nil)).Elem()
}

type DeployTargetInput interface {
	pulumi.Input

	ToDeployTargetOutput() DeployTargetOutput
	ToDeployTargetOutputWithContext(ctx context.Context) DeployTargetOutput
}

func (*DeployTarget) ElementType() reflect.Type {
	return reflect.TypeOf((**DeployTarget)(nil)).Elem()
}

func (i *DeployTarget) ToDeployTargetOutput() DeployTargetOutput {
	return i.ToDeployTargetOutputWithContext(context.Background())
}

func (i *DeployTarget) ToDeployTargetOutputWithContext(ctx context.Context) DeployTargetOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DeployTargetOutput)
}

// DeployTargetArrayInput is an input type that accepts DeployTargetArray and DeployTargetArrayOutput values.
// You can construct a concrete instance of `DeployTargetArrayInput` via:
//
//	DeployTargetArray{ DeployTargetArgs{...} }
type DeployTargetArrayInput interface {
	pulumi.Input

	ToDeployTargetArrayOutput() DeployTargetArrayOutput
	ToDeployTargetArrayOutputWithContext(context.Context) DeployTargetArrayOutput
}

type DeployTargetArray []DeployTargetInput

func (DeployTargetArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DeployTarget)(nil)).Elem()
}

func (i DeployTargetArray) ToDeployTargetArrayOutput() DeployTargetArrayOutput {
	return i.ToDeployTargetArrayOutputWithContext(context.Background())
}

func (i DeployTargetArray) ToDeployTargetArrayOutputWithContext(ctx context.Context) DeployTargetArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DeployTargetArrayOutput)
}

// DeployTargetMapInput is an input type that accepts DeployTargetMap and DeployTargetMapOutput values.
// You can construct a concrete instance of `DeployTargetMapInput` via:
//
//	DeployTargetMap{ "key": DeployTargetArgs{...} }
type DeployTargetMapInput interface {
	pulumi.Input

	ToDeployTargetMapOutput() DeployTargetMapOutput
	ToDeployTargetMapOutputWithContext(context.Context) DeployTargetMapOutput
}

type DeployTargetMap map[string]DeployTargetInput

func (DeployTargetMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DeployTarget)(nil)).Elem()
}

func (i DeployTargetMap) ToDeployTargetMapOutput() DeployTargetMapOutput {
	return i.ToDeployTargetMapOutputWithContext(context.Background())
}

func (i DeployTargetMap) ToDeployTargetMapOutputWithContext(ctx context.Context) DeployTargetMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DeployTargetMapOutput)
}

type DeployTargetOutput struct{ *pulumi.OutputState }

func (DeployTargetOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DeployTarget)(nil)).Elem()
}

func (o DeployTargetOutput) ToDeployTargetOutput() DeployTargetOutput {
	return o
}

func (o DeployTargetOutput) ToDeployTargetOutputWithContext(ctx context.Context) DeployTargetOutput {
	return o
}

// Custom build image.
func (o DeployTargetOutput) BuildImage() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DeployTarget) pulumi.StringPtrOutput { return v.BuildImage }).(pulumi.StringPtrOutput)
}

// Cloud provider (e.g., 'kind', 'aws', 'gcp'). Defaults to 'kind'.
func (o DeployTargetOutput) CloudProvider() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DeployTarget) pulumi.StringPtrOutput { return v.CloudProvider }).(pulumi.StringPtrOutput)
}

// Cloud region (e.g., 'us-east-1', 'local'). Defaults to 'local'.
func (o DeployTargetOutput) CloudRegion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DeployTarget) pulumi.StringPtrOutput { return v.CloudRegion }).(pulumi.StringPtrOutput)
}

// The Kubernetes API URL.
func (o DeployTargetOutput) ConsoleUrl() pulumi.StringOutput {
	return o.ApplyT(func(v *DeployTarget) pulumi.StringOutput { return v.ConsoleUrl }).(pulumi.StringOutput)
}

func (o DeployTargetOutput) Created() pulumi.StringOutput {
	return o.ApplyT(func(v *DeployTarget) pulumi.StringOutput { return v.Created }).(pulumi.StringOutput)
}

// Whether the deploy target is disabled.
func (o DeployTargetOutput) Disabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *DeployTarget) pulumi.BoolPtrOutput { return v.Disabled }).(pulumi.BoolPtrOutput)
}

func (o DeployTargetOutput) LagoonId() pulumi.IntOutput {
	return o.ApplyT(func(v *DeployTarget) pulumi.IntOutput { return v.LagoonId }).(pulumi.IntOutput)
}

// The deploy target name.
func (o DeployTargetOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *DeployTarget) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Router pattern for the deploy target.
func (o DeployTargetOutput) RouterPattern() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DeployTarget) pulumi.StringPtrOutput { return v.RouterPattern }).(pulumi.StringPtrOutput)
}

func (o DeployTargetOutput) SharedBastionSecret() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DeployTarget) pulumi.StringPtrOutput { return v.SharedBastionSecret }).(pulumi.StringPtrOutput)
}

// SSH host for builds.
func (o DeployTargetOutput) SshHost() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DeployTarget) pulumi.StringPtrOutput { return v.SshHost }).(pulumi.StringPtrOutput)
}

// SSH port for builds.
func (o DeployTargetOutput) SshPort() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DeployTarget) pulumi.StringPtrOutput { return v.SshPort }).(pulumi.StringPtrOutput)
}

type DeployTargetArrayOutput struct{ *pulumi.OutputState }

func (DeployTargetArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DeployTarget)(nil)).Elem()
}

func (o DeployTargetArrayOutput) ToDeployTargetArrayOutput() DeployTargetArrayOutput {
	return o
}

func (o DeployTargetArrayOutput) ToDeployTargetArrayOutputWithContext(ctx context.Context) DeployTargetArrayOutput {
	return o
}

func (o DeployTargetArrayOutput) Index(i pulumi.IntInput) DeployTargetOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DeployTarget {
		return vs[0].([]*DeployTarget)[vs[1].(int)]
	}).(DeployTargetOutput)
}

type DeployTargetMapOutput struct{ *pulumi.OutputState }

func (DeployTargetMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DeployTarget)(nil)).Elem()
}

func (o DeployTargetMapOutput) ToDeployTargetMapOutput() DeployTargetMapOutput {
	return o
}

func (o DeployTargetMapOutput) ToDeployTargetMapOutputWithContext(ctx context.Context) DeployTargetMapOutput {
	return o
}

func (o DeployTargetMapOutput) MapIndex(k pulumi.StringInput) DeployTargetOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DeployTarget {
		return vs[0].(map[string]*DeployTarget)[vs[1].(string)]
	}).(DeployTargetOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DeployTargetInput)(nil)).Elem(), &DeployTarget{})
	pulumi.RegisterInputType(reflect.TypeOf((*DeployTargetArrayInput)(nil)).Elem(), DeployTargetArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DeployTargetMapInput)(nil)).Elem(), DeployTargetMap{})
	pulumi.RegisterOutputType(DeployTargetOutput{})
	pulumi.RegisterOutputType(DeployTargetArrayOutput{})
	pulumi.RegisterOutputType(DeployTargetMapOutput{})
}
