// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package lagoon

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/internal"
)

// Manages a Lagoon environment (branch/PR deployment).
type Environment struct {
	pulumi.CustomResourceState

	// Whether to auto-idle this environment (1=yes, 0=no).
	AutoIdle pulumi.IntPtrOutput `pulumi:"autoIdle"`
	// The creation timestamp.
	Created pulumi.StringOutput `pulumi:"created"`
	// The base ref for the deployment.
	DeployBaseRef pulumi.StringPtrOutput `pulumi:"deployBaseRef"`
	// The head ref for pull request deployments.
	DeployHeadRef pulumi.StringPtrOutput `pulumi:"deployHeadRef"`
	// Title for pull request deployments.
	DeployTitle pulumi.StringPtrOutput `pulumi:"deployTitle"`
	// Deployment type: 'branch' or 'pullrequest'.
	DeployType pulumi.StringOutput `pulumi:"deployType"`
	// Environment type: 'production' or 'development'.
	EnvironmentType pulumi.StringOutput `pulumi:"environmentType"`
	// The Lagoon-assigned numeric ID of the environment.
	LagoonId pulumi.IntOutput `pulumi:"lagoonId"`
	// The environment name (typically the branch name).
	Name pulumi.StringOutput `pulumi:"name"`
	// Override namespace name on the cluster.
	OpenshiftProjectName pulumi.StringPtrOutput `pulumi:"openshiftProjectName"`
	// The parent project ID.
	ProjectId pulumi.IntOutput `pulumi:"projectId"`
	// The primary route URL for this environment.
	Route pulumi.StringOutput `pulumi:"route"`
	// All route URLs for this environment.
	Routes pulumi.StringOutput `pulumi:"routes"`
}

// NewEnvironment registers a new resource with the given unique name, arguments, and options.
func NewEnvironment(ctx *pulumi.Context,
	name string, args *EnvironmentArgs, opts ...pulumi.ResourceOption) (*Environment, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DeployType == nil {
		return nil, errors.New("invalid value for required argument 'DeployType'")
	}
	if args.EnvironmentType == nil {
		return nil, errors.New("invalid value for required argument 'EnvironmentType'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.ProjectId == nil {
		return nil, errors.New("invalid value for required argument 'ProjectId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Environment
	err := ctx.RegisterResource("lagoon:lagoon:Environment", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEnvironment gets an existing Environment resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEnvironment(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EnvironmentState, opts ...pulumi.ResourceOption) (*Environment, error) {
	var resource Environment
	err := ctx.ReadResource("lagoon:lagoon:Environment", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Environment resources.
type environmentState struct {
}

type EnvironmentState struct {
}

func (EnvironmentState) ElementType() reflect.Type {
	return reflect.TypeOf((*environmentState)(nil)).Elem()
}

type environmentArgs struct {
	// Whether to auto-idle this environment (1=yes, 0=no).
	AutoIdle *int `pulumi:"autoIdle"`
	// The base ref for the deployment.
	DeployBaseRef *string `pulumi:"deployBaseRef"`
	// The head ref for pull request deployments.
	DeployHeadRef *string `pulumi:"deployHeadRef"`
	// Title for pull request deployments.
	DeployTitle *string `pulumi:"deployTitle"`
	// Deployment type: 'branch' or 'pullrequest'.
	DeployType string `pulumi:"deployType"`
	// Environment type: 'production' or 'development'.
	EnvironmentType string `pulumi:"environmentType"`
	// The environment name (typically the branch name).
	Name string `pulumi:"name"`
	// Override namespace name on the cluster.
	OpenshiftProjectName *string `pulumi:"openshiftProjectName"`
	// The parent project ID.
	ProjectId int `pulumi:"projectId"`
}

// The set of arguments for constructing a Environment resource.
type EnvironmentArgs struct {
	// Whether to auto-idle this environment (1=yes, 0=no).
	AutoIdle pulumi.IntPtrInput
	// The base ref for the deployment.
	DeployBaseRef pulumi.StringPtrInput
	// The head ref for pull request deployments.
	DeployHeadRef pulumi.StringPtrInput
	// Title for pull request deployments.
	DeployTitle pulumi.StringPtrInput
	// Deployment type: 'branch' or 'pullrequest'.
	DeployType pulumi.StringInput
	// Environment type: 'production' or 'development'.
	EnvironmentType pulumi.StringInput
	// The environment name (typically the branch name).
	Name pulumi.StringInput
	// Override namespace name on the cluster.
	OpenshiftProjectName pulumi.StringPtrInput
	// The parent project ID.
	ProjectId pulumi.IntInput
}

func (EnvironmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*environmentArgs)(nil)).Elem()
}

type EnvironmentInput interface {
	pulumi.Input

	ToEnvironmentOutput() EnvironmentOutput
	ToEnvironmentOutputWithContext(ctx context.Context) EnvironmentOutput
}

func (*Environment) ElementType() reflect.Type {
	return reflect.TypeOf((**Environment)(nil)).Elem()
}

func (i *Environment) ToEnvironmentOutput() EnvironmentOutput {
	return i.ToEnvironmentOutputWithContext(context.Background())
}

func (i *Environment) ToEnvironmentOutputWithContext(ctx context.Context) EnvironmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnvironmentOutput)
}

// EnvironmentArrayInput is an input type that accepts EnvironmentArray and EnvironmentArrayOutput values.
// You can construct a concrete instance of `EnvironmentArrayInput` via:
//
//	EnvironmentArray{ EnvironmentArgs{...} }
type EnvironmentArrayInput interface {
	pulumi.Input

	ToEnvironmentArrayOutput() EnvironmentArrayOutput
	ToEnvironmentArrayOutputWithContext(context.Context) EnvironmentArrayOutput
}

type EnvironmentArray []EnvironmentInput

func (EnvironmentArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Environment)(nil)).Elem()
}

func (i EnvironmentArray) ToEnvironmentArrayOutput() EnvironmentArrayOutput {
	return i.ToEnvironmentArrayOutputWithContext(context.Background())
}

func (i EnvironmentArray) ToEnvironmentArrayOutputWithContext(ctx context.Context) EnvironmentArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnvironmentArrayOutput)
}

// EnvironmentMapInput is an input type that accepts EnvironmentMap and EnvironmentMapOutput values.
// You can construct a concrete instance of `EnvironmentMapInput` via:
//
//	EnvironmentMap{ "key": EnvironmentArgs{...} }
type EnvironmentMapInput interface {
	pulumi.Input

	ToEnvironmentMapOutput() EnvironmentMapOutput
	ToEnvironmentMapOutputWithContext(context.Context) EnvironmentMapOutput
}

type EnvironmentMap map[string]EnvironmentInput

func (EnvironmentMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Environment)(nil)).Elem()
}

func (i EnvironmentMap) ToEnvironmentMapOutput() EnvironmentMapOutput {
	return i.ToEnvironmentMapOutputWithContext(context.Background())
}

func (i EnvironmentMap) ToEnvironmentMapOutputWithContext(ctx context.Context) EnvironmentMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnvironmentMapOutput)
}

type EnvironmentOutput struct{ *pulumi.OutputState }

func (EnvironmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Environment)(nil)).Elem()
}

func (o EnvironmentOutput) ToEnvironmentOutput() EnvironmentOutput {
	return o
}

func (o EnvironmentOutput) ToEnvironmentOutputWithContext(ctx context.Context) EnvironmentOutput {
	return o
}

// Whether to auto-idle this environment (1=yes, 0=no).
func (o EnvironmentOutput) AutoIdle() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.IntPtrOutput { return v.AutoIdle }).(pulumi.IntPtrOutput)
}

// The creation timestamp.
func (o EnvironmentOutput) Created() pulumi.StringOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringOutput { return v.Created }).(pulumi.StringOutput)
}

// The base ref for the deployment.
func (o EnvironmentOutput) DeployBaseRef() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.DeployBaseRef }).(pulumi.StringPtrOutput)
}

// The head ref for pull request deployments.
func (o EnvironmentOutput) DeployHeadRef() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.DeployHeadRef }).(pulumi.StringPtrOutput)
}

// Title for pull request deployments.
func (o EnvironmentOutput) DeployTitle() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.DeployTitle }).(pulumi.StringPtrOutput)
}

// Deployment type: 'branch' or 'pullrequest'.
func (o EnvironmentOutput) DeployType() pulumi.StringOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringOutput { return v.DeployType }).(pulumi.StringOutput)
}

// Environment type: 'production' or 'development'.
func (o EnvironmentOutput) EnvironmentType() pulumi.StringOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringOutput { return v.EnvironmentType }).(pulumi.StringOutput)
}

// The Lagoon-assigned numeric ID of the environment.
func (o EnvironmentOutput) LagoonId() pulumi.IntOutput {
	return o.ApplyT(func(v *Environment) pulumi.IntOutput { return v.LagoonId }).(pulumi.IntOutput)
}

// The environment name (typically the branch name).
func (o EnvironmentOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Override namespace name on the cluster.
func (o EnvironmentOutput) OpenshiftProjectName() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringPtrOutput { return v.OpenshiftProjectName }).(pulumi.StringPtrOutput)
}

// The parent project ID.
func (o EnvironmentOutput) ProjectId() pulumi.IntOutput {
	return o.ApplyT(func(v *Environment) pulumi.IntOutput { return v.ProjectId }).(pulumi.IntOutput)
}

// The primary route URL for this environment.
func (o EnvironmentOutput) Route() pulumi.StringOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringOutput { return v.Route }).(pulumi.StringOutput)
}

// All route URLs for this environment.
func (o EnvironmentOutput) Routes() pulumi.StringOutput {
	return o.ApplyT(func(v *Environment) pulumi.StringOutput { return v.Routes }).(pulumi.StringOutput)
}

type EnvironmentArrayOutput struct{ *pulumi.OutputState }

func (EnvironmentArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Environment)(nil)).Elem()
}

func (o EnvironmentArrayOutput) ToEnvironmentArrayOutput() EnvironmentArrayOutput {
	return o
}

func (o EnvironmentArrayOutput) ToEnvironmentArrayOutputWithContext(ctx context.Context) EnvironmentArrayOutput {
	return o
}

func (o EnvironmentArrayOutput) Index(i pulumi.IntInput) EnvironmentOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Environment {
		return vs[0].([]*Environment)[vs[1].(int)]
	}).(EnvironmentOutput)
}

type EnvironmentMapOutput struct{ *pulumi.OutputState }

func (EnvironmentMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Environment)(nil)).Elem()
}

func (o EnvironmentMapOutput) ToEnvironmentMapOutput() EnvironmentMapOutput {
	return o
}

func (o EnvironmentMapOutput) ToEnvironmentMapOutputWithContext(ctx context.Context) EnvironmentMapOutput {
	return o
}

func (o EnvironmentMapOutput) MapIndex(k pulumi.StringInput) EnvironmentOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Environment {
		return vs[0].(map[string]*Environment)[vs[1].(string)]
	}).(EnvironmentOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EnvironmentInput)(nil)).Elem(), &Environment{})
	pulumi.RegisterInputType(reflect.TypeOf((*EnvironmentArrayInput)(nil)).Elem(), EnvironmentArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*EnvironmentMapInput)(nil)).Elem(), EnvironmentMap{})
	pulumi.RegisterOutputType(EnvironmentOutput{})
	pulumi.RegisterOutputType(EnvironmentArrayOutput{})
	pulumi.RegisterOutputType(EnvironmentMapOutput{})
}
