// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package lagoon

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/internal"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/resources"
)

// Manages the autogenerated route configuration for a specific Lagoon environment, overriding the project-level config for that environment.
type EnvironmentAutogeneratedRouteConfig struct {
	pulumi.CustomResourceState

	// Whether to generate routes for pull request environments.
	AllowPullRequests pulumi.BoolPtrOutput `pulumi:"allowPullRequests"`
	// Whether to disable request verification on autogenerated routes.
	DisableRequestVerification pulumi.BoolPtrOutput `pulumi:"disableRequestVerification"`
	// Whether autogenerated routes are enabled for this environment.
	Enabled pulumi.BoolPtrOutput `pulumi:"enabled"`
	// The Lagoon environment name. Changing this forces replacement.
	EnvironmentName pulumi.StringOutput `pulumi:"environmentName"`
	// How to handle insecure (HTTP) traffic: Allow, Redirect, or None.
	Insecure pulumi.StringPtrOutput `pulumi:"insecure"`
	// Path-based routing rules for autogenerated routes.
	PathRoutes resources.AutogeneratedPathRouteInputArrayOutput `pulumi:"pathRoutes"`
	// Custom prefixes for autogenerated route domains.
	Prefixes pulumi.StringArrayOutput `pulumi:"prefixes"`
	// The Lagoon project name. Changing this forces replacement.
	ProjectName pulumi.StringOutput `pulumi:"projectName"`
	// Whether to use Let's Encrypt for autogenerated route TLS.
	TlsAcme pulumi.BoolPtrOutput `pulumi:"tlsAcme"`
}

// NewEnvironmentAutogeneratedRouteConfig registers a new resource with the given unique name, arguments, and options.
func NewEnvironmentAutogeneratedRouteConfig(ctx *pulumi.Context,
	name string, args *EnvironmentAutogeneratedRouteConfigArgs, opts ...pulumi.ResourceOption) (*EnvironmentAutogeneratedRouteConfig, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EnvironmentName == nil {
		return nil, errors.New("invalid value for required argument 'EnvironmentName'")
	}
	if args.ProjectName == nil {
		return nil, errors.New("invalid value for required argument 'ProjectName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource EnvironmentAutogeneratedRouteConfig
	err := ctx.RegisterResource("lagoon:lagoon:EnvironmentAutogeneratedRouteConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetEnvironmentAutogeneratedRouteConfig gets an existing EnvironmentAutogeneratedRouteConfig resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetEnvironmentAutogeneratedRouteConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *EnvironmentAutogeneratedRouteConfigState, opts ...pulumi.ResourceOption) (*EnvironmentAutogeneratedRouteConfig, error) {
	var resource EnvironmentAutogeneratedRouteConfig
	err := ctx.ReadResource("lagoon:lagoon:EnvironmentAutogeneratedRouteConfig", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering EnvironmentAutogeneratedRouteConfig resources.
type environmentAutogeneratedRouteConfigState struct {
}

type EnvironmentAutogeneratedRouteConfigState struct {
}

func (EnvironmentAutogeneratedRouteConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*environmentAutogeneratedRouteConfigState)(nil)).Elem()
}

type environmentAutogeneratedRouteConfigArgs struct {
	// Whether to generate routes for pull request environments.
	AllowPullRequests *bool `pulumi:"allowPullRequests"`
	// Whether to disable request verification on autogenerated routes.
	DisableRequestVerification *bool `pulumi:"disableRequestVerification"`
	// Whether autogenerated routes are enabled for this environment.
	Enabled *bool `pulumi:"enabled"`
	// The Lagoon environment name. Changing this forces replacement.
	EnvironmentName string `pulumi:"environmentName"`
	// How to handle insecure (HTTP) traffic: Allow, Redirect, or None.
	Insecure *string `pulumi:"insecure"`
	// Path-based routing rules for autogenerated routes.
	PathRoutes []resources.AutogeneratedPathRouteInput `pulumi:"pathRoutes"`
	// Custom prefixes for autogenerated route domains.
	Prefixes []string `pulumi:"prefixes"`
	// The Lagoon project name. Changing this forces replacement.
	ProjectName string `pulumi:"projectName"`
	// Whether to use Let's Encrypt for autogenerated route TLS.
	TlsAcme *bool `pulumi:"tlsAcme"`
}

// The set of arguments for constructing a EnvironmentAutogeneratedRouteConfig resource.
type EnvironmentAutogeneratedRouteConfigArgs struct {
	// Whether to generate routes for pull request environments.
	AllowPullRequests pulumi.BoolPtrInput
	// Whether to disable request verification on autogenerated routes.
	DisableRequestVerification pulumi.BoolPtrInput
	// Whether autogenerated routes are enabled for this environment.
	Enabled pulumi.BoolPtrInput
	// The Lagoon environment name. Changing this forces replacement.
	EnvironmentName pulumi.StringInput
	// How to handle insecure (HTTP) traffic: Allow, Redirect, or None.
	Insecure pulumi.StringPtrInput
	// Path-based routing rules for autogenerated routes.
	PathRoutes resources.AutogeneratedPathRouteInputArrayInput
	// Custom prefixes for autogenerated route domains.
	Prefixes pulumi.StringArrayInput
	// The Lagoon project name. Changing this forces replacement.
	ProjectName pulumi.StringInput
	// Whether to use Let's Encrypt for autogenerated route TLS.
	TlsAcme pulumi.BoolPtrInput
}

func (EnvironmentAutogeneratedRouteConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*environmentAutogeneratedRouteConfigArgs)(nil)).Elem()
}

type EnvironmentAutogeneratedRouteConfigInput interface {
	pulumi.Input

	ToEnvironmentAutogeneratedRouteConfigOutput() EnvironmentAutogeneratedRouteConfigOutput
	ToEnvironmentAutogeneratedRouteConfigOutputWithContext(ctx context.Context) EnvironmentAutogeneratedRouteConfigOutput
}

func (*EnvironmentAutogeneratedRouteConfig) ElementType() reflect.Type {
	return reflect.TypeOf((**EnvironmentAutogeneratedRouteConfig)(nil)).Elem()
}

func (i *EnvironmentAutogeneratedRouteConfig) ToEnvironmentAutogeneratedRouteConfigOutput() EnvironmentAutogeneratedRouteConfigOutput {
	return i.ToEnvironmentAutogeneratedRouteConfigOutputWithContext(context.Background())
}

func (i *EnvironmentAutogeneratedRouteConfig) ToEnvironmentAutogeneratedRouteConfigOutputWithContext(ctx context.Context) EnvironmentAutogeneratedRouteConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnvironmentAutogeneratedRouteConfigOutput)
}

// EnvironmentAutogeneratedRouteConfigArrayInput is an input type that accepts EnvironmentAutogeneratedRouteConfigArray and EnvironmentAutogeneratedRouteConfigArrayOutput values.
// You can construct a concrete instance of `EnvironmentAutogeneratedRouteConfigArrayInput` via:
//
//	EnvironmentAutogeneratedRouteConfigArray{ EnvironmentAutogeneratedRouteConfigArgs{...} }
type EnvironmentAutogeneratedRouteConfigArrayInput interface {
	pulumi.Input

	ToEnvironmentAutogeneratedRouteConfigArrayOutput() EnvironmentAutogeneratedRouteConfigArrayOutput
	ToEnvironmentAutogeneratedRouteConfigArrayOutputWithContext(context.Context) EnvironmentAutogeneratedRouteConfigArrayOutput
}

type EnvironmentAutogeneratedRouteConfigArray []EnvironmentAutogeneratedRouteConfigInput

func (EnvironmentAutogeneratedRouteConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EnvironmentAutogeneratedRouteConfig)(nil)).Elem()
}

func (i EnvironmentAutogeneratedRouteConfigArray) ToEnvironmentAutogeneratedRouteConfigArrayOutput() EnvironmentAutogeneratedRouteConfigArrayOutput {
	return i.ToEnvironmentAutogeneratedRouteConfigArrayOutputWithContext(context.Background())
}

func (i EnvironmentAutogeneratedRouteConfigArray) ToEnvironmentAutogeneratedRouteConfigArrayOutputWithContext(ctx context.Context) EnvironmentAutogeneratedRouteConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnvironmentAutogeneratedRouteConfigArrayOutput)
}

// EnvironmentAutogeneratedRouteConfigMapInput is an input type that accepts EnvironmentAutogeneratedRouteConfigMap and EnvironmentAutogeneratedRouteConfigMapOutput values.
// You can construct a concrete instance of `EnvironmentAutogeneratedRouteConfigMapInput` via:
//
//	EnvironmentAutogeneratedRouteConfigMap{ "key": EnvironmentAutogeneratedRouteConfigArgs{...} }
type EnvironmentAutogeneratedRouteConfigMapInput interface {
	pulumi.Input

	ToEnvironmentAutogeneratedRouteConfigMapOutput() EnvironmentAutogeneratedRouteConfigMapOutput
	ToEnvironmentAutogeneratedRouteConfigMapOutputWithContext(context.Context) EnvironmentAutogeneratedRouteConfigMapOutput
}

type EnvironmentAutogeneratedRouteConfigMap map[string]EnvironmentAutogeneratedRouteConfigInput

func (EnvironmentAutogeneratedRouteConfigMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EnvironmentAutogeneratedRouteConfig)(nil)).Elem()
}

func (i EnvironmentAutogeneratedRouteConfigMap) ToEnvironmentAutogeneratedRouteConfigMapOutput() EnvironmentAutogeneratedRouteConfigMapOutput {
	return i.ToEnvironmentAutogeneratedRouteConfigMapOutputWithContext(context.Background())
}

func (i EnvironmentAutogeneratedRouteConfigMap) ToEnvironmentAutogeneratedRouteConfigMapOutputWithContext(ctx context.Context) EnvironmentAutogeneratedRouteConfigMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(EnvironmentAutogeneratedRouteConfigMapOutput)
}

type EnvironmentAutogeneratedRouteConfigOutput struct{ *pulumi.OutputState }

func (EnvironmentAutogeneratedRouteConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**EnvironmentAutogeneratedRouteConfig)(nil)).Elem()
}

func (o EnvironmentAutogeneratedRouteConfigOutput) ToEnvironmentAutogeneratedRouteConfigOutput() EnvironmentAutogeneratedRouteConfigOutput {
	return o
}

func (o EnvironmentAutogeneratedRouteConfigOutput) ToEnvironmentAutogeneratedRouteConfigOutputWithContext(ctx context.Context) EnvironmentAutogeneratedRouteConfigOutput {
	return o
}

// Whether to generate routes for pull request environments.
func (o EnvironmentAutogeneratedRouteConfigOutput) AllowPullRequests() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EnvironmentAutogeneratedRouteConfig) pulumi.BoolPtrOutput { return v.AllowPullRequests }).(pulumi.BoolPtrOutput)
}

// Whether to disable request verification on autogenerated routes.
func (o EnvironmentAutogeneratedRouteConfigOutput) DisableRequestVerification() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EnvironmentAutogeneratedRouteConfig) pulumi.BoolPtrOutput { return v.DisableRequestVerification }).(pulumi.BoolPtrOutput)
}

// Whether autogenerated routes are enabled for this environment.
func (o EnvironmentAutogeneratedRouteConfigOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EnvironmentAutogeneratedRouteConfig) pulumi.BoolPtrOutput { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// The Lagoon environment name. Changing this forces replacement.
func (o EnvironmentAutogeneratedRouteConfigOutput) EnvironmentName() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentAutogeneratedRouteConfig) pulumi.StringOutput { return v.EnvironmentName }).(pulumi.StringOutput)
}

// How to handle insecure (HTTP) traffic: Allow, Redirect, or None.
func (o EnvironmentAutogeneratedRouteConfigOutput) Insecure() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *EnvironmentAutogeneratedRouteConfig) pulumi.StringPtrOutput { return v.Insecure }).(pulumi.StringPtrOutput)
}

// Path-based routing rules for autogenerated routes.
func (o EnvironmentAutogeneratedRouteConfigOutput) PathRoutes() resources.AutogeneratedPathRouteInputArrayOutput {
	return o.ApplyT(func(v *EnvironmentAutogeneratedRouteConfig) resources.AutogeneratedPathRouteInputArrayOutput {
		return v.PathRoutes
	}).(resources.AutogeneratedPathRouteInputArrayOutput)
}

// Custom prefixes for autogenerated route domains.
func (o EnvironmentAutogeneratedRouteConfigOutput) Prefixes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *EnvironmentAutogeneratedRouteConfig) pulumi.StringArrayOutput { return v.Prefixes }).(pulumi.StringArrayOutput)
}

// The Lagoon project name. Changing this forces replacement.
func (o EnvironmentAutogeneratedRouteConfigOutput) ProjectName() pulumi.StringOutput {
	return o.ApplyT(func(v *EnvironmentAutogeneratedRouteConfig) pulumi.StringOutput { return v.ProjectName }).(pulumi.StringOutput)
}

// Whether to use Let's Encrypt for autogenerated route TLS.
func (o EnvironmentAutogeneratedRouteConfigOutput) TlsAcme() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *EnvironmentAutogeneratedRouteConfig) pulumi.BoolPtrOutput { return v.TlsAcme }).(pulumi.BoolPtrOutput)
}

type EnvironmentAutogeneratedRouteConfigArrayOutput struct{ *pulumi.OutputState }

func (EnvironmentAutogeneratedRouteConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*EnvironmentAutogeneratedRouteConfig)(nil)).Elem()
}

func (o EnvironmentAutogeneratedRouteConfigArrayOutput) ToEnvironmentAutogeneratedRouteConfigArrayOutput() EnvironmentAutogeneratedRouteConfigArrayOutput {
	return o
}

func (o EnvironmentAutogeneratedRouteConfigArrayOutput) ToEnvironmentAutogeneratedRouteConfigArrayOutputWithContext(ctx context.Context) EnvironmentAutogeneratedRouteConfigArrayOutput {
	return o
}

func (o EnvironmentAutogeneratedRouteConfigArrayOutput) Index(i pulumi.IntInput) EnvironmentAutogeneratedRouteConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *EnvironmentAutogeneratedRouteConfig {
		return vs[0].([]*EnvironmentAutogeneratedRouteConfig)[vs[1].(int)]
	}).(EnvironmentAutogeneratedRouteConfigOutput)
}

type EnvironmentAutogeneratedRouteConfigMapOutput struct{ *pulumi.OutputState }

func (EnvironmentAutogeneratedRouteConfigMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*EnvironmentAutogeneratedRouteConfig)(nil)).Elem()
}

func (o EnvironmentAutogeneratedRouteConfigMapOutput) ToEnvironmentAutogeneratedRouteConfigMapOutput() EnvironmentAutogeneratedRouteConfigMapOutput {
	return o
}

func (o EnvironmentAutogeneratedRouteConfigMapOutput) ToEnvironmentAutogeneratedRouteConfigMapOutputWithContext(ctx context.Context) EnvironmentAutogeneratedRouteConfigMapOutput {
	return o
}

func (o EnvironmentAutogeneratedRouteConfigMapOutput) MapIndex(k pulumi.StringInput) EnvironmentAutogeneratedRouteConfigOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *EnvironmentAutogeneratedRouteConfig {
		return vs[0].(map[string]*EnvironmentAutogeneratedRouteConfig)[vs[1].(string)]
	}).(EnvironmentAutogeneratedRouteConfigOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*EnvironmentAutogeneratedRouteConfigInput)(nil)).Elem(), &EnvironmentAutogeneratedRouteConfig{})
	pulumi.RegisterInputType(reflect.TypeOf((*EnvironmentAutogeneratedRouteConfigArrayInput)(nil)).Elem(), EnvironmentAutogeneratedRouteConfigArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*EnvironmentAutogeneratedRouteConfigMapInput)(nil)).Elem(), EnvironmentAutogeneratedRouteConfigMap{})
	pulumi.RegisterOutputType(EnvironmentAutogeneratedRouteConfigOutput{})
	pulumi.RegisterOutputType(EnvironmentAutogeneratedRouteConfigArrayOutput{})
	pulumi.RegisterOutputType(EnvironmentAutogeneratedRouteConfigMapOutput{})
}
