// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package lagoon

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/internal"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/resources"
)

// Manages the autogenerated route configuration for a Lagoon project. Once set via the API, overrides .lagoon.yml autogenerated route config entirely.
type ProjectAutogeneratedRouteConfig struct {
	pulumi.CustomResourceState

	// Whether to generate routes for pull request environments.
	AllowPullRequests pulumi.BoolPtrOutput `pulumi:"allowPullRequests"`
	// Whether to disable request verification on autogenerated routes.
	DisableRequestVerification pulumi.BoolPtrOutput `pulumi:"disableRequestVerification"`
	// Whether autogenerated routes are enabled for this project.
	Enabled pulumi.BoolPtrOutput `pulumi:"enabled"`
	// How to handle insecure (HTTP) traffic: Allow, Redirect, or None.
	Insecure pulumi.StringPtrOutput `pulumi:"insecure"`
	// Path-based routing rules for autogenerated routes.
	PathRoutes resources.AutogeneratedPathRouteInputArrayOutput `pulumi:"pathRoutes"`
	// Custom prefixes for autogenerated route domains.
	Prefixes pulumi.StringArrayOutput `pulumi:"prefixes"`
	// The Lagoon project name. Changing this forces replacement.
	ProjectName pulumi.StringOutput `pulumi:"projectName"`
	// Whether to use Let's Encrypt for autogenerated route TLS.
	TlsAcme pulumi.BoolPtrOutput `pulumi:"tlsAcme"`
}

// NewProjectAutogeneratedRouteConfig registers a new resource with the given unique name, arguments, and options.
func NewProjectAutogeneratedRouteConfig(ctx *pulumi.Context,
	name string, args *ProjectAutogeneratedRouteConfigArgs, opts ...pulumi.ResourceOption) (*ProjectAutogeneratedRouteConfig, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ProjectName == nil {
		return nil, errors.New("invalid value for required argument 'ProjectName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ProjectAutogeneratedRouteConfig
	err := ctx.RegisterResource("lagoon:lagoon:ProjectAutogeneratedRouteConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetProjectAutogeneratedRouteConfig gets an existing ProjectAutogeneratedRouteConfig resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetProjectAutogeneratedRouteConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ProjectAutogeneratedRouteConfigState, opts ...pulumi.ResourceOption) (*ProjectAutogeneratedRouteConfig, error) {
	var resource ProjectAutogeneratedRouteConfig
	err := ctx.ReadResource("lagoon:lagoon:ProjectAutogeneratedRouteConfig", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ProjectAutogeneratedRouteConfig resources.
type projectAutogeneratedRouteConfigState struct {
}

type ProjectAutogeneratedRouteConfigState struct {
}

func (ProjectAutogeneratedRouteConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*projectAutogeneratedRouteConfigState)(nil)).Elem()
}

type projectAutogeneratedRouteConfigArgs struct {
	// Whether to generate routes for pull request environments.
	AllowPullRequests *bool `pulumi:"allowPullRequests"`
	// Whether to disable request verification on autogenerated routes.
	DisableRequestVerification *bool `pulumi:"disableRequestVerification"`
	// Whether autogenerated routes are enabled for this project.
	Enabled *bool `pulumi:"enabled"`
	// How to handle insecure (HTTP) traffic: Allow, Redirect, or None.
	Insecure *string `pulumi:"insecure"`
	// Path-based routing rules for autogenerated routes.
	PathRoutes []resources.AutogeneratedPathRouteInput `pulumi:"pathRoutes"`
	// Custom prefixes for autogenerated route domains.
	Prefixes []string `pulumi:"prefixes"`
	// The Lagoon project name. Changing this forces replacement.
	ProjectName string `pulumi:"projectName"`
	// Whether to use Let's Encrypt for autogenerated route TLS.
	TlsAcme *bool `pulumi:"tlsAcme"`
}

// The set of arguments for constructing a ProjectAutogeneratedRouteConfig resource.
type ProjectAutogeneratedRouteConfigArgs struct {
	// Whether to generate routes for pull request environments.
	AllowPullRequests pulumi.BoolPtrInput
	// Whether to disable request verification on autogenerated routes.
	DisableRequestVerification pulumi.BoolPtrInput
	// Whether autogenerated routes are enabled for this project.
	Enabled pulumi.BoolPtrInput
	// How to handle insecure (HTTP) traffic: Allow, Redirect, or None.
	Insecure pulumi.StringPtrInput
	// Path-based routing rules for autogenerated routes.
	PathRoutes resources.AutogeneratedPathRouteInputArrayInput
	// Custom prefixes for autogenerated route domains.
	Prefixes pulumi.StringArrayInput
	// The Lagoon project name. Changing this forces replacement.
	ProjectName pulumi.StringInput
	// Whether to use Let's Encrypt for autogenerated route TLS.
	TlsAcme pulumi.BoolPtrInput
}

func (ProjectAutogeneratedRouteConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*projectAutogeneratedRouteConfigArgs)(nil)).Elem()
}

type ProjectAutogeneratedRouteConfigInput interface {
	pulumi.Input

	ToProjectAutogeneratedRouteConfigOutput() ProjectAutogeneratedRouteConfigOutput
	ToProjectAutogeneratedRouteConfigOutputWithContext(ctx context.Context) ProjectAutogeneratedRouteConfigOutput
}

func (*ProjectAutogeneratedRouteConfig) ElementType() reflect.Type {
	return reflect.TypeOf((**ProjectAutogeneratedRouteConfig)(nil)).Elem()
}

func (i *ProjectAutogeneratedRouteConfig) ToProjectAutogeneratedRouteConfigOutput() ProjectAutogeneratedRouteConfigOutput {
	return i.ToProjectAutogeneratedRouteConfigOutputWithContext(context.Background())
}

func (i *ProjectAutogeneratedRouteConfig) ToProjectAutogeneratedRouteConfigOutputWithContext(ctx context.Context) ProjectAutogeneratedRouteConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectAutogeneratedRouteConfigOutput)
}

// ProjectAutogeneratedRouteConfigArrayInput is an input type that accepts ProjectAutogeneratedRouteConfigArray and ProjectAutogeneratedRouteConfigArrayOutput values.
// You can construct a concrete instance of `ProjectAutogeneratedRouteConfigArrayInput` via:
//
//	ProjectAutogeneratedRouteConfigArray{ ProjectAutogeneratedRouteConfigArgs{...} }
type ProjectAutogeneratedRouteConfigArrayInput interface {
	pulumi.Input

	ToProjectAutogeneratedRouteConfigArrayOutput() ProjectAutogeneratedRouteConfigArrayOutput
	ToProjectAutogeneratedRouteConfigArrayOutputWithContext(context.Context) ProjectAutogeneratedRouteConfigArrayOutput
}

type ProjectAutogeneratedRouteConfigArray []ProjectAutogeneratedRouteConfigInput

func (ProjectAutogeneratedRouteConfigArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProjectAutogeneratedRouteConfig)(nil)).Elem()
}

func (i ProjectAutogeneratedRouteConfigArray) ToProjectAutogeneratedRouteConfigArrayOutput() ProjectAutogeneratedRouteConfigArrayOutput {
	return i.ToProjectAutogeneratedRouteConfigArrayOutputWithContext(context.Background())
}

func (i ProjectAutogeneratedRouteConfigArray) ToProjectAutogeneratedRouteConfigArrayOutputWithContext(ctx context.Context) ProjectAutogeneratedRouteConfigArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectAutogeneratedRouteConfigArrayOutput)
}

// ProjectAutogeneratedRouteConfigMapInput is an input type that accepts ProjectAutogeneratedRouteConfigMap and ProjectAutogeneratedRouteConfigMapOutput values.
// You can construct a concrete instance of `ProjectAutogeneratedRouteConfigMapInput` via:
//
//	ProjectAutogeneratedRouteConfigMap{ "key": ProjectAutogeneratedRouteConfigArgs{...} }
type ProjectAutogeneratedRouteConfigMapInput interface {
	pulumi.Input

	ToProjectAutogeneratedRouteConfigMapOutput() ProjectAutogeneratedRouteConfigMapOutput
	ToProjectAutogeneratedRouteConfigMapOutputWithContext(context.Context) ProjectAutogeneratedRouteConfigMapOutput
}

type ProjectAutogeneratedRouteConfigMap map[string]ProjectAutogeneratedRouteConfigInput

func (ProjectAutogeneratedRouteConfigMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProjectAutogeneratedRouteConfig)(nil)).Elem()
}

func (i ProjectAutogeneratedRouteConfigMap) ToProjectAutogeneratedRouteConfigMapOutput() ProjectAutogeneratedRouteConfigMapOutput {
	return i.ToProjectAutogeneratedRouteConfigMapOutputWithContext(context.Background())
}

func (i ProjectAutogeneratedRouteConfigMap) ToProjectAutogeneratedRouteConfigMapOutputWithContext(ctx context.Context) ProjectAutogeneratedRouteConfigMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProjectAutogeneratedRouteConfigMapOutput)
}

type ProjectAutogeneratedRouteConfigOutput struct{ *pulumi.OutputState }

func (ProjectAutogeneratedRouteConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProjectAutogeneratedRouteConfig)(nil)).Elem()
}

func (o ProjectAutogeneratedRouteConfigOutput) ToProjectAutogeneratedRouteConfigOutput() ProjectAutogeneratedRouteConfigOutput {
	return o
}

func (o ProjectAutogeneratedRouteConfigOutput) ToProjectAutogeneratedRouteConfigOutputWithContext(ctx context.Context) ProjectAutogeneratedRouteConfigOutput {
	return o
}

// Whether to generate routes for pull request environments.
func (o ProjectAutogeneratedRouteConfigOutput) AllowPullRequests() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ProjectAutogeneratedRouteConfig) pulumi.BoolPtrOutput { return v.AllowPullRequests }).(pulumi.BoolPtrOutput)
}

// Whether to disable request verification on autogenerated routes.
func (o ProjectAutogeneratedRouteConfigOutput) DisableRequestVerification() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ProjectAutogeneratedRouteConfig) pulumi.BoolPtrOutput { return v.DisableRequestVerification }).(pulumi.BoolPtrOutput)
}

// Whether autogenerated routes are enabled for this project.
func (o ProjectAutogeneratedRouteConfigOutput) Enabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ProjectAutogeneratedRouteConfig) pulumi.BoolPtrOutput { return v.Enabled }).(pulumi.BoolPtrOutput)
}

// How to handle insecure (HTTP) traffic: Allow, Redirect, or None.
func (o ProjectAutogeneratedRouteConfigOutput) Insecure() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProjectAutogeneratedRouteConfig) pulumi.StringPtrOutput { return v.Insecure }).(pulumi.StringPtrOutput)
}

// Path-based routing rules for autogenerated routes.
func (o ProjectAutogeneratedRouteConfigOutput) PathRoutes() resources.AutogeneratedPathRouteInputArrayOutput {
	return o.ApplyT(func(v *ProjectAutogeneratedRouteConfig) resources.AutogeneratedPathRouteInputArrayOutput {
		return v.PathRoutes
	}).(resources.AutogeneratedPathRouteInputArrayOutput)
}

// Custom prefixes for autogenerated route domains.
func (o ProjectAutogeneratedRouteConfigOutput) Prefixes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ProjectAutogeneratedRouteConfig) pulumi.StringArrayOutput { return v.Prefixes }).(pulumi.StringArrayOutput)
}

// The Lagoon project name. Changing this forces replacement.
func (o ProjectAutogeneratedRouteConfigOutput) ProjectName() pulumi.StringOutput {
	return o.ApplyT(func(v *ProjectAutogeneratedRouteConfig) pulumi.StringOutput { return v.ProjectName }).(pulumi.StringOutput)
}

// Whether to use Let's Encrypt for autogenerated route TLS.
func (o ProjectAutogeneratedRouteConfigOutput) TlsAcme() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ProjectAutogeneratedRouteConfig) pulumi.BoolPtrOutput { return v.TlsAcme }).(pulumi.BoolPtrOutput)
}

type ProjectAutogeneratedRouteConfigArrayOutput struct{ *pulumi.OutputState }

func (ProjectAutogeneratedRouteConfigArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ProjectAutogeneratedRouteConfig)(nil)).Elem()
}

func (o ProjectAutogeneratedRouteConfigArrayOutput) ToProjectAutogeneratedRouteConfigArrayOutput() ProjectAutogeneratedRouteConfigArrayOutput {
	return o
}

func (o ProjectAutogeneratedRouteConfigArrayOutput) ToProjectAutogeneratedRouteConfigArrayOutputWithContext(ctx context.Context) ProjectAutogeneratedRouteConfigArrayOutput {
	return o
}

func (o ProjectAutogeneratedRouteConfigArrayOutput) Index(i pulumi.IntInput) ProjectAutogeneratedRouteConfigOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ProjectAutogeneratedRouteConfig {
		return vs[0].([]*ProjectAutogeneratedRouteConfig)[vs[1].(int)]
	}).(ProjectAutogeneratedRouteConfigOutput)
}

type ProjectAutogeneratedRouteConfigMapOutput struct{ *pulumi.OutputState }

func (ProjectAutogeneratedRouteConfigMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ProjectAutogeneratedRouteConfig)(nil)).Elem()
}

func (o ProjectAutogeneratedRouteConfigMapOutput) ToProjectAutogeneratedRouteConfigMapOutput() ProjectAutogeneratedRouteConfigMapOutput {
	return o
}

func (o ProjectAutogeneratedRouteConfigMapOutput) ToProjectAutogeneratedRouteConfigMapOutputWithContext(ctx context.Context) ProjectAutogeneratedRouteConfigMapOutput {
	return o
}

func (o ProjectAutogeneratedRouteConfigMapOutput) MapIndex(k pulumi.StringInput) ProjectAutogeneratedRouteConfigOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ProjectAutogeneratedRouteConfig {
		return vs[0].(map[string]*ProjectAutogeneratedRouteConfig)[vs[1].(string)]
	}).(ProjectAutogeneratedRouteConfigOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectAutogeneratedRouteConfigInput)(nil)).Elem(), &ProjectAutogeneratedRouteConfig{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectAutogeneratedRouteConfigArrayInput)(nil)).Elem(), ProjectAutogeneratedRouteConfigArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ProjectAutogeneratedRouteConfigMapInput)(nil)).Elem(), ProjectAutogeneratedRouteConfigMap{})
	pulumi.RegisterOutputType(ProjectAutogeneratedRouteConfigOutput{})
	pulumi.RegisterOutputType(ProjectAutogeneratedRouteConfigArrayOutput{})
	pulumi.RegisterOutputType(ProjectAutogeneratedRouteConfigMapOutput{})
}
