// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package lagoon

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/internal"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/resources"
)

// Manages a Lagoon API-defined route on a project (requires Lagoon v2.29.0+).
type Route struct {
	pulumi.CustomResourceState

	// Additional SAN domains for the TLS certificate (max 25).
	AlternativeNames pulumi.StringArrayOutput `pulumi:"alternativeNames"`
	// Ingress annotations (key/value pairs, max 10).
	Annotations resources.RouteAnnotationInputArrayOutput `pulumi:"annotations"`
	// Timestamp when the route was created.
	Created pulumi.StringOutput `pulumi:"created"`
	// Whether to disable request verification.
	DisableRequestVerification pulumi.BoolPtrOutput `pulumi:"disableRequestVerification"`
	// The primary domain for the route (e.g., 'example.com'). Changing this forces replacement.
	Domain pulumi.StringOutput `pulumi:"domain"`
	// The environment to attach this route to.
	Environment pulumi.StringPtrOutput `pulumi:"environment"`
	// Whether to enable HTTP Strict Transport Security.
	HstsEnabled pulumi.BoolPtrOutput `pulumi:"hstsEnabled"`
	// Whether to include subdomains in HSTS.
	HstsIncludeSubdomains pulumi.BoolPtrOutput `pulumi:"hstsIncludeSubdomains"`
	// HSTS max-age in seconds.
	HstsMaxAge pulumi.IntPtrOutput `pulumi:"hstsMaxAge"`
	// Whether to include the preload directive in HSTS.
	HstsPreload pulumi.BoolPtrOutput `pulumi:"hstsPreload"`
	// How to handle insecure (HTTP) traffic: Allow, Redirect, or None. Defaults to Redirect.
	Insecure pulumi.StringPtrOutput `pulumi:"insecure"`
	// The Lagoon-assigned numeric route ID.
	LagoonId pulumi.IntOutput `pulumi:"lagoonId"`
	// Path to use for uptime monitoring.
	MonitoringPath pulumi.StringPtrOutput `pulumi:"monitoringPath"`
	// Path-based routing rules (max 10).
	PathRoutes resources.RoutePathRouteInputArrayOutput `pulumi:"pathRoutes"`
	// Whether this is the primary route.
	Primary pulumi.BoolPtrOutput `pulumi:"primary"`
	// The Lagoon project name this route belongs to.
	ProjectName pulumi.StringOutput `pulumi:"projectName"`
	// Route type for active/standby: STANDARD, ACTIVE, or STANDBY.
	RouteType pulumi.StringPtrOutput `pulumi:"routeType"`
	// The service to route traffic to (e.g., 'nginx').
	Service pulumi.StringPtrOutput `pulumi:"service"`
	// The source of this route: API, YAML, or AUTOGENERATED.
	Source pulumi.StringOutput `pulumi:"source"`
	// Whether to use Let's Encrypt for TLS. Defaults to true.
	TlsAcme pulumi.BoolPtrOutput `pulumi:"tlsAcme"`
	// Timestamp when the route was last updated.
	Updated pulumi.StringOutput `pulumi:"updated"`
}

// NewRoute registers a new resource with the given unique name, arguments, and options.
func NewRoute(ctx *pulumi.Context,
	name string, args *RouteArgs, opts ...pulumi.ResourceOption) (*Route, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Domain == nil {
		return nil, errors.New("invalid value for required argument 'Domain'")
	}
	if args.ProjectName == nil {
		return nil, errors.New("invalid value for required argument 'ProjectName'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Route
	err := ctx.RegisterResource("lagoon:lagoon:Route", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRoute gets an existing Route resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRoute(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RouteState, opts ...pulumi.ResourceOption) (*Route, error) {
	var resource Route
	err := ctx.ReadResource("lagoon:lagoon:Route", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Route resources.
type routeState struct {
}

type RouteState struct {
}

func (RouteState) ElementType() reflect.Type {
	return reflect.TypeOf((*routeState)(nil)).Elem()
}

type routeArgs struct {
	// Additional SAN domains for the TLS certificate (max 25).
	AlternativeNames []string `pulumi:"alternativeNames"`
	// Ingress annotations (key/value pairs, max 10).
	Annotations []resources.RouteAnnotationInput `pulumi:"annotations"`
	// Whether to disable request verification.
	DisableRequestVerification *bool `pulumi:"disableRequestVerification"`
	// The primary domain for the route (e.g., 'example.com'). Changing this forces replacement.
	Domain string `pulumi:"domain"`
	// The environment to attach this route to.
	Environment *string `pulumi:"environment"`
	// Whether to enable HTTP Strict Transport Security.
	HstsEnabled *bool `pulumi:"hstsEnabled"`
	// Whether to include subdomains in HSTS.
	HstsIncludeSubdomains *bool `pulumi:"hstsIncludeSubdomains"`
	// HSTS max-age in seconds.
	HstsMaxAge *int `pulumi:"hstsMaxAge"`
	// Whether to include the preload directive in HSTS.
	HstsPreload *bool `pulumi:"hstsPreload"`
	// How to handle insecure (HTTP) traffic: Allow, Redirect, or None. Defaults to Redirect.
	Insecure *string `pulumi:"insecure"`
	// Path to use for uptime monitoring.
	MonitoringPath *string `pulumi:"monitoringPath"`
	// Path-based routing rules (max 10).
	PathRoutes []resources.RoutePathRouteInput `pulumi:"pathRoutes"`
	// Whether this is the primary route.
	Primary *bool `pulumi:"primary"`
	// The Lagoon project name this route belongs to.
	ProjectName string `pulumi:"projectName"`
	// Route type for active/standby: STANDARD, ACTIVE, or STANDBY.
	RouteType *string `pulumi:"routeType"`
	// The service to route traffic to (e.g., 'nginx').
	Service *string `pulumi:"service"`
	// Whether to use Let's Encrypt for TLS. Defaults to true.
	TlsAcme *bool `pulumi:"tlsAcme"`
}

// The set of arguments for constructing a Route resource.
type RouteArgs struct {
	// Additional SAN domains for the TLS certificate (max 25).
	AlternativeNames pulumi.StringArrayInput
	// Ingress annotations (key/value pairs, max 10).
	Annotations resources.RouteAnnotationInputArrayInput
	// Whether to disable request verification.
	DisableRequestVerification pulumi.BoolPtrInput
	// The primary domain for the route (e.g., 'example.com'). Changing this forces replacement.
	Domain pulumi.StringInput
	// The environment to attach this route to.
	Environment pulumi.StringPtrInput
	// Whether to enable HTTP Strict Transport Security.
	HstsEnabled pulumi.BoolPtrInput
	// Whether to include subdomains in HSTS.
	HstsIncludeSubdomains pulumi.BoolPtrInput
	// HSTS max-age in seconds.
	HstsMaxAge pulumi.IntPtrInput
	// Whether to include the preload directive in HSTS.
	HstsPreload pulumi.BoolPtrInput
	// How to handle insecure (HTTP) traffic: Allow, Redirect, or None. Defaults to Redirect.
	Insecure pulumi.StringPtrInput
	// Path to use for uptime monitoring.
	MonitoringPath pulumi.StringPtrInput
	// Path-based routing rules (max 10).
	PathRoutes resources.RoutePathRouteInputArrayInput
	// Whether this is the primary route.
	Primary pulumi.BoolPtrInput
	// The Lagoon project name this route belongs to.
	ProjectName pulumi.StringInput
	// Route type for active/standby: STANDARD, ACTIVE, or STANDBY.
	RouteType pulumi.StringPtrInput
	// The service to route traffic to (e.g., 'nginx').
	Service pulumi.StringPtrInput
	// Whether to use Let's Encrypt for TLS. Defaults to true.
	TlsAcme pulumi.BoolPtrInput
}

func (RouteArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*routeArgs)(nil)).Elem()
}

type RouteInput interface {
	pulumi.Input

	ToRouteOutput() RouteOutput
	ToRouteOutputWithContext(ctx context.Context) RouteOutput
}

func (*Route) ElementType() reflect.Type {
	return reflect.TypeOf((**Route)(nil)).Elem()
}

func (i *Route) ToRouteOutput() RouteOutput {
	return i.ToRouteOutputWithContext(context.Background())
}

func (i *Route) ToRouteOutputWithContext(ctx context.Context) RouteOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RouteOutput)
}

// RouteArrayInput is an input type that accepts RouteArray and RouteArrayOutput values.
// You can construct a concrete instance of `RouteArrayInput` via:
//
//	RouteArray{ RouteArgs{...} }
type RouteArrayInput interface {
	pulumi.Input

	ToRouteArrayOutput() RouteArrayOutput
	ToRouteArrayOutputWithContext(context.Context) RouteArrayOutput
}

type RouteArray []RouteInput

func (RouteArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Route)(nil)).Elem()
}

func (i RouteArray) ToRouteArrayOutput() RouteArrayOutput {
	return i.ToRouteArrayOutputWithContext(context.Background())
}

func (i RouteArray) ToRouteArrayOutputWithContext(ctx context.Context) RouteArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RouteArrayOutput)
}

// RouteMapInput is an input type that accepts RouteMap and RouteMapOutput values.
// You can construct a concrete instance of `RouteMapInput` via:
//
//	RouteMap{ "key": RouteArgs{...} }
type RouteMapInput interface {
	pulumi.Input

	ToRouteMapOutput() RouteMapOutput
	ToRouteMapOutputWithContext(context.Context) RouteMapOutput
}

type RouteMap map[string]RouteInput

func (RouteMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Route)(nil)).Elem()
}

func (i RouteMap) ToRouteMapOutput() RouteMapOutput {
	return i.ToRouteMapOutputWithContext(context.Background())
}

func (i RouteMap) ToRouteMapOutputWithContext(ctx context.Context) RouteMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RouteMapOutput)
}

type RouteOutput struct{ *pulumi.OutputState }

func (RouteOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Route)(nil)).Elem()
}

func (o RouteOutput) ToRouteOutput() RouteOutput {
	return o
}

func (o RouteOutput) ToRouteOutputWithContext(ctx context.Context) RouteOutput {
	return o
}

// Additional SAN domains for the TLS certificate (max 25).
func (o RouteOutput) AlternativeNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Route) pulumi.StringArrayOutput { return v.AlternativeNames }).(pulumi.StringArrayOutput)
}

// Ingress annotations (key/value pairs, max 10).
func (o RouteOutput) Annotations() resources.RouteAnnotationInputArrayOutput {
	return o.ApplyT(func(v *Route) resources.RouteAnnotationInputArrayOutput { return v.Annotations }).(resources.RouteAnnotationInputArrayOutput)
}

// Timestamp when the route was created.
func (o RouteOutput) Created() pulumi.StringOutput {
	return o.ApplyT(func(v *Route) pulumi.StringOutput { return v.Created }).(pulumi.StringOutput)
}

// Whether to disable request verification.
func (o RouteOutput) DisableRequestVerification() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Route) pulumi.BoolPtrOutput { return v.DisableRequestVerification }).(pulumi.BoolPtrOutput)
}

// The primary domain for the route (e.g., 'example.com'). Changing this forces replacement.
func (o RouteOutput) Domain() pulumi.StringOutput {
	return o.ApplyT(func(v *Route) pulumi.StringOutput { return v.Domain }).(pulumi.StringOutput)
}

// The environment to attach this route to.
func (o RouteOutput) Environment() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Route) pulumi.StringPtrOutput { return v.Environment }).(pulumi.StringPtrOutput)
}

// Whether to enable HTTP Strict Transport Security.
func (o RouteOutput) HstsEnabled() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Route) pulumi.BoolPtrOutput { return v.HstsEnabled }).(pulumi.BoolPtrOutput)
}

// Whether to include subdomains in HSTS.
func (o RouteOutput) HstsIncludeSubdomains() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Route) pulumi.BoolPtrOutput { return v.HstsIncludeSubdomains }).(pulumi.BoolPtrOutput)
}

// HSTS max-age in seconds.
func (o RouteOutput) HstsMaxAge() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Route) pulumi.IntPtrOutput { return v.HstsMaxAge }).(pulumi.IntPtrOutput)
}

// Whether to include the preload directive in HSTS.
func (o RouteOutput) HstsPreload() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Route) pulumi.BoolPtrOutput { return v.HstsPreload }).(pulumi.BoolPtrOutput)
}

// How to handle insecure (HTTP) traffic: Allow, Redirect, or None. Defaults to Redirect.
func (o RouteOutput) Insecure() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Route) pulumi.StringPtrOutput { return v.Insecure }).(pulumi.StringPtrOutput)
}

// The Lagoon-assigned numeric route ID.
func (o RouteOutput) LagoonId() pulumi.IntOutput {
	return o.ApplyT(func(v *Route) pulumi.IntOutput { return v.LagoonId }).(pulumi.IntOutput)
}

// Path to use for uptime monitoring.
func (o RouteOutput) MonitoringPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Route) pulumi.StringPtrOutput { return v.MonitoringPath }).(pulumi.StringPtrOutput)
}

// Path-based routing rules (max 10).
func (o RouteOutput) PathRoutes() resources.RoutePathRouteInputArrayOutput {
	return o.ApplyT(func(v *Route) resources.RoutePathRouteInputArrayOutput { return v.PathRoutes }).(resources.RoutePathRouteInputArrayOutput)
}

// Whether this is the primary route.
func (o RouteOutput) Primary() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Route) pulumi.BoolPtrOutput { return v.Primary }).(pulumi.BoolPtrOutput)
}

// The Lagoon project name this route belongs to.
func (o RouteOutput) ProjectName() pulumi.StringOutput {
	return o.ApplyT(func(v *Route) pulumi.StringOutput { return v.ProjectName }).(pulumi.StringOutput)
}

// Route type for active/standby: STANDARD, ACTIVE, or STANDBY.
func (o RouteOutput) RouteType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Route) pulumi.StringPtrOutput { return v.RouteType }).(pulumi.StringPtrOutput)
}

// The service to route traffic to (e.g., 'nginx').
func (o RouteOutput) Service() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Route) pulumi.StringPtrOutput { return v.Service }).(pulumi.StringPtrOutput)
}

// The source of this route: API, YAML, or AUTOGENERATED.
func (o RouteOutput) Source() pulumi.StringOutput {
	return o.ApplyT(func(v *Route) pulumi.StringOutput { return v.Source }).(pulumi.StringOutput)
}

// Whether to use Let's Encrypt for TLS. Defaults to true.
func (o RouteOutput) TlsAcme() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Route) pulumi.BoolPtrOutput { return v.TlsAcme }).(pulumi.BoolPtrOutput)
}

// Timestamp when the route was last updated.
func (o RouteOutput) Updated() pulumi.StringOutput {
	return o.ApplyT(func(v *Route) pulumi.StringOutput { return v.Updated }).(pulumi.StringOutput)
}

type RouteArrayOutput struct{ *pulumi.OutputState }

func (RouteArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Route)(nil)).Elem()
}

func (o RouteArrayOutput) ToRouteArrayOutput() RouteArrayOutput {
	return o
}

func (o RouteArrayOutput) ToRouteArrayOutputWithContext(ctx context.Context) RouteArrayOutput {
	return o
}

func (o RouteArrayOutput) Index(i pulumi.IntInput) RouteOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Route {
		return vs[0].([]*Route)[vs[1].(int)]
	}).(RouteOutput)
}

type RouteMapOutput struct{ *pulumi.OutputState }

func (RouteMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Route)(nil)).Elem()
}

func (o RouteMapOutput) ToRouteMapOutput() RouteMapOutput {
	return o
}

func (o RouteMapOutput) ToRouteMapOutputWithContext(ctx context.Context) RouteMapOutput {
	return o
}

func (o RouteMapOutput) MapIndex(k pulumi.StringInput) RouteOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Route {
		return vs[0].(map[string]*Route)[vs[1].(string)]
	}).(RouteOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RouteInput)(nil)).Elem(), &Route{})
	pulumi.RegisterInputType(reflect.TypeOf((*RouteArrayInput)(nil)).Elem(), RouteArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*RouteMapInput)(nil)).Elem(), RouteMap{})
	pulumi.RegisterOutputType(RouteOutput{})
	pulumi.RegisterOutputType(RouteArrayOutput{})
	pulumi.RegisterOutputType(RouteMapOutput{})
}
