// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package lagoon

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/internal"
)

// Assigns a platform-level role (OWNER or VIEWER) to a Lagoon user.
type UserPlatformRole struct {
	pulumi.CustomResourceState

	// The platform role: OWNER or VIEWER.
	Role pulumi.StringOutput `pulumi:"role"`
	// The user's email address.
	UserEmail pulumi.StringOutput `pulumi:"userEmail"`
}

// NewUserPlatformRole registers a new resource with the given unique name, arguments, and options.
func NewUserPlatformRole(ctx *pulumi.Context,
	name string, args *UserPlatformRoleArgs, opts ...pulumi.ResourceOption) (*UserPlatformRole, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Role == nil {
		return nil, errors.New("invalid value for required argument 'Role'")
	}
	if args.UserEmail == nil {
		return nil, errors.New("invalid value for required argument 'UserEmail'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource UserPlatformRole
	err := ctx.RegisterResource("lagoon:lagoon:UserPlatformRole", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUserPlatformRole gets an existing UserPlatformRole resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUserPlatformRole(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UserPlatformRoleState, opts ...pulumi.ResourceOption) (*UserPlatformRole, error) {
	var resource UserPlatformRole
	err := ctx.ReadResource("lagoon:lagoon:UserPlatformRole", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering UserPlatformRole resources.
type userPlatformRoleState struct {
}

type UserPlatformRoleState struct {
}

func (UserPlatformRoleState) ElementType() reflect.Type {
	return reflect.TypeOf((*userPlatformRoleState)(nil)).Elem()
}

type userPlatformRoleArgs struct {
	// The platform role: OWNER or VIEWER.
	Role string `pulumi:"role"`
	// The user's email address.
	UserEmail string `pulumi:"userEmail"`
}

// The set of arguments for constructing a UserPlatformRole resource.
type UserPlatformRoleArgs struct {
	// The platform role: OWNER or VIEWER.
	Role pulumi.StringInput
	// The user's email address.
	UserEmail pulumi.StringInput
}

func (UserPlatformRoleArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*userPlatformRoleArgs)(nil)).Elem()
}

type UserPlatformRoleInput interface {
	pulumi.Input

	ToUserPlatformRoleOutput() UserPlatformRoleOutput
	ToUserPlatformRoleOutputWithContext(ctx context.Context) UserPlatformRoleOutput
}

func (*UserPlatformRole) ElementType() reflect.Type {
	return reflect.TypeOf((**UserPlatformRole)(nil)).Elem()
}

func (i *UserPlatformRole) ToUserPlatformRoleOutput() UserPlatformRoleOutput {
	return i.ToUserPlatformRoleOutputWithContext(context.Background())
}

func (i *UserPlatformRole) ToUserPlatformRoleOutputWithContext(ctx context.Context) UserPlatformRoleOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserPlatformRoleOutput)
}

// UserPlatformRoleArrayInput is an input type that accepts UserPlatformRoleArray and UserPlatformRoleArrayOutput values.
// You can construct a concrete instance of `UserPlatformRoleArrayInput` via:
//
//	UserPlatformRoleArray{ UserPlatformRoleArgs{...} }
type UserPlatformRoleArrayInput interface {
	pulumi.Input

	ToUserPlatformRoleArrayOutput() UserPlatformRoleArrayOutput
	ToUserPlatformRoleArrayOutputWithContext(context.Context) UserPlatformRoleArrayOutput
}

type UserPlatformRoleArray []UserPlatformRoleInput

func (UserPlatformRoleArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*UserPlatformRole)(nil)).Elem()
}

func (i UserPlatformRoleArray) ToUserPlatformRoleArrayOutput() UserPlatformRoleArrayOutput {
	return i.ToUserPlatformRoleArrayOutputWithContext(context.Background())
}

func (i UserPlatformRoleArray) ToUserPlatformRoleArrayOutputWithContext(ctx context.Context) UserPlatformRoleArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserPlatformRoleArrayOutput)
}

// UserPlatformRoleMapInput is an input type that accepts UserPlatformRoleMap and UserPlatformRoleMapOutput values.
// You can construct a concrete instance of `UserPlatformRoleMapInput` via:
//
//	UserPlatformRoleMap{ "key": UserPlatformRoleArgs{...} }
type UserPlatformRoleMapInput interface {
	pulumi.Input

	ToUserPlatformRoleMapOutput() UserPlatformRoleMapOutput
	ToUserPlatformRoleMapOutputWithContext(context.Context) UserPlatformRoleMapOutput
}

type UserPlatformRoleMap map[string]UserPlatformRoleInput

func (UserPlatformRoleMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*UserPlatformRole)(nil)).Elem()
}

func (i UserPlatformRoleMap) ToUserPlatformRoleMapOutput() UserPlatformRoleMapOutput {
	return i.ToUserPlatformRoleMapOutputWithContext(context.Background())
}

func (i UserPlatformRoleMap) ToUserPlatformRoleMapOutputWithContext(ctx context.Context) UserPlatformRoleMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserPlatformRoleMapOutput)
}

type UserPlatformRoleOutput struct{ *pulumi.OutputState }

func (UserPlatformRoleOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**UserPlatformRole)(nil)).Elem()
}

func (o UserPlatformRoleOutput) ToUserPlatformRoleOutput() UserPlatformRoleOutput {
	return o
}

func (o UserPlatformRoleOutput) ToUserPlatformRoleOutputWithContext(ctx context.Context) UserPlatformRoleOutput {
	return o
}

// The platform role: OWNER or VIEWER.
func (o UserPlatformRoleOutput) Role() pulumi.StringOutput {
	return o.ApplyT(func(v *UserPlatformRole) pulumi.StringOutput { return v.Role }).(pulumi.StringOutput)
}

// The user's email address.
func (o UserPlatformRoleOutput) UserEmail() pulumi.StringOutput {
	return o.ApplyT(func(v *UserPlatformRole) pulumi.StringOutput { return v.UserEmail }).(pulumi.StringOutput)
}

type UserPlatformRoleArrayOutput struct{ *pulumi.OutputState }

func (UserPlatformRoleArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*UserPlatformRole)(nil)).Elem()
}

func (o UserPlatformRoleArrayOutput) ToUserPlatformRoleArrayOutput() UserPlatformRoleArrayOutput {
	return o
}

func (o UserPlatformRoleArrayOutput) ToUserPlatformRoleArrayOutputWithContext(ctx context.Context) UserPlatformRoleArrayOutput {
	return o
}

func (o UserPlatformRoleArrayOutput) Index(i pulumi.IntInput) UserPlatformRoleOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *UserPlatformRole {
		return vs[0].([]*UserPlatformRole)[vs[1].(int)]
	}).(UserPlatformRoleOutput)
}

type UserPlatformRoleMapOutput struct{ *pulumi.OutputState }

func (UserPlatformRoleMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*UserPlatformRole)(nil)).Elem()
}

func (o UserPlatformRoleMapOutput) ToUserPlatformRoleMapOutput() UserPlatformRoleMapOutput {
	return o
}

func (o UserPlatformRoleMapOutput) ToUserPlatformRoleMapOutputWithContext(ctx context.Context) UserPlatformRoleMapOutput {
	return o
}

func (o UserPlatformRoleMapOutput) MapIndex(k pulumi.StringInput) UserPlatformRoleOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *UserPlatformRole {
		return vs[0].(map[string]*UserPlatformRole)[vs[1].(string)]
	}).(UserPlatformRoleOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UserPlatformRoleInput)(nil)).Elem(), &UserPlatformRole{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserPlatformRoleArrayInput)(nil)).Elem(), UserPlatformRoleArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserPlatformRoleMapInput)(nil)).Elem(), UserPlatformRoleMap{})
	pulumi.RegisterOutputType(UserPlatformRoleOutput{})
	pulumi.RegisterOutputType(UserPlatformRoleArrayOutput{})
	pulumi.RegisterOutputType(UserPlatformRoleMapOutput{})
}
