// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package lagoon

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/internal"
)

// Assigns a Lagoon user to a group with a specific role.
type UserGroupAssignment struct {
	pulumi.CustomResourceState

	// The group name.
	GroupName pulumi.StringOutput `pulumi:"groupName"`
	// The role within the group: GUEST, REPORTER, DEVELOPER, MAINTAINER, or OWNER.
	Role pulumi.StringOutput `pulumi:"role"`
	// The user's email address.
	UserEmail pulumi.StringOutput `pulumi:"userEmail"`
}

// NewUserGroupAssignment registers a new resource with the given unique name, arguments, and options.
func NewUserGroupAssignment(ctx *pulumi.Context,
	name string, args *UserGroupAssignmentArgs, opts ...pulumi.ResourceOption) (*UserGroupAssignment, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.GroupName == nil {
		return nil, errors.New("invalid value for required argument 'GroupName'")
	}
	if args.Role == nil {
		return nil, errors.New("invalid value for required argument 'Role'")
	}
	if args.UserEmail == nil {
		return nil, errors.New("invalid value for required argument 'UserEmail'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource UserGroupAssignment
	err := ctx.RegisterResource("lagoon:lagoon:UserGroupAssignment", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUserGroupAssignment gets an existing UserGroupAssignment resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUserGroupAssignment(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UserGroupAssignmentState, opts ...pulumi.ResourceOption) (*UserGroupAssignment, error) {
	var resource UserGroupAssignment
	err := ctx.ReadResource("lagoon:lagoon:UserGroupAssignment", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering UserGroupAssignment resources.
type userGroupAssignmentState struct {
}

type UserGroupAssignmentState struct {
}

func (UserGroupAssignmentState) ElementType() reflect.Type {
	return reflect.TypeOf((*userGroupAssignmentState)(nil)).Elem()
}

type userGroupAssignmentArgs struct {
	// The group name.
	GroupName string `pulumi:"groupName"`
	// The role within the group: GUEST, REPORTER, DEVELOPER, MAINTAINER, or OWNER.
	Role string `pulumi:"role"`
	// The user's email address.
	UserEmail string `pulumi:"userEmail"`
}

// The set of arguments for constructing a UserGroupAssignment resource.
type UserGroupAssignmentArgs struct {
	// The group name.
	GroupName pulumi.StringInput
	// The role within the group: GUEST, REPORTER, DEVELOPER, MAINTAINER, or OWNER.
	Role pulumi.StringInput
	// The user's email address.
	UserEmail pulumi.StringInput
}

func (UserGroupAssignmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*userGroupAssignmentArgs)(nil)).Elem()
}

type UserGroupAssignmentInput interface {
	pulumi.Input

	ToUserGroupAssignmentOutput() UserGroupAssignmentOutput
	ToUserGroupAssignmentOutputWithContext(ctx context.Context) UserGroupAssignmentOutput
}

func (*UserGroupAssignment) ElementType() reflect.Type {
	return reflect.TypeOf((**UserGroupAssignment)(nil)).Elem()
}

func (i *UserGroupAssignment) ToUserGroupAssignmentOutput() UserGroupAssignmentOutput {
	return i.ToUserGroupAssignmentOutputWithContext(context.Background())
}

func (i *UserGroupAssignment) ToUserGroupAssignmentOutputWithContext(ctx context.Context) UserGroupAssignmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserGroupAssignmentOutput)
}

// UserGroupAssignmentArrayInput is an input type that accepts UserGroupAssignmentArray and UserGroupAssignmentArrayOutput values.
// You can construct a concrete instance of `UserGroupAssignmentArrayInput` via:
//
//	UserGroupAssignmentArray{ UserGroupAssignmentArgs{...} }
type UserGroupAssignmentArrayInput interface {
	pulumi.Input

	ToUserGroupAssignmentArrayOutput() UserGroupAssignmentArrayOutput
	ToUserGroupAssignmentArrayOutputWithContext(context.Context) UserGroupAssignmentArrayOutput
}

type UserGroupAssignmentArray []UserGroupAssignmentInput

func (UserGroupAssignmentArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*UserGroupAssignment)(nil)).Elem()
}

func (i UserGroupAssignmentArray) ToUserGroupAssignmentArrayOutput() UserGroupAssignmentArrayOutput {
	return i.ToUserGroupAssignmentArrayOutputWithContext(context.Background())
}

func (i UserGroupAssignmentArray) ToUserGroupAssignmentArrayOutputWithContext(ctx context.Context) UserGroupAssignmentArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserGroupAssignmentArrayOutput)
}

// UserGroupAssignmentMapInput is an input type that accepts UserGroupAssignmentMap and UserGroupAssignmentMapOutput values.
// You can construct a concrete instance of `UserGroupAssignmentMapInput` via:
//
//	UserGroupAssignmentMap{ "key": UserGroupAssignmentArgs{...} }
type UserGroupAssignmentMapInput interface {
	pulumi.Input

	ToUserGroupAssignmentMapOutput() UserGroupAssignmentMapOutput
	ToUserGroupAssignmentMapOutputWithContext(context.Context) UserGroupAssignmentMapOutput
}

type UserGroupAssignmentMap map[string]UserGroupAssignmentInput

func (UserGroupAssignmentMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*UserGroupAssignment)(nil)).Elem()
}

func (i UserGroupAssignmentMap) ToUserGroupAssignmentMapOutput() UserGroupAssignmentMapOutput {
	return i.ToUserGroupAssignmentMapOutputWithContext(context.Background())
}

func (i UserGroupAssignmentMap) ToUserGroupAssignmentMapOutputWithContext(ctx context.Context) UserGroupAssignmentMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserGroupAssignmentMapOutput)
}

type UserGroupAssignmentOutput struct{ *pulumi.OutputState }

func (UserGroupAssignmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**UserGroupAssignment)(nil)).Elem()
}

func (o UserGroupAssignmentOutput) ToUserGroupAssignmentOutput() UserGroupAssignmentOutput {
	return o
}

func (o UserGroupAssignmentOutput) ToUserGroupAssignmentOutputWithContext(ctx context.Context) UserGroupAssignmentOutput {
	return o
}

// The group name.
func (o UserGroupAssignmentOutput) GroupName() pulumi.StringOutput {
	return o.ApplyT(func(v *UserGroupAssignment) pulumi.StringOutput { return v.GroupName }).(pulumi.StringOutput)
}

// The role within the group: GUEST, REPORTER, DEVELOPER, MAINTAINER, or OWNER.
func (o UserGroupAssignmentOutput) Role() pulumi.StringOutput {
	return o.ApplyT(func(v *UserGroupAssignment) pulumi.StringOutput { return v.Role }).(pulumi.StringOutput)
}

// The user's email address.
func (o UserGroupAssignmentOutput) UserEmail() pulumi.StringOutput {
	return o.ApplyT(func(v *UserGroupAssignment) pulumi.StringOutput { return v.UserEmail }).(pulumi.StringOutput)
}

type UserGroupAssignmentArrayOutput struct{ *pulumi.OutputState }

func (UserGroupAssignmentArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*UserGroupAssignment)(nil)).Elem()
}

func (o UserGroupAssignmentArrayOutput) ToUserGroupAssignmentArrayOutput() UserGroupAssignmentArrayOutput {
	return o
}

func (o UserGroupAssignmentArrayOutput) ToUserGroupAssignmentArrayOutputWithContext(ctx context.Context) UserGroupAssignmentArrayOutput {
	return o
}

func (o UserGroupAssignmentArrayOutput) Index(i pulumi.IntInput) UserGroupAssignmentOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *UserGroupAssignment {
		return vs[0].([]*UserGroupAssignment)[vs[1].(int)]
	}).(UserGroupAssignmentOutput)
}

type UserGroupAssignmentMapOutput struct{ *pulumi.OutputState }

func (UserGroupAssignmentMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*UserGroupAssignment)(nil)).Elem()
}

func (o UserGroupAssignmentMapOutput) ToUserGroupAssignmentMapOutput() UserGroupAssignmentMapOutput {
	return o
}

func (o UserGroupAssignmentMapOutput) ToUserGroupAssignmentMapOutputWithContext(ctx context.Context) UserGroupAssignmentMapOutput {
	return o
}

func (o UserGroupAssignmentMapOutput) MapIndex(k pulumi.StringInput) UserGroupAssignmentOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *UserGroupAssignment {
		return vs[0].(map[string]*UserGroupAssignment)[vs[1].(string)]
	}).(UserGroupAssignmentOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UserGroupAssignmentInput)(nil)).Elem(), &UserGroupAssignment{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserGroupAssignmentArrayInput)(nil)).Elem(), UserGroupAssignmentArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserGroupAssignmentMapInput)(nil)).Elem(), UserGroupAssignmentMap{})
	pulumi.RegisterOutputType(UserGroupAssignmentOutput{})
	pulumi.RegisterOutputType(UserGroupAssignmentArrayOutput{})
	pulumi.RegisterOutputType(UserGroupAssignmentMapOutput{})
}
