package resources

import (
	"context"
	"testing"

	p "github.com/pulumi/pulumi-go-provider"
	"github.com/pulumi/pulumi-go-provider/infer"
	"github.com/tag1consulting/pulumi-lagoon/provider/pkg/client"
)

func TestEnvironmentAutogeneratedRouteConfig_Create_HappyPath(t *testing.T) {
	called := false
	enabled := true
	mock := &mockLagoonClient{
		updateAutoRouteConfigEnvFn: func(_ context.Context, projectName, environmentName string, patch map[string]any) (*client.AutogeneratedRouteConfig, error) {
			called = true
			if projectName != "my-project" {
				t.Errorf("expected my-project, got %s", projectName)
			}
			if environmentName != "main" {
				t.Errorf("expected main, got %s", environmentName)
			}
			return &client.AutogeneratedRouteConfig{Enabled: &enabled}, nil
		},
	}
	ctx := testCtx(mock)
	r := &EnvironmentAutogeneratedRouteConfig{}
	resp, err := r.Create(ctx, infer.CreateRequest[EnvironmentAutogeneratedRouteConfigArgs]{
		Inputs: EnvironmentAutogeneratedRouteConfigArgs{
			ProjectName:     "my-project",
			EnvironmentName: "main",
			Enabled:         &enabled,
		},
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !called {
		t.Error("expected API to be called")
	}
	if resp.ID != "my-project:main" {
		t.Errorf("expected ID my-project:main, got %s", resp.ID)
	}
}

func TestEnvironmentAutogeneratedRouteConfig_Create_DryRun(t *testing.T) {
	called := false
	mock := &mockLagoonClient{
		updateAutoRouteConfigEnvFn: func(_ context.Context, _, _ string, _ map[string]any) (*client.AutogeneratedRouteConfig, error) {
			called = true
			return nil, nil
		},
	}
	ctx := testCtx(mock)
	r := &EnvironmentAutogeneratedRouteConfig{}
	resp, err := r.Create(ctx, infer.CreateRequest[EnvironmentAutogeneratedRouteConfigArgs]{
		DryRun: true,
		Inputs: EnvironmentAutogeneratedRouteConfigArgs{ProjectName: "p", EnvironmentName: "main"},
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if called {
		t.Error("API should not be called on dry run")
	}
	if resp.ID != "p:main" {
		t.Errorf("expected ID p:main, got %s", resp.ID)
	}
}

func TestEnvironmentAutogeneratedRouteConfig_Delete_HappyPath(t *testing.T) {
	called := false
	mock := &mockLagoonClient{
		removeAutoRouteConfigEnvFn: func(_ context.Context, projectName, environmentName string) error {
			called = true
			if projectName != "p" || environmentName != "main" {
				t.Errorf("unexpected args: %s %s", projectName, environmentName)
			}
			return nil
		},
	}
	ctx := testCtx(mock)
	r := &EnvironmentAutogeneratedRouteConfig{}
	_, err := r.Delete(ctx, infer.DeleteRequest[EnvironmentAutogeneratedRouteConfigState]{
		State: EnvironmentAutogeneratedRouteConfigState{
			EnvironmentAutogeneratedRouteConfigArgs: EnvironmentAutogeneratedRouteConfigArgs{
				ProjectName: "p", EnvironmentName: "main",
			},
		},
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !called {
		t.Error("expected RemoveAutogeneratedRouteConfigFromEnvironment to be called")
	}
}

func TestEnvironmentAutogeneratedRouteConfig_Read_ByImportID(t *testing.T) {
	enabled := true
	mock := &mockLagoonClient{
		getAutoRouteConfigEnvFn: func(_ context.Context, projectName, environmentName string) (*client.AutogeneratedRouteConfig, error) {
			if projectName != "my-project" || environmentName != "main" {
				t.Errorf("unexpected args: %s %s", projectName, environmentName)
			}
			return &client.AutogeneratedRouteConfig{Enabled: &enabled}, nil
		},
	}
	ctx := testCtx(mock)
	r := &EnvironmentAutogeneratedRouteConfig{}
	resp, err := r.Read(ctx, infer.ReadRequest[EnvironmentAutogeneratedRouteConfigArgs, EnvironmentAutogeneratedRouteConfigState]{
		ID:    "my-project:main",
		State: EnvironmentAutogeneratedRouteConfigState{},
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if resp.Inputs.ProjectName != "my-project" {
		t.Errorf("expected projectName my-project, got %s", resp.Inputs.ProjectName)
	}
	if resp.Inputs.EnvironmentName != "main" {
		t.Errorf("expected environmentName main, got %s", resp.Inputs.EnvironmentName)
	}
}

func TestEnvironmentAutogeneratedRouteConfig_Diff_BothIdentityFieldsAreForceNew(t *testing.T) {
	r := &EnvironmentAutogeneratedRouteConfig{}

	// Project name change
	resp, err := r.Diff(testCtx(&mockLagoonClient{}), infer.DiffRequest[EnvironmentAutogeneratedRouteConfigArgs, EnvironmentAutogeneratedRouteConfigState]{
		Inputs: EnvironmentAutogeneratedRouteConfigArgs{ProjectName: "new-proj", EnvironmentName: "main"},
		State:  EnvironmentAutogeneratedRouteConfigState{EnvironmentAutogeneratedRouteConfigArgs: EnvironmentAutogeneratedRouteConfigArgs{ProjectName: "old-proj", EnvironmentName: "main"}},
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if d, ok := resp.DetailedDiff["projectName"]; !ok || d.Kind != p.UpdateReplace {
		t.Errorf("expected projectName UpdateReplace, got %v", resp.DetailedDiff)
	}

	// Environment name change
	resp, err = r.Diff(testCtx(&mockLagoonClient{}), infer.DiffRequest[EnvironmentAutogeneratedRouteConfigArgs, EnvironmentAutogeneratedRouteConfigState]{
		Inputs: EnvironmentAutogeneratedRouteConfigArgs{ProjectName: "p", EnvironmentName: "new-env"},
		State:  EnvironmentAutogeneratedRouteConfigState{EnvironmentAutogeneratedRouteConfigArgs: EnvironmentAutogeneratedRouteConfigArgs{ProjectName: "p", EnvironmentName: "old-env"}},
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if d, ok := resp.DetailedDiff["environmentName"]; !ok || d.Kind != p.UpdateReplace {
		t.Errorf("expected environmentName UpdateReplace, got %v", resp.DetailedDiff)
	}
}
