package resources

import (
	"context"
	"errors"
	"fmt"
	"strings"

	p "github.com/pulumi/pulumi-go-provider"
	"github.com/pulumi/pulumi-go-provider/infer"
	"github.com/tag1consulting/pulumi-lagoon/provider/pkg/client"
)

// EnvironmentAutogeneratedRouteConfig manages the autogenerated route configuration
// for a specific Lagoon environment, overriding the project-level config for that environment.
type EnvironmentAutogeneratedRouteConfig struct{}

// EnvironmentAutogeneratedRouteConfigArgs defines the user-provided inputs.
type EnvironmentAutogeneratedRouteConfigArgs struct {
	ProjectName                string                        `pulumi:"projectName"`
	EnvironmentName            string                        `pulumi:"environmentName"`
	Enabled                    *bool                         `pulumi:"enabled,optional"`
	AllowPullRequests          *bool                         `pulumi:"allowPullRequests,optional"`
	Prefixes                   *[]string                     `pulumi:"prefixes,optional"`
	PathRoutes                 *[]AutogeneratedPathRouteInput `pulumi:"pathRoutes,optional"`
	DisableRequestVerification *bool                         `pulumi:"disableRequestVerification,optional"`
	Insecure                   *string                       `pulumi:"insecure,optional"`
	TLSAcme                    *bool                         `pulumi:"tlsAcme,optional"`
}

// EnvironmentAutogeneratedRouteConfigState is the persisted state.
type EnvironmentAutogeneratedRouteConfigState struct {
	EnvironmentAutogeneratedRouteConfigArgs
}

func (r *EnvironmentAutogeneratedRouteConfig) Annotate(a infer.Annotator) {
	a.SetToken("lagoon", "EnvironmentAutogeneratedRouteConfig")
	a.Describe(&r, "Manages the autogenerated route configuration for a specific Lagoon environment, overriding the project-level config for that environment.")
}

func (a *EnvironmentAutogeneratedRouteConfigArgs) Annotate(an infer.Annotator) {
	an.Describe(&a.ProjectName, "The Lagoon project name. Changing this forces replacement.")
	an.Describe(&a.EnvironmentName, "The Lagoon environment name. Changing this forces replacement.")
	an.Describe(&a.Enabled, "Whether autogenerated routes are enabled for this environment.")
	an.Describe(&a.AllowPullRequests, "Whether to generate routes for pull request environments.")
	an.Describe(&a.Prefixes, "Custom prefixes for autogenerated route domains.")
	an.Describe(&a.PathRoutes, "Path-based routing rules for autogenerated routes.")
	an.Describe(&a.DisableRequestVerification, "Whether to disable request verification on autogenerated routes.")
	an.Describe(&a.Insecure, "How to handle insecure (HTTP) traffic: Allow, Redirect, or None.")
	an.Describe(&a.TLSAcme, "Whether to use Let's Encrypt for autogenerated route TLS.")
}

func (r *EnvironmentAutogeneratedRouteConfig) Create(ctx context.Context, req infer.CreateRequest[EnvironmentAutogeneratedRouteConfigArgs]) (infer.CreateResponse[EnvironmentAutogeneratedRouteConfigState], error) {
	args := req.Inputs
	resourceID := args.ProjectName + ":" + args.EnvironmentName

	if req.DryRun {
		return infer.CreateResponse[EnvironmentAutogeneratedRouteConfigState]{
			ID:     resourceID,
			Output: EnvironmentAutogeneratedRouteConfigState{EnvironmentAutogeneratedRouteConfigArgs: args},
		}, nil
	}

	c := clientFor(ctx)
	patch := buildAutogeneratedRouteConfigPatch(args.Enabled, args.AllowPullRequests, args.Prefixes, args.PathRoutes, args.DisableRequestVerification, args.Insecure, args.TLSAcme)

	if _, err := c.UpdateAutogeneratedRouteConfigOnEnvironment(ctx, args.ProjectName, args.EnvironmentName, patch); err != nil {
		return infer.CreateResponse[EnvironmentAutogeneratedRouteConfigState]{}, fmt.Errorf("failed to set environment autogenerated route config: %w", err)
	}

	return infer.CreateResponse[EnvironmentAutogeneratedRouteConfigState]{
		ID:     resourceID,
		Output: EnvironmentAutogeneratedRouteConfigState{EnvironmentAutogeneratedRouteConfigArgs: args},
	}, nil
}

func (r *EnvironmentAutogeneratedRouteConfig) Update(ctx context.Context, req infer.UpdateRequest[EnvironmentAutogeneratedRouteConfigArgs, EnvironmentAutogeneratedRouteConfigState]) (infer.UpdateResponse[EnvironmentAutogeneratedRouteConfigState], error) {
	if req.DryRun {
		return infer.UpdateResponse[EnvironmentAutogeneratedRouteConfigState]{
			Output: EnvironmentAutogeneratedRouteConfigState{EnvironmentAutogeneratedRouteConfigArgs: req.Inputs},
		}, nil
	}

	c := clientFor(ctx)
	args := req.Inputs
	patch := buildAutogeneratedRouteConfigPatch(args.Enabled, args.AllowPullRequests, args.Prefixes, args.PathRoutes, args.DisableRequestVerification, args.Insecure, args.TLSAcme)

	if _, err := c.UpdateAutogeneratedRouteConfigOnEnvironment(ctx, args.ProjectName, args.EnvironmentName, patch); err != nil {
		return infer.UpdateResponse[EnvironmentAutogeneratedRouteConfigState]{}, fmt.Errorf("failed to update environment autogenerated route config: %w", err)
	}

	return infer.UpdateResponse[EnvironmentAutogeneratedRouteConfigState]{
		Output: EnvironmentAutogeneratedRouteConfigState{EnvironmentAutogeneratedRouteConfigArgs: args},
	}, nil
}

func (r *EnvironmentAutogeneratedRouteConfig) Delete(ctx context.Context, req infer.DeleteRequest[EnvironmentAutogeneratedRouteConfigState]) (infer.DeleteResponse, error) {
	c := clientFor(ctx)
	state := req.State

	if err := c.RemoveAutogeneratedRouteConfigFromEnvironment(ctx, state.ProjectName, state.EnvironmentName); err != nil {
		if errors.Is(err, client.ErrNotFound) {
			return infer.DeleteResponse{}, nil
		}
		return infer.DeleteResponse{}, fmt.Errorf("failed to remove environment autogenerated route config: %w", err)
	}
	return infer.DeleteResponse{}, nil
}

func (r *EnvironmentAutogeneratedRouteConfig) Read(ctx context.Context, req infer.ReadRequest[EnvironmentAutogeneratedRouteConfigArgs, EnvironmentAutogeneratedRouteConfigState]) (infer.ReadResponse[EnvironmentAutogeneratedRouteConfigArgs, EnvironmentAutogeneratedRouteConfigState], error) {
	c := clientFor(ctx)

	projectName := req.State.ProjectName
	environmentName := req.State.EnvironmentName
	if projectName == "" || environmentName == "" {
		// Parse import ID: "{projectName}:{environmentName}"
		parts := strings.SplitN(req.ID, ":", 2)
		if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
			return infer.ReadResponse[EnvironmentAutogeneratedRouteConfigArgs, EnvironmentAutogeneratedRouteConfigState]{}, fmt.Errorf("invalid ID %q: expected '{projectName}:{environmentName}'", req.ID)
		}
		projectName = parts[0]
		environmentName = parts[1]
	}

	cfg, err := c.GetAutogeneratedRouteConfigForEnvironment(ctx, projectName, environmentName)
	if err != nil {
		if errors.Is(err, client.ErrNotFound) {
			return infer.ReadResponse[EnvironmentAutogeneratedRouteConfigArgs, EnvironmentAutogeneratedRouteConfigState]{}, nil
		}
		return infer.ReadResponse[EnvironmentAutogeneratedRouteConfigArgs, EnvironmentAutogeneratedRouteConfigState]{}, fmt.Errorf("failed to read environment autogenerated route config: %w", err)
	}
	if cfg == nil {
		return infer.ReadResponse[EnvironmentAutogeneratedRouteConfigArgs, EnvironmentAutogeneratedRouteConfigState]{}, nil
	}

	args := autogeneratedRouteConfigToEnvironmentArgs(projectName, environmentName, cfg)
	st := EnvironmentAutogeneratedRouteConfigState{EnvironmentAutogeneratedRouteConfigArgs: args}

	return infer.ReadResponse[EnvironmentAutogeneratedRouteConfigArgs, EnvironmentAutogeneratedRouteConfigState]{
		ID:     projectName + ":" + environmentName,
		Inputs: args,
		State:  st,
	}, nil
}

func (r *EnvironmentAutogeneratedRouteConfig) Diff(ctx context.Context, req infer.DiffRequest[EnvironmentAutogeneratedRouteConfigArgs, EnvironmentAutogeneratedRouteConfigState]) (infer.DiffResponse, error) {
	diff := map[string]p.PropertyDiff{}

	if req.Inputs.ProjectName != req.State.ProjectName {
		diff["projectName"] = p.PropertyDiff{Kind: p.UpdateReplace}
	}
	if req.Inputs.EnvironmentName != req.State.EnvironmentName {
		diff["environmentName"] = p.PropertyDiff{Kind: p.UpdateReplace}
	}
	if req.Inputs.Enabled != req.State.Enabled {
		diff["enabled"] = p.PropertyDiff{Kind: p.Update}
	}
	if req.Inputs.AllowPullRequests != req.State.AllowPullRequests {
		diff["allowPullRequests"] = p.PropertyDiff{Kind: p.Update}
	}
	if prefixesDiffer(req.Inputs.Prefixes, req.State.Prefixes) {
		diff["prefixes"] = p.PropertyDiff{Kind: p.Update}
	}
	if autogeneratedPathRoutesDiffer(req.Inputs.PathRoutes, req.State.PathRoutes) {
		diff["pathRoutes"] = p.PropertyDiff{Kind: p.Update}
	}
	if req.Inputs.DisableRequestVerification != req.State.DisableRequestVerification {
		diff["disableRequestVerification"] = p.PropertyDiff{Kind: p.Update}
	}
	if ptrDiffers(req.Inputs.Insecure, req.State.Insecure) {
		diff["insecure"] = p.PropertyDiff{Kind: p.Update}
	}
	if req.Inputs.TLSAcme != req.State.TLSAcme {
		diff["tlsAcme"] = p.PropertyDiff{Kind: p.Update}
	}

	return p.DiffResponse{HasChanges: len(diff) > 0, DetailedDiff: diff, DeleteBeforeReplace: true}, nil
}

func autogeneratedRouteConfigToEnvironmentArgs(projectName, environmentName string, cfg *client.AutogeneratedRouteConfig) EnvironmentAutogeneratedRouteConfigArgs {
	args := EnvironmentAutogeneratedRouteConfigArgs{
		ProjectName:                projectName,
		EnvironmentName:            environmentName,
		Enabled:                    cfg.Enabled,
		AllowPullRequests:          cfg.AllowPullRequests,
		DisableRequestVerification: cfg.DisableRequestVerification,
		TLSAcme:                    cfg.TLSAcme,
	}
	if cfg.Insecure != "" {
		args.Insecure = &cfg.Insecure
	}
	if len(cfg.Prefixes) > 0 {
		args.Prefixes = &cfg.Prefixes
	}
	if len(cfg.PathRoutes) > 0 {
		prs := make([]AutogeneratedPathRouteInput, len(cfg.PathRoutes))
		for i, pr := range cfg.PathRoutes {
			prs[i] = AutogeneratedPathRouteInput{
				FromService: pr.FromService,
				ToService:   pr.ToService,
				Path:        pr.Path,
			}
		}
		args.PathRoutes = &prs
	}
	return args
}
