package resources

import (
	"context"
	"errors"
	"fmt"

	p "github.com/pulumi/pulumi-go-provider"
	"github.com/pulumi/pulumi-go-provider/infer"
	"github.com/tag1consulting/pulumi-lagoon/provider/pkg/client"
)

// ProjectAutogeneratedRouteConfig manages the autogenerated route configuration for a Lagoon project.
// Once set via the API, it overrides any autogenerated route config defined in .lagoon.yml.
type ProjectAutogeneratedRouteConfig struct{}

// ProjectAutogeneratedRouteConfigArgs defines the user-provided inputs.
type ProjectAutogeneratedRouteConfigArgs struct {
	ProjectName                string                 `pulumi:"projectName"`
	Enabled                    *bool                  `pulumi:"enabled,optional"`
	AllowPullRequests          *bool                  `pulumi:"allowPullRequests,optional"`
	Prefixes                   *[]string              `pulumi:"prefixes,optional"`
	PathRoutes                 *[]AutogeneratedPathRouteInput `pulumi:"pathRoutes,optional"`
	DisableRequestVerification *bool                  `pulumi:"disableRequestVerification,optional"`
	Insecure                   *string                `pulumi:"insecure,optional"`
	TLSAcme                    *bool                  `pulumi:"tlsAcme,optional"`
}

// AutogeneratedPathRouteInput is a path routing rule in an autogenerated route config.
type AutogeneratedPathRouteInput struct {
	FromService string `pulumi:"fromService"`
	ToService   string `pulumi:"toService"`
	Path        string `pulumi:"path"`
}

func (a *AutogeneratedPathRouteInput) Annotate(an infer.Annotator) {
	an.Describe(&a.FromService, "The source service originating the request.")
	an.Describe(&a.ToService, "The destination service to route to.")
	an.Describe(&a.Path, "The URL path prefix to match.")
}

// ProjectAutogeneratedRouteConfigState is the persisted state.
type ProjectAutogeneratedRouteConfigState struct {
	ProjectAutogeneratedRouteConfigArgs
}

func (r *ProjectAutogeneratedRouteConfig) Annotate(a infer.Annotator) {
	a.SetToken("lagoon", "ProjectAutogeneratedRouteConfig")
	a.Describe(&r, "Manages the autogenerated route configuration for a Lagoon project. Once set via the API, overrides .lagoon.yml autogenerated route config entirely.")
}

func (a *ProjectAutogeneratedRouteConfigArgs) Annotate(an infer.Annotator) {
	an.Describe(&a.ProjectName, "The Lagoon project name. Changing this forces replacement.")
	an.Describe(&a.Enabled, "Whether autogenerated routes are enabled for this project.")
	an.Describe(&a.AllowPullRequests, "Whether to generate routes for pull request environments.")
	an.Describe(&a.Prefixes, "Custom prefixes for autogenerated route domains.")
	an.Describe(&a.PathRoutes, "Path-based routing rules for autogenerated routes.")
	an.Describe(&a.DisableRequestVerification, "Whether to disable request verification on autogenerated routes.")
	an.Describe(&a.Insecure, "How to handle insecure (HTTP) traffic: Allow, Redirect, or None.")
	an.Describe(&a.TLSAcme, "Whether to use Let's Encrypt for autogenerated route TLS.")
}

func (r *ProjectAutogeneratedRouteConfig) Create(ctx context.Context, req infer.CreateRequest[ProjectAutogeneratedRouteConfigArgs]) (infer.CreateResponse[ProjectAutogeneratedRouteConfigState], error) {
	if req.DryRun {
		return infer.CreateResponse[ProjectAutogeneratedRouteConfigState]{
			ID:     req.Inputs.ProjectName,
			Output: ProjectAutogeneratedRouteConfigState{ProjectAutogeneratedRouteConfigArgs: req.Inputs},
		}, nil
	}

	c := clientFor(ctx)
	args := req.Inputs

	patch := buildAutogeneratedRouteConfigPatch(args.Enabled, args.AllowPullRequests, args.Prefixes, args.PathRoutes, args.DisableRequestVerification, args.Insecure, args.TLSAcme)

	if _, err := c.UpdateAutogeneratedRouteConfigOnProject(ctx, args.ProjectName, patch); err != nil {
		return infer.CreateResponse[ProjectAutogeneratedRouteConfigState]{}, fmt.Errorf("failed to set project autogenerated route config: %w", err)
	}

	return infer.CreateResponse[ProjectAutogeneratedRouteConfigState]{
		ID:     args.ProjectName,
		Output: ProjectAutogeneratedRouteConfigState{ProjectAutogeneratedRouteConfigArgs: args},
	}, nil
}

func (r *ProjectAutogeneratedRouteConfig) Update(ctx context.Context, req infer.UpdateRequest[ProjectAutogeneratedRouteConfigArgs, ProjectAutogeneratedRouteConfigState]) (infer.UpdateResponse[ProjectAutogeneratedRouteConfigState], error) {
	if req.DryRun {
		return infer.UpdateResponse[ProjectAutogeneratedRouteConfigState]{
			Output: ProjectAutogeneratedRouteConfigState{ProjectAutogeneratedRouteConfigArgs: req.Inputs},
		}, nil
	}

	c := clientFor(ctx)
	args := req.Inputs

	patch := buildAutogeneratedRouteConfigPatch(args.Enabled, args.AllowPullRequests, args.Prefixes, args.PathRoutes, args.DisableRequestVerification, args.Insecure, args.TLSAcme)

	if _, err := c.UpdateAutogeneratedRouteConfigOnProject(ctx, args.ProjectName, patch); err != nil {
		return infer.UpdateResponse[ProjectAutogeneratedRouteConfigState]{}, fmt.Errorf("failed to update project autogenerated route config: %w", err)
	}

	return infer.UpdateResponse[ProjectAutogeneratedRouteConfigState]{
		Output: ProjectAutogeneratedRouteConfigState{ProjectAutogeneratedRouteConfigArgs: args},
	}, nil
}

func (r *ProjectAutogeneratedRouteConfig) Delete(ctx context.Context, req infer.DeleteRequest[ProjectAutogeneratedRouteConfigState]) (infer.DeleteResponse, error) {
	c := clientFor(ctx)

	if err := c.RemoveAutogeneratedRouteConfigFromProject(ctx, req.State.ProjectName); err != nil {
		if errors.Is(err, client.ErrNotFound) {
			return infer.DeleteResponse{}, nil
		}
		return infer.DeleteResponse{}, fmt.Errorf("failed to remove project autogenerated route config: %w", err)
	}
	return infer.DeleteResponse{}, nil
}

func (r *ProjectAutogeneratedRouteConfig) Read(ctx context.Context, req infer.ReadRequest[ProjectAutogeneratedRouteConfigArgs, ProjectAutogeneratedRouteConfigState]) (infer.ReadResponse[ProjectAutogeneratedRouteConfigArgs, ProjectAutogeneratedRouteConfigState], error) {
	c := clientFor(ctx)

	projectName := req.State.ProjectName
	if projectName == "" {
		projectName = req.ID
	}

	cfg, err := c.GetAutogeneratedRouteConfigForProject(ctx, projectName)
	if err != nil {
		if errors.Is(err, client.ErrNotFound) {
			return infer.ReadResponse[ProjectAutogeneratedRouteConfigArgs, ProjectAutogeneratedRouteConfigState]{}, nil
		}
		return infer.ReadResponse[ProjectAutogeneratedRouteConfigArgs, ProjectAutogeneratedRouteConfigState]{}, fmt.Errorf("failed to read project autogenerated route config: %w", err)
	}
	if cfg == nil {
		// Config was removed externally
		return infer.ReadResponse[ProjectAutogeneratedRouteConfigArgs, ProjectAutogeneratedRouteConfigState]{}, nil
	}

	args := autogeneratedRouteConfigToProjectArgs(projectName, cfg)
	st := ProjectAutogeneratedRouteConfigState{ProjectAutogeneratedRouteConfigArgs: args}

	return infer.ReadResponse[ProjectAutogeneratedRouteConfigArgs, ProjectAutogeneratedRouteConfigState]{
		ID:     projectName,
		Inputs: args,
		State:  st,
	}, nil
}

func (r *ProjectAutogeneratedRouteConfig) Diff(ctx context.Context, req infer.DiffRequest[ProjectAutogeneratedRouteConfigArgs, ProjectAutogeneratedRouteConfigState]) (infer.DiffResponse, error) {
	diff := map[string]p.PropertyDiff{}

	if req.Inputs.ProjectName != req.State.ProjectName {
		diff["projectName"] = p.PropertyDiff{Kind: p.UpdateReplace}
	}
	if ptrBoolDiffers(req.Inputs.Enabled, req.State.Enabled) {
		diff["enabled"] = p.PropertyDiff{Kind: p.Update}
	}
	if ptrBoolDiffers(req.Inputs.AllowPullRequests, req.State.AllowPullRequests) {
		diff["allowPullRequests"] = p.PropertyDiff{Kind: p.Update}
	}
	if prefixesDiffer(req.Inputs.Prefixes, req.State.Prefixes) {
		diff["prefixes"] = p.PropertyDiff{Kind: p.Update}
	}
	if autogeneratedPathRoutesDiffer(req.Inputs.PathRoutes, req.State.PathRoutes) {
		diff["pathRoutes"] = p.PropertyDiff{Kind: p.Update}
	}
	if ptrBoolDiffers(req.Inputs.DisableRequestVerification, req.State.DisableRequestVerification) {
		diff["disableRequestVerification"] = p.PropertyDiff{Kind: p.Update}
	}
	if ptrDiffers(req.Inputs.Insecure, req.State.Insecure) {
		diff["insecure"] = p.PropertyDiff{Kind: p.Update}
	}
	if ptrBoolDiffers(req.Inputs.TLSAcme, req.State.TLSAcme) {
		diff["tlsAcme"] = p.PropertyDiff{Kind: p.Update}
	}

	return p.DiffResponse{HasChanges: len(diff) > 0, DetailedDiff: diff, DeleteBeforeReplace: true}, nil
}

// --- Helpers ---

func buildAutogeneratedRouteConfigPatch(
	enabled, allowPRs *bool,
	prefixes *[]string,
	pathRoutes *[]AutogeneratedPathRouteInput,
	disableVerification *bool,
	insecure *string,
	tlsAcme *bool,
) map[string]any {
	patch := map[string]any{}
	setOptionalBool(patch, "enabled", enabled)
	setOptionalBool(patch, "allowPullRequests", allowPRs)
	setOptionalBool(patch, "disableRequestVerification", disableVerification)
	setOptionalBool(patch, "tlsAcme", tlsAcme)
	setOptional(patch, "insecure", insecure)

	if prefixes != nil {
		patch["prefixes"] = *prefixes
	}
	if pathRoutes != nil {
		prs := make([]map[string]any, len(*pathRoutes))
		for i, pr := range *pathRoutes {
			prs[i] = map[string]any{
				"fromService": pr.FromService,
				"toService":   pr.ToService,
				"path":        pr.Path,
			}
		}
		patch["pathRoutes"] = prs
	}
	return patch
}

func autogeneratedRouteConfigToProjectArgs(projectName string, cfg *client.AutogeneratedRouteConfig) ProjectAutogeneratedRouteConfigArgs {
	args := ProjectAutogeneratedRouteConfigArgs{
		ProjectName:                projectName,
		Enabled:                    cfg.Enabled,
		AllowPullRequests:          cfg.AllowPullRequests,
		DisableRequestVerification: cfg.DisableRequestVerification,
		TLSAcme:                    cfg.TLSAcme,
	}
	if cfg.Insecure != "" {
		args.Insecure = &cfg.Insecure
	}
	if len(cfg.Prefixes) > 0 {
		args.Prefixes = &cfg.Prefixes
	}
	if len(cfg.PathRoutes) > 0 {
		prs := make([]AutogeneratedPathRouteInput, len(cfg.PathRoutes))
		for i, pr := range cfg.PathRoutes {
			prs[i] = AutogeneratedPathRouteInput{
				FromService: pr.FromService,
				ToService:   pr.ToService,
				Path:        pr.Path,
			}
		}
		args.PathRoutes = &prs
	}
	return args
}

func prefixesDiffer(a, b *[]string) bool {
	aLen, bLen := 0, 0
	if a != nil {
		aLen = len(*a)
	}
	if b != nil {
		bLen = len(*b)
	}
	if aLen == 0 && bLen == 0 {
		return false
	}
	if aLen != bLen {
		return true
	}
	for i, v := range *a {
		if (*b)[i] != v {
			return true
		}
	}
	return false
}

func autogeneratedPathRoutesDiffer(a, b *[]AutogeneratedPathRouteInput) bool {
	aLen, bLen := 0, 0
	if a != nil {
		aLen = len(*a)
	}
	if b != nil {
		bLen = len(*b)
	}
	if aLen == 0 && bLen == 0 {
		return false
	}
	if aLen != bLen {
		return true
	}
	type key struct{ from, to, path string }
	bSet := make(map[key]struct{}, bLen)
	for _, pr := range *b {
		bSet[key{pr.FromService, pr.ToService, pr.Path}] = struct{}{}
	}
	for _, pr := range *a {
		if _, ok := bSet[key{pr.FromService, pr.ToService, pr.Path}]; !ok {
			return true
		}
	}
	return false
}
