package resources

import (
	"context"
	"errors"
	"fmt"
	"strconv"
	"strings"

	p "github.com/pulumi/pulumi-go-provider"
	"github.com/pulumi/pulumi-go-provider/infer"
	"github.com/tag1consulting/pulumi-lagoon/provider/pkg/client"
)

// Route manages a Lagoon API-defined route on a project, with optional environment attachment.
type Route struct{}

// RouteAnnotationInput is a key/value annotation on a route.
type RouteAnnotationInput struct {
	Key   string `pulumi:"key"`
	Value string `pulumi:"value"`
}

// RoutePathRouteInput is a path-based routing rule on a route.
type RoutePathRouteInput struct {
	Path      string `pulumi:"path"`
	ToService string `pulumi:"toService"`
}

// RouteArgs defines the user-provided inputs for a LagoonRoute resource.
type RouteArgs struct {
	ProjectName                string                 `pulumi:"projectName"`
	Domain                     string                 `pulumi:"domain"`
	Service                    *string                `pulumi:"service,optional"`
	Environment                *string                `pulumi:"environment,optional"`
	TLSAcme                    *bool                  `pulumi:"tlsAcme,optional"`
	Insecure                   *string                `pulumi:"insecure,optional"`
	RouteType                  *string                `pulumi:"routeType,optional"`
	Primary                    *bool                  `pulumi:"primary,optional"`
	MonitoringPath             *string                `pulumi:"monitoringPath,optional"`
	DisableRequestVerification *bool                  `pulumi:"disableRequestVerification,optional"`
	HSTSEnabled                *bool                  `pulumi:"hstsEnabled,optional"`
	HSTSPreload                *bool                  `pulumi:"hstsPreload,optional"`
	HSTSIncludeSubdomains      *bool                  `pulumi:"hstsIncludeSubdomains,optional"`
	HSTSMaxAge                 *int                   `pulumi:"hstsMaxAge,optional"`
	Annotations                *[]RouteAnnotationInput `pulumi:"annotations,optional"`
	AlternativeNames           *[]string              `pulumi:"alternativeNames,optional"`
	PathRoutes                 *[]RoutePathRouteInput  `pulumi:"pathRoutes,optional"`
}

// RouteState is the full persisted state for a LagoonRoute resource.
type RouteState struct {
	RouteArgs
	LagoonID int    `pulumi:"lagoonId"`
	Source   string `pulumi:"source"`
	Created  string `pulumi:"created"`
	Updated  string `pulumi:"updated"`
}

func (r *Route) Annotate(a infer.Annotator) {
	a.SetToken("lagoon", "Route")
	a.Describe(&r, "Manages a Lagoon API-defined route on a project (requires Lagoon v2.29.0+).")
}

func (a *RouteArgs) Annotate(an infer.Annotator) {
	an.Describe(&a.ProjectName, "The Lagoon project name this route belongs to.")
	an.Describe(&a.Domain, "The primary domain for the route (e.g., 'example.com'). Changing this forces replacement.")
	an.Describe(&a.Service, "The service to route traffic to (e.g., 'nginx').")
	an.Describe(&a.Environment, "The environment to attach this route to.")
	an.Describe(&a.TLSAcme, "Whether to use Let's Encrypt for TLS. Defaults to true.")
	an.Describe(&a.Insecure, "How to handle insecure (HTTP) traffic: Allow, Redirect, or None. Defaults to Redirect.")
	an.Describe(&a.RouteType, "Route type for active/standby: STANDARD, ACTIVE, or STANDBY.")
	an.Describe(&a.Primary, "Whether this is the primary route.")
	an.Describe(&a.MonitoringPath, "Path to use for uptime monitoring.")
	an.Describe(&a.DisableRequestVerification, "Whether to disable request verification.")
	an.Describe(&a.HSTSEnabled, "Whether to enable HTTP Strict Transport Security.")
	an.Describe(&a.HSTSPreload, "Whether to include the preload directive in HSTS.")
	an.Describe(&a.HSTSIncludeSubdomains, "Whether to include subdomains in HSTS.")
	an.Describe(&a.HSTSMaxAge, "HSTS max-age in seconds.")
	an.Describe(&a.Annotations, "Ingress annotations (key/value pairs, max 10).")
	an.Describe(&a.AlternativeNames, "Additional SAN domains for the TLS certificate (max 25).")
	an.Describe(&a.PathRoutes, "Path-based routing rules (max 10).")
}

func (s *RouteState) Annotate(an infer.Annotator) {
	an.Describe(&s.LagoonID, "The Lagoon-assigned numeric route ID.")
	an.Describe(&s.Source, "The source of this route: API, YAML, or AUTOGENERATED.")
	an.Describe(&s.Created, "Timestamp when the route was created.")
	an.Describe(&s.Updated, "Timestamp when the route was last updated.")
}

func (r *Route) Create(ctx context.Context, req infer.CreateRequest[RouteArgs]) (infer.CreateResponse[RouteState], error) {
	if req.DryRun {
		return infer.CreateResponse[RouteState]{
			ID:     "preview-id",
			Output: RouteState{RouteArgs: req.Inputs},
		}, nil
	}

	c := clientFor(ctx)
	args := req.Inputs

	if err := validateRouteEnums(args.Insecure, args.RouteType); err != nil {
		return infer.CreateResponse[RouteState]{}, err
	}

	input := map[string]any{
		"project": args.ProjectName,
		"domain":  args.Domain,
	}
	setOptional(input, "service", args.Service)
	setOptionalBool(input, "tlsAcme", args.TLSAcme)
	if args.Insecure != nil {
		input["insecure"] = *args.Insecure
	}
	if args.RouteType != nil {
		input["type"] = strings.ToUpper(*args.RouteType)
	}
	setOptionalBool(input, "primary", args.Primary)
	setOptionalBool(input, "disableRequestVerification", args.DisableRequestVerification)
	setOptionalBool(input, "hstsEnabled", args.HSTSEnabled)
	setOptionalBool(input, "hstsPreload", args.HSTSPreload)
	setOptionalBool(input, "hstsIncludeSubdomains", args.HSTSIncludeSubdomains)
	setOptionalInt(input, "hstsMaxAge", args.HSTSMaxAge)

	if args.Annotations != nil && len(*args.Annotations) > 0 {
		anns := make([]map[string]any, len(*args.Annotations))
		for i, a := range *args.Annotations {
			anns[i] = map[string]any{"key": a.Key, "value": a.Value}
		}
		input["annotations"] = anns
	}
	if args.AlternativeNames != nil && len(*args.AlternativeNames) > 0 {
		input["alternativeNames"] = *args.AlternativeNames
	}
	if args.PathRoutes != nil && len(*args.PathRoutes) > 0 {
		prs := make([]map[string]any, len(*args.PathRoutes))
		for i, pr := range *args.PathRoutes {
			prs[i] = map[string]any{"path": pr.Path, "toService": pr.ToService}
		}
		input["pathRoutes"] = prs
	}

	// Optionally attach to environment at creation time
	if args.Environment != nil {
		input["environment"] = *args.Environment
	}

	route, err := c.AddRouteToProject(ctx, input)
	if err != nil {
		return infer.CreateResponse[RouteState]{}, fmt.Errorf("failed to create route: %w", err)
	}

	// monitoringPath is not in AddRouteToProjectInput — apply via update
	if args.MonitoringPath != nil {
		patch := map[string]any{
			"domain":         args.Domain,
			"project":        args.ProjectName,
			"patch":          map[string]any{"monitoringPath": *args.MonitoringPath},
		}
		if _, err := c.UpdateRouteOnProject(ctx, route.ID, patch); err != nil {
			// Non-fatal: route exists, monitoringPath will be set on next apply
			_ = err
		}
	}

	return infer.CreateResponse[RouteState]{
		ID: strconv.Itoa(route.ID),
		Output: RouteState{
			RouteArgs: args,
			LagoonID:  route.ID,
			Source:    route.Source,
			Created:   route.Created,
			Updated:   route.Updated,
		},
	}, nil
}

func (r *Route) Update(ctx context.Context, req infer.UpdateRequest[RouteArgs, RouteState]) (infer.UpdateResponse[RouteState], error) {
	if req.DryRun {
		return infer.UpdateResponse[RouteState]{
			Output: RouteState{RouteArgs: req.Inputs, LagoonID: req.State.LagoonID, Source: req.State.Source, Created: req.State.Created},
		}, nil
	}

	c := clientFor(ctx)
	args := req.Inputs
	state := req.State

	if err := validateRouteEnums(args.Insecure, args.RouteType); err != nil {
		return infer.UpdateResponse[RouteState]{}, err
	}

	// Build scalar patch
	patch := map[string]any{}
	if args.TLSAcme != state.TLSAcme {
		setOptionalBool(patch, "tlsAcme", args.TLSAcme)
	}
	if ptrDiffers(args.Insecure, state.Insecure) {
		setOptional(patch, "insecure", args.Insecure)
	}
	if ptrDiffers(args.MonitoringPath, state.MonitoringPath) {
		setOptional(patch, "monitoringPath", args.MonitoringPath)
	}
	if args.DisableRequestVerification != state.DisableRequestVerification {
		setOptionalBool(patch, "disableRequestVerification", args.DisableRequestVerification)
	}
	if args.HSTSEnabled != state.HSTSEnabled {
		setOptionalBool(patch, "hstsEnabled", args.HSTSEnabled)
	}
	if args.HSTSPreload != state.HSTSPreload {
		setOptionalBool(patch, "hstsPreload", args.HSTSPreload)
	}
	if args.HSTSIncludeSubdomains != state.HSTSIncludeSubdomains {
		setOptionalBool(patch, "hstsIncludeSubdomains", args.HSTSIncludeSubdomains)
	}
	if ptrIntDiffers(args.HSTSMaxAge, state.HSTSMaxAge) {
		setOptionalInt(patch, "hstsMaxAge", args.HSTSMaxAge)
	}

	if len(patch) > 0 {
		updateInput := map[string]any{
			"domain":  args.Domain,
			"project": args.ProjectName,
			"patch":   patch,
		}
		if _, err := c.UpdateRouteOnProject(ctx, state.LagoonID, updateInput); err != nil {
			return infer.UpdateResponse[RouteState]{}, fmt.Errorf("failed to update route: %w", err)
		}
	}

	// Reconcile annotations
	if annotationsDiffer(args.Annotations, state.Annotations) {
		if err := reconcileAnnotations(ctx, c, state.LagoonID, state.Annotations, args.Annotations); err != nil {
			return infer.UpdateResponse[RouteState]{}, err
		}
	}

	// Reconcile alternative names
	if alternativeNamesDiffer(args.AlternativeNames, state.AlternativeNames) {
		if err := reconcileAlternativeNames(ctx, c, state.LagoonID, state.AlternativeNames, args.AlternativeNames); err != nil {
			return infer.UpdateResponse[RouteState]{}, err
		}
	}

	// Reconcile path routes
	if pathRoutesDiffer(args.PathRoutes, state.PathRoutes) {
		if err := reconcilePathRoutes(ctx, c, state.LagoonID, state.PathRoutes, args.PathRoutes); err != nil {
			return infer.UpdateResponse[RouteState]{}, err
		}
	}

	// Reconcile environment attachment
	if ptrDiffers(args.Environment, state.Environment) {
		if err := reconcileEnvironment(ctx, c, args.Domain, args.ProjectName, state.Environment, args.Environment, args.Service, args.Primary, args.RouteType); err != nil {
			return infer.UpdateResponse[RouteState]{}, err
		}
	}

	return infer.UpdateResponse[RouteState]{
		Output: RouteState{
			RouteArgs: args,
			LagoonID:  state.LagoonID,
			Source:    state.Source,
			Created:   state.Created,
		},
	}, nil
}

func (r *Route) Delete(ctx context.Context, req infer.DeleteRequest[RouteState]) (infer.DeleteResponse, error) {
	c := clientFor(ctx)
	state := req.State

	// Detach from environment before deleting
	if state.Environment != nil && *state.Environment != "" {
		if err := c.RemoveRouteFromEnvironment(ctx, state.Domain, state.ProjectName, *state.Environment); err != nil {
			if !errors.Is(err, client.ErrNotFound) {
				return infer.DeleteResponse{}, fmt.Errorf("failed to detach route from environment: %w", err)
			}
		}
	}

	if err := c.DeleteRoute(ctx, state.LagoonID); err != nil {
		if errors.Is(err, client.ErrNotFound) {
			return infer.DeleteResponse{}, nil
		}
		return infer.DeleteResponse{}, fmt.Errorf("failed to delete route: %w", err)
	}
	return infer.DeleteResponse{}, nil
}

func (r *Route) Read(ctx context.Context, req infer.ReadRequest[RouteArgs, RouteState]) (infer.ReadResponse[RouteArgs, RouteState], error) {
	c := clientFor(ctx)

	// Determine projectName and domain: prefer state, fall back to import ID parsing
	projectName := req.State.ProjectName
	domain := req.State.Domain
	if projectName == "" || domain == "" {
		// Parse import ID: "{projectName}:{domain}"
		parts := strings.SplitN(req.ID, ":", 2)
		if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
			return infer.ReadResponse[RouteArgs, RouteState]{}, fmt.Errorf("invalid route ID %q: expected '{projectName}:{domain}'", req.ID)
		}
		projectName = parts[0]
		domain = parts[1]
	}

	route, err := c.GetRouteByDomain(ctx, projectName, domain)
	if err != nil {
		if errors.Is(err, client.ErrNotFound) {
			return infer.ReadResponse[RouteArgs, RouteState]{}, nil
		}
		return infer.ReadResponse[RouteArgs, RouteState]{}, fmt.Errorf("failed to read route: %w", err)
	}

	args := routeToArgs(route, req.State)
	st := RouteState{
		RouteArgs: args,
		LagoonID:  route.ID,
		Source:    route.Source,
		Created:   route.Created,
		Updated:   route.Updated,
	}

	return infer.ReadResponse[RouteArgs, RouteState]{
		ID:     strconv.Itoa(route.ID),
		Inputs: args,
		State:  st,
	}, nil
}

func (r *Route) Diff(ctx context.Context, req infer.DiffRequest[RouteArgs, RouteState]) (infer.DiffResponse, error) {
	diff := map[string]p.PropertyDiff{}

	// Identity fields — force replacement
	if req.Inputs.ProjectName != req.State.ProjectName {
		diff["projectName"] = p.PropertyDiff{Kind: p.UpdateReplace}
	}
	if req.Inputs.Domain != req.State.Domain {
		diff["domain"] = p.PropertyDiff{Kind: p.UpdateReplace}
	}

	// In-place update fields
	if ptrDiffers(req.Inputs.Service, req.State.Service) {
		diff["service"] = p.PropertyDiff{Kind: p.Update}
	}
	if ptrDiffers(req.Inputs.Environment, req.State.Environment) {
		diff["environment"] = p.PropertyDiff{Kind: p.Update}
	}
	if req.Inputs.TLSAcme != req.State.TLSAcme {
		diff["tlsAcme"] = p.PropertyDiff{Kind: p.Update}
	}
	if ptrDiffers(req.Inputs.Insecure, req.State.Insecure) {
		diff["insecure"] = p.PropertyDiff{Kind: p.Update}
	}
	if ptrDiffers(req.Inputs.RouteType, req.State.RouteType) {
		diff["routeType"] = p.PropertyDiff{Kind: p.Update}
	}
	if req.Inputs.Primary != req.State.Primary {
		diff["primary"] = p.PropertyDiff{Kind: p.Update}
	}
	if ptrDiffers(req.Inputs.MonitoringPath, req.State.MonitoringPath) {
		diff["monitoringPath"] = p.PropertyDiff{Kind: p.Update}
	}
	if req.Inputs.DisableRequestVerification != req.State.DisableRequestVerification {
		diff["disableRequestVerification"] = p.PropertyDiff{Kind: p.Update}
	}
	if req.Inputs.HSTSEnabled != req.State.HSTSEnabled {
		diff["hstsEnabled"] = p.PropertyDiff{Kind: p.Update}
	}
	if req.Inputs.HSTSPreload != req.State.HSTSPreload {
		diff["hstsPreload"] = p.PropertyDiff{Kind: p.Update}
	}
	if req.Inputs.HSTSIncludeSubdomains != req.State.HSTSIncludeSubdomains {
		diff["hstsIncludeSubdomains"] = p.PropertyDiff{Kind: p.Update}
	}
	if ptrIntDiffers(req.Inputs.HSTSMaxAge, req.State.HSTSMaxAge) {
		diff["hstsMaxAge"] = p.PropertyDiff{Kind: p.Update}
	}
	if annotationsDiffer(req.Inputs.Annotations, req.State.Annotations) {
		diff["annotations"] = p.PropertyDiff{Kind: p.Update}
	}
	if alternativeNamesDiffer(req.Inputs.AlternativeNames, req.State.AlternativeNames) {
		diff["alternativeNames"] = p.PropertyDiff{Kind: p.Update}
	}
	if pathRoutesDiffer(req.Inputs.PathRoutes, req.State.PathRoutes) {
		diff["pathRoutes"] = p.PropertyDiff{Kind: p.Update}
	}

	return p.DiffResponse{HasChanges: len(diff) > 0, DetailedDiff: diff, DeleteBeforeReplace: true}, nil
}

// --- Helpers ---

// validateRouteEnums checks that insecure and routeType values are valid.
func validateRouteEnums(insecure, routeType *string) error {
	if insecure != nil {
		switch *insecure {
		case "Allow", "Redirect", "None":
		default:
			return fmt.Errorf("insecure must be Allow, Redirect, or None; got %q", *insecure)
		}
	}
	if routeType != nil {
		switch strings.ToUpper(*routeType) {
		case "STANDARD", "ACTIVE", "STANDBY":
		default:
			return fmt.Errorf("routeType must be STANDARD, ACTIVE, or STANDBY; got %q", *routeType)
		}
	}
	return nil
}

// routeToArgs maps a client.Route back to RouteArgs, preserving optional state for fields not returned by API.
func routeToArgs(route *client.Route, state RouteState) RouteArgs {
	args := RouteArgs{
		ProjectName:                route.ProjectName,
		Domain:                     route.Domain,
		TLSAcme:                    route.TLSAcme,
		Primary:                    route.Primary,
		DisableRequestVerification: route.DisableRequestVerification,
		HSTSEnabled:                route.HSTSEnabled,
		HSTSPreload:                route.HSTSPreload,
		HSTSIncludeSubdomains:      route.HSTSIncludeSubdomains,
		HSTSMaxAge:                 route.HSTSMaxAge,
	}

	if route.Service != "" {
		args.Service = &route.Service
	}
	if route.EnvironmentName != "" {
		envName := route.EnvironmentName
		args.Environment = &envName
	}
	if route.Insecure != "" {
		args.Insecure = &route.Insecure
	}
	if route.Type != "" {
		t := route.Type
		args.RouteType = &t
	}
	if route.MonitoringPath != "" {
		args.MonitoringPath = &route.MonitoringPath
	}

	if len(route.Annotations) > 0 {
		anns := make([]RouteAnnotationInput, len(route.Annotations))
		for i, a := range route.Annotations {
			anns[i] = RouteAnnotationInput{Key: a.Key, Value: a.Value}
		}
		args.Annotations = &anns
	} else {
		// Preserve nil vs empty from state to avoid spurious diffs
		args.Annotations = state.Annotations
	}

	if len(route.AlternativeNames) > 0 {
		names := make([]string, len(route.AlternativeNames))
		for i, an := range route.AlternativeNames {
			names[i] = an.Domain
		}
		args.AlternativeNames = &names
	} else {
		args.AlternativeNames = state.AlternativeNames
	}

	if len(route.PathRoutes) > 0 {
		prs := make([]RoutePathRouteInput, len(route.PathRoutes))
		for i, pr := range route.PathRoutes {
			prs[i] = RoutePathRouteInput{Path: pr.Path, ToService: pr.ToService}
		}
		args.PathRoutes = &prs
	} else {
		args.PathRoutes = state.PathRoutes
	}

	return args
}

// annotationsDiffer returns true if two optional annotation slices differ.
func annotationsDiffer(a, b *[]RouteAnnotationInput) bool {
	aLen, bLen := 0, 0
	if a != nil {
		aLen = len(*a)
	}
	if b != nil {
		bLen = len(*b)
	}
	if aLen == 0 && bLen == 0 {
		return false
	}
	if aLen != bLen {
		return true
	}
	// Build map from state for comparison
	bMap := make(map[string]string, bLen)
	for _, ann := range *b {
		bMap[ann.Key] = ann.Value
	}
	for _, ann := range *a {
		if v, ok := bMap[ann.Key]; !ok || v != ann.Value {
			return true
		}
	}
	return false
}

// alternativeNamesDiffer returns true if two optional string slices differ.
func alternativeNamesDiffer(a, b *[]string) bool {
	aLen, bLen := 0, 0
	if a != nil {
		aLen = len(*a)
	}
	if b != nil {
		bLen = len(*b)
	}
	if aLen == 0 && bLen == 0 {
		return false
	}
	if aLen != bLen {
		return true
	}
	bSet := make(map[string]struct{}, bLen)
	for _, n := range *b {
		bSet[n] = struct{}{}
	}
	for _, n := range *a {
		if _, ok := bSet[n]; !ok {
			return true
		}
	}
	return false
}

// pathRoutesDiffer returns true if two optional path route slices differ.
func pathRoutesDiffer(a, b *[]RoutePathRouteInput) bool {
	aLen, bLen := 0, 0
	if a != nil {
		aLen = len(*a)
	}
	if b != nil {
		bLen = len(*b)
	}
	if aLen == 0 && bLen == 0 {
		return false
	}
	if aLen != bLen {
		return true
	}
	type key struct{ path, svc string }
	bSet := make(map[key]struct{}, bLen)
	for _, pr := range *b {
		bSet[key{pr.Path, pr.ToService}] = struct{}{}
	}
	for _, pr := range *a {
		if _, ok := bSet[key{pr.Path, pr.ToService}]; !ok {
			return true
		}
	}
	return false
}

// reconcileAnnotations adds/removes annotations to match the desired state.
func reconcileAnnotations(ctx context.Context, c LagoonClient, routeID int, old, new *[]RouteAnnotationInput) error {
	oldMap := make(map[string]string)
	if old != nil {
		for _, a := range *old {
			oldMap[a.Key] = a.Value
		}
	}
	newMap := make(map[string]string)
	if new != nil {
		for _, a := range *new {
			newMap[a.Key] = a.Value
		}
	}

	// Remove annotations no longer present or with changed value
	for key := range oldMap {
		if newVal, ok := newMap[key]; !ok || newVal != oldMap[key] {
			if _, err := c.RemoveRouteAnnotation(ctx, routeID, key); err != nil {
				return fmt.Errorf("failed to remove annotation %q: %w", key, err)
			}
		}
	}

	// Add new or changed annotations
	var toAdd []map[string]string
	for key, val := range newMap {
		if oldVal, ok := oldMap[key]; !ok || oldVal != val {
			toAdd = append(toAdd, map[string]string{"key": key, "value": val})
		}
	}
	if len(toAdd) > 0 {
		if _, err := c.AddRouteAnnotations(ctx, routeID, toAdd); err != nil {
			return fmt.Errorf("failed to add annotations: %w", err)
		}
	}
	return nil
}

// reconcileAlternativeNames adds/removes alternative domains to match the desired state.
func reconcileAlternativeNames(ctx context.Context, c LagoonClient, routeID int, old, new *[]string) error {
	oldSet := make(map[string]struct{})
	if old != nil {
		for _, n := range *old {
			oldSet[n] = struct{}{}
		}
	}
	newSet := make(map[string]struct{})
	if new != nil {
		for _, n := range *new {
			newSet[n] = struct{}{}
		}
	}

	// Remove first
	for name := range oldSet {
		if _, ok := newSet[name]; !ok {
			if _, err := c.RemoveRouteAlternativeDomain(ctx, routeID, name); err != nil {
				return fmt.Errorf("failed to remove alternative name %q: %w", name, err)
			}
		}
	}

	// Add new
	var toAdd []string
	for name := range newSet {
		if _, ok := oldSet[name]; !ok {
			toAdd = append(toAdd, name)
		}
	}
	if len(toAdd) > 0 {
		if _, err := c.AddRouteAlternativeDomains(ctx, routeID, toAdd); err != nil {
			return fmt.Errorf("failed to add alternative names: %w", err)
		}
	}
	return nil
}

// reconcilePathRoutes adds/removes path routes to match the desired state.
func reconcilePathRoutes(ctx context.Context, c LagoonClient, routeID int, old, new *[]RoutePathRouteInput) error {
	type key struct{ path, svc string }

	oldSet := make(map[key]struct{})
	if old != nil {
		for _, pr := range *old {
			oldSet[key{pr.Path, pr.ToService}] = struct{}{}
		}
	}
	newSet := make(map[key]struct{})
	if new != nil {
		for _, pr := range *new {
			newSet[key{pr.Path, pr.ToService}] = struct{}{}
		}
	}

	// Remove first
	if old != nil {
		for _, pr := range *old {
			k := key{pr.Path, pr.ToService}
			if _, ok := newSet[k]; !ok {
				if _, err := c.RemovePathRouteFromRoute(ctx, routeID, pr.ToService, pr.Path); err != nil {
					return fmt.Errorf("failed to remove path route %s->%s: %w", pr.Path, pr.ToService, err)
				}
			}
		}
	}

	// Add new
	var toAdd []map[string]string
	if new != nil {
		for _, pr := range *new {
			k := key{pr.Path, pr.ToService}
			if _, ok := oldSet[k]; !ok {
				toAdd = append(toAdd, map[string]string{"path": pr.Path, "toService": pr.ToService})
			}
		}
	}
	if len(toAdd) > 0 {
		if _, err := c.AddPathRoutesToRoute(ctx, routeID, toAdd); err != nil {
			return fmt.Errorf("failed to add path routes: %w", err)
		}
	}
	return nil
}

// reconcileEnvironment handles environment attachment changes.
func reconcileEnvironment(ctx context.Context, c LagoonClient, domain, project string, oldEnv, newEnv, service *string, primary *bool, routeType *string) error {
	// Detach from old environment if it was set
	if oldEnv != nil && *oldEnv != "" {
		if err := c.RemoveRouteFromEnvironment(ctx, domain, project, *oldEnv); err != nil {
			if !errors.Is(err, client.ErrNotFound) {
				return fmt.Errorf("failed to detach route from environment %q: %w", *oldEnv, err)
			}
		}
	}

	// Attach to new environment if set
	if newEnv != nil && *newEnv != "" {
		input := map[string]any{
			"domain":      domain,
			"project":     project,
			"environment": *newEnv,
		}
		if service != nil {
			input["service"] = *service
		}
		if primary != nil {
			input["primary"] = *primary
		}
		if routeType != nil {
			input["type"] = strings.ToUpper(*routeType)
		}
		if _, err := c.AddOrUpdateRouteOnEnvironment(ctx, input); err != nil {
			return fmt.Errorf("failed to attach route to environment %q: %w", *newEnv, err)
		}
	}
	return nil
}
