// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package lagoon

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/internal"
)

type Provider struct {
	pulumi.ProviderResourceState

	// The Lagoon GraphQL API endpoint URL.
	ApiUrl pulumi.StringPtrOutput `pulumi:"apiUrl"`
	// The audience claim for generated JWT tokens. Defaults to 'api.dev'.
	JwtAudience pulumi.StringPtrOutput `pulumi:"jwtAudience"`
	// The Lagoon core JWTSECRET. Used to generate admin tokens on-the-fly.
	JwtSecret pulumi.StringPtrOutput `pulumi:"jwtSecret"`
	// A pre-configured JWT authentication token for the Lagoon API.
	Token pulumi.StringPtrOutput `pulumi:"token"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.ApiUrl == nil {
		if d := internal.GetEnvOrDefault("https://api.lagoon.sh/graphql", nil, "LAGOON_API_URL"); d != nil {
			args.ApiUrl = pulumi.StringPtr(d.(string))
		}
	}
	if args.Insecure == nil {
		if d := internal.GetEnvOrDefault(false, internal.ParseEnvBool, "LAGOON_INSECURE"); d != nil {
			args.Insecure = pulumi.BoolPtr(d.(bool))
		}
	}
	if args.JwtAudience == nil {
		if d := internal.GetEnvOrDefault("api.dev", nil, "LAGOON_JWT_AUDIENCE"); d != nil {
			args.JwtAudience = pulumi.StringPtr(d.(string))
		}
	}
	if args.JwtSecret == nil {
		if d := internal.GetEnvOrDefault(nil, nil, "LAGOON_JWT_SECRET"); d != nil {
			args.JwtSecret = pulumi.StringPtr(d.(string))
		}
	}
	if args.Token == nil {
		if d := internal.GetEnvOrDefault(nil, nil, "LAGOON_TOKEN"); d != nil {
			args.Token = pulumi.StringPtr(d.(string))
		}
	}
	if args.ApiUrl != nil {
		args.ApiUrl = pulumi.ToSecret(args.ApiUrl).(pulumi.StringPtrInput)
	}
	if args.JwtSecret != nil {
		args.JwtSecret = pulumi.ToSecret(args.JwtSecret).(pulumi.StringPtrInput)
	}
	if args.Token != nil {
		args.Token = pulumi.ToSecret(args.Token).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"apiUrl",
		"jwtSecret",
		"token",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:lagoon", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// The Lagoon GraphQL API endpoint URL.
	ApiUrl *string `pulumi:"apiUrl"`
	// Disable SSL certificate verification when connecting to the Lagoon API.
	Insecure *bool `pulumi:"insecure"`
	// The audience claim for generated JWT tokens. Defaults to 'api.dev'.
	JwtAudience *string `pulumi:"jwtAudience"`
	// The Lagoon core JWTSECRET. Used to generate admin tokens on-the-fly.
	JwtSecret *string `pulumi:"jwtSecret"`
	// A pre-configured JWT authentication token for the Lagoon API.
	Token *string `pulumi:"token"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// The Lagoon GraphQL API endpoint URL.
	ApiUrl pulumi.StringPtrInput
	// Disable SSL certificate verification when connecting to the Lagoon API.
	Insecure pulumi.BoolPtrInput
	// The audience claim for generated JWT tokens. Defaults to 'api.dev'.
	JwtAudience pulumi.StringPtrInput
	// The Lagoon core JWTSECRET. Used to generate admin tokens on-the-fly.
	JwtSecret pulumi.StringPtrInput
	// A pre-configured JWT authentication token for the Lagoon API.
	Token pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// The Lagoon GraphQL API endpoint URL.
func (o ProviderOutput) ApiUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiUrl }).(pulumi.StringPtrOutput)
}

// The audience claim for generated JWT tokens. Defaults to 'api.dev'.
func (o ProviderOutput) JwtAudience() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.JwtAudience }).(pulumi.StringPtrOutput)
}

// The Lagoon core JWTSECRET. Used to generate admin tokens on-the-fly.
func (o ProviderOutput) JwtSecret() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.JwtSecret }).(pulumi.StringPtrOutput)
}

// A pre-configured JWT authentication token for the Lagoon API.
func (o ProviderOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Token }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
