# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ProviderArgs', 'Provider']

@pulumi.input_type
class ProviderArgs:
    def __init__(__self__, *,
                 api_url: Optional[pulumi.Input[_builtins.str]] = None,
                 insecure: Optional[pulumi.Input[_builtins.bool]] = None,
                 jwt_audience: Optional[pulumi.Input[_builtins.str]] = None,
                 jwt_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 token: Optional[pulumi.Input[_builtins.str]] = None):
        """
        The set of arguments for constructing a Provider resource.

        :param pulumi.Input[_builtins.str] api_url: The Lagoon GraphQL API endpoint URL.
        :param pulumi.Input[_builtins.bool] insecure: Disable SSL certificate verification when connecting to the Lagoon API.
        :param pulumi.Input[_builtins.str] jwt_audience: The audience claim for generated JWT tokens. Defaults to 'api.dev'.
        :param pulumi.Input[_builtins.str] jwt_secret: The Lagoon core JWTSECRET. Used to generate admin tokens on-the-fly.
        :param pulumi.Input[_builtins.str] token: A pre-configured JWT authentication token for the Lagoon API.
        """
        if api_url is None:
            api_url = (_utilities.get_env('LAGOON_API_URL') or 'https://api.lagoon.sh/graphql')
        if api_url is not None:
            pulumi.set(__self__, "api_url", api_url)
        if insecure is None:
            insecure = (_utilities.get_env_bool('LAGOON_INSECURE') or False)
        if insecure is not None:
            pulumi.set(__self__, "insecure", insecure)
        if jwt_audience is None:
            jwt_audience = (_utilities.get_env('LAGOON_JWT_AUDIENCE') or 'api.dev')
        if jwt_audience is not None:
            pulumi.set(__self__, "jwt_audience", jwt_audience)
        if jwt_secret is None:
            jwt_secret = _utilities.get_env('LAGOON_JWT_SECRET')
        if jwt_secret is not None:
            pulumi.set(__self__, "jwt_secret", jwt_secret)
        if token is None:
            token = _utilities.get_env('LAGOON_TOKEN')
        if token is not None:
            pulumi.set(__self__, "token", token)

    @_builtins.property
    @pulumi.getter(name="apiUrl")
    def api_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The Lagoon GraphQL API endpoint URL.
        """
        return pulumi.get(self, "api_url")

    @api_url.setter
    def api_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "api_url", value)

    @_builtins.property
    @pulumi.getter
    def insecure(self) -> Optional[pulumi.Input[_builtins.bool]]:
        """
        Disable SSL certificate verification when connecting to the Lagoon API.
        """
        return pulumi.get(self, "insecure")

    @insecure.setter
    def insecure(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "insecure", value)

    @_builtins.property
    @pulumi.getter(name="jwtAudience")
    def jwt_audience(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The audience claim for generated JWT tokens. Defaults to 'api.dev'.
        """
        return pulumi.get(self, "jwt_audience")

    @jwt_audience.setter
    def jwt_audience(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "jwt_audience", value)

    @_builtins.property
    @pulumi.getter(name="jwtSecret")
    def jwt_secret(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        The Lagoon core JWTSECRET. Used to generate admin tokens on-the-fly.
        """
        return pulumi.get(self, "jwt_secret")

    @jwt_secret.setter
    def jwt_secret(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "jwt_secret", value)

    @_builtins.property
    @pulumi.getter
    def token(self) -> Optional[pulumi.Input[_builtins.str]]:
        """
        A pre-configured JWT authentication token for the Lagoon API.
        """
        return pulumi.get(self, "token")

    @token.setter
    def token(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "token", value)


@pulumi.type_token("pulumi:providers:lagoon")
class Provider(pulumi.ProviderResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_url: Optional[pulumi.Input[_builtins.str]] = None,
                 insecure: Optional[pulumi.Input[_builtins.bool]] = None,
                 jwt_audience: Optional[pulumi.Input[_builtins.str]] = None,
                 jwt_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 token: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a Lagoon resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] api_url: The Lagoon GraphQL API endpoint URL.
        :param pulumi.Input[_builtins.bool] insecure: Disable SSL certificate verification when connecting to the Lagoon API.
        :param pulumi.Input[_builtins.str] jwt_audience: The audience claim for generated JWT tokens. Defaults to 'api.dev'.
        :param pulumi.Input[_builtins.str] jwt_secret: The Lagoon core JWTSECRET. Used to generate admin tokens on-the-fly.
        :param pulumi.Input[_builtins.str] token: A pre-configured JWT authentication token for the Lagoon API.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ProviderArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Lagoon resource with the given unique name, props, and options.

        :param str resource_name: The name of the resource.
        :param ProviderArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProviderArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 api_url: Optional[pulumi.Input[_builtins.str]] = None,
                 insecure: Optional[pulumi.Input[_builtins.bool]] = None,
                 jwt_audience: Optional[pulumi.Input[_builtins.str]] = None,
                 jwt_secret: Optional[pulumi.Input[_builtins.str]] = None,
                 token: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProviderArgs.__new__(ProviderArgs)

            if api_url is None:
                api_url = (_utilities.get_env('LAGOON_API_URL') or 'https://api.lagoon.sh/graphql')
            __props__.__dict__["api_url"] = None if api_url is None else pulumi.Output.secret(api_url)
            if insecure is None:
                insecure = (_utilities.get_env_bool('LAGOON_INSECURE') or False)
            __props__.__dict__["insecure"] = pulumi.Output.from_input(insecure).apply(pulumi.runtime.to_json) if insecure is not None else None
            if jwt_audience is None:
                jwt_audience = (_utilities.get_env('LAGOON_JWT_AUDIENCE') or 'api.dev')
            __props__.__dict__["jwt_audience"] = jwt_audience
            if jwt_secret is None:
                jwt_secret = _utilities.get_env('LAGOON_JWT_SECRET')
            __props__.__dict__["jwt_secret"] = None if jwt_secret is None else pulumi.Output.secret(jwt_secret)
            if token is None:
                token = _utilities.get_env('LAGOON_TOKEN')
            __props__.__dict__["token"] = None if token is None else pulumi.Output.secret(token)
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["apiUrl", "jwtSecret", "token"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Provider, __self__).__init__(
            'lagoon',
            resource_name,
            __props__,
            opts)

    @_builtins.property
    @pulumi.getter(name="apiUrl")
    def api_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The Lagoon GraphQL API endpoint URL.
        """
        return pulumi.get(self, "api_url")

    @_builtins.property
    @pulumi.getter(name="jwtAudience")
    def jwt_audience(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The audience claim for generated JWT tokens. Defaults to 'api.dev'.
        """
        return pulumi.get(self, "jwt_audience")

    @_builtins.property
    @pulumi.getter(name="jwtSecret")
    def jwt_secret(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The Lagoon core JWTSECRET. Used to generate admin tokens on-the-fly.
        """
        return pulumi.get(self, "jwt_secret")

    @_builtins.property
    @pulumi.getter
    def token(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A pre-configured JWT authentication token for the Lagoon API.
        """
        return pulumi.get(self, "token")

