package provider

import (
	p "github.com/pulumi/pulumi-go-provider"
	"github.com/pulumi/pulumi-go-provider/infer"
	"github.com/tag1consulting/pulumi-lagoon/provider/pkg/config"
	"github.com/tag1consulting/pulumi-lagoon/provider/pkg/resources"
)

// NewProvider constructs the Lagoon provider with all resources wired.
func NewProvider(version string) (p.Provider, error) {
	return infer.NewProviderBuilder().
		WithDisplayName("Lagoon").
		WithDescription("Manage Lagoon hosting platform resources as infrastructure-as-code.").
		WithPublisher("Tag1 Consulting").
		WithRepository("https://github.com/tag1consulting/pulumi-lagoon-provider").
		WithHomepage("https://github.com/tag1consulting/pulumi-lagoon-provider").
		WithLicense("Apache-2.0").
		WithKeywords("lagoon", "hosting", "kubernetes", "pulumi", "category/infrastructure", "kind/native").
		WithLogoURL("https://raw.githubusercontent.com/tag1consulting/pulumi-lagoon-provider/main/docs/logo.svg").
		WithPluginDownloadURL("github://api.github.com/tag1consulting/pulumi-lagoon-provider").
		WithLanguageMap(map[string]any{
			"go": map[string]any{
				"importBasePath":                "github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon",
				"generateExtraInputTypes":       true,
				"generateResourceContainerTypes": true,
				"respectSchemaVersion":           true,
			},
			"nodejs": map[string]any{
				"packageName":          "@tag1consulting/pulumi-lagoon",
				"respectSchemaVersion": true,
			},
			"python": map[string]any{
				"packageName":          "pulumi_lagoon",
				"pyproject":            map[string]any{"enabled": true},
				"respectSchemaVersion": true,
			},
			"csharp": map[string]any{
				"packageId": "Tag1Consulting.Lagoon",
				"packageReferences": map[string]any{
					"Pulumi": "3.*",
				},
				"rootNamespace":        "Tag1Consulting",
				"respectSchemaVersion": true,
			},
		}).
		WithConfig(infer.Config(&config.LagoonConfig{})).
		WithResources(
			infer.Resource(&resources.Project{}),
			infer.Resource(&resources.Environment{}),
			infer.Resource(&resources.Variable{}),
			infer.Resource(&resources.DeployTarget{}),
			infer.Resource(&resources.DeployTargetConfig{}),
			infer.Resource(&resources.Task{}),
			infer.Resource(&resources.NotificationSlack{}),
			infer.Resource(&resources.NotificationRocketChat{}),
			infer.Resource(&resources.NotificationEmail{}),
			infer.Resource(&resources.NotificationMicrosoftTeams{}),
			infer.Resource(&resources.ProjectNotification{}),
			infer.Resource(&resources.Group{}),
			infer.Resource(&resources.Route{}),
			infer.Resource(&resources.ProjectAutogeneratedRouteConfig{}),
			infer.Resource(&resources.EnvironmentAutogeneratedRouteConfig{}),
			infer.Resource(&resources.User{}),
			infer.Resource(&resources.UserGroupAssignment{}),
			infer.Resource(&resources.UserPlatformRole{}),
		).
		Build()
}
