// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package resources

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/internal"
)

var _ = internal.GetEnvOrDefault

type TaskArgumentInput struct {
	DisplayName string `pulumi:"displayName"`
	Name        string `pulumi:"name"`
	Type        string `pulumi:"type"`
}

// TaskArgumentInputInput is an input type that accepts TaskArgumentInputArgs and TaskArgumentInputOutput values.
// You can construct a concrete instance of `TaskArgumentInputInput` via:
//
//	TaskArgumentInputArgs{...}
type TaskArgumentInputInput interface {
	pulumi.Input

	ToTaskArgumentInputOutput() TaskArgumentInputOutput
	ToTaskArgumentInputOutputWithContext(context.Context) TaskArgumentInputOutput
}

type TaskArgumentInputArgs struct {
	DisplayName pulumi.StringInput `pulumi:"displayName"`
	Name        pulumi.StringInput `pulumi:"name"`
	Type        pulumi.StringInput `pulumi:"type"`
}

func (TaskArgumentInputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*TaskArgumentInput)(nil)).Elem()
}

func (i TaskArgumentInputArgs) ToTaskArgumentInputOutput() TaskArgumentInputOutput {
	return i.ToTaskArgumentInputOutputWithContext(context.Background())
}

func (i TaskArgumentInputArgs) ToTaskArgumentInputOutputWithContext(ctx context.Context) TaskArgumentInputOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TaskArgumentInputOutput)
}

// TaskArgumentInputArrayInput is an input type that accepts TaskArgumentInputArray and TaskArgumentInputArrayOutput values.
// You can construct a concrete instance of `TaskArgumentInputArrayInput` via:
//
//	TaskArgumentInputArray{ TaskArgumentInputArgs{...} }
type TaskArgumentInputArrayInput interface {
	pulumi.Input

	ToTaskArgumentInputArrayOutput() TaskArgumentInputArrayOutput
	ToTaskArgumentInputArrayOutputWithContext(context.Context) TaskArgumentInputArrayOutput
}

type TaskArgumentInputArray []TaskArgumentInputInput

func (TaskArgumentInputArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TaskArgumentInput)(nil)).Elem()
}

func (i TaskArgumentInputArray) ToTaskArgumentInputArrayOutput() TaskArgumentInputArrayOutput {
	return i.ToTaskArgumentInputArrayOutputWithContext(context.Background())
}

func (i TaskArgumentInputArray) ToTaskArgumentInputArrayOutputWithContext(ctx context.Context) TaskArgumentInputArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(TaskArgumentInputArrayOutput)
}

type TaskArgumentInputOutput struct{ *pulumi.OutputState }

func (TaskArgumentInputOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*TaskArgumentInput)(nil)).Elem()
}

func (o TaskArgumentInputOutput) ToTaskArgumentInputOutput() TaskArgumentInputOutput {
	return o
}

func (o TaskArgumentInputOutput) ToTaskArgumentInputOutputWithContext(ctx context.Context) TaskArgumentInputOutput {
	return o
}

func (o TaskArgumentInputOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v TaskArgumentInput) string { return v.DisplayName }).(pulumi.StringOutput)
}

func (o TaskArgumentInputOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v TaskArgumentInput) string { return v.Name }).(pulumi.StringOutput)
}

func (o TaskArgumentInputOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v TaskArgumentInput) string { return v.Type }).(pulumi.StringOutput)
}

type TaskArgumentInputArrayOutput struct{ *pulumi.OutputState }

func (TaskArgumentInputArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]TaskArgumentInput)(nil)).Elem()
}

func (o TaskArgumentInputArrayOutput) ToTaskArgumentInputArrayOutput() TaskArgumentInputArrayOutput {
	return o
}

func (o TaskArgumentInputArrayOutput) ToTaskArgumentInputArrayOutputWithContext(ctx context.Context) TaskArgumentInputArrayOutput {
	return o
}

func (o TaskArgumentInputArrayOutput) Index(i pulumi.IntInput) TaskArgumentInputOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) TaskArgumentInput {
		return vs[0].([]TaskArgumentInput)[vs[1].(int)]
	}).(TaskArgumentInputOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*TaskArgumentInputInput)(nil)).Elem(), TaskArgumentInputArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*TaskArgumentInputArrayInput)(nil)).Elem(), TaskArgumentInputArray{})
	pulumi.RegisterOutputType(TaskArgumentInputOutput{})
	pulumi.RegisterOutputType(TaskArgumentInputArrayOutput{})
}
