// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/internal"
)

var _ = internal.GetEnvOrDefault

// The Lagoon GraphQL API endpoint URL.
func GetApiUrl(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "lagoon:apiUrl")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("https://api.lagoon.sh/graphql", nil, "LAGOON_API_URL"); d != nil {
		value = d.(string)
	}
	return value
}

// Disable SSL certificate verification when connecting to the Lagoon API.
func GetInsecure(ctx *pulumi.Context) bool {
	v, err := config.TryBool(ctx, "lagoon:insecure")
	if err == nil {
		return v
	}
	var value bool
	if d := internal.GetEnvOrDefault(false, internal.ParseEnvBool, "LAGOON_INSECURE"); d != nil {
		value = d.(bool)
	}
	return value
}

// The audience claim for generated JWT tokens. Defaults to 'api.dev'.
func GetJwtAudience(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "lagoon:jwtAudience")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault("api.dev", nil, "LAGOON_JWT_AUDIENCE"); d != nil {
		value = d.(string)
	}
	return value
}

// The Lagoon core JWTSECRET. Used to generate admin tokens on-the-fly.
func GetJwtSecret(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "lagoon:jwtSecret")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "LAGOON_JWT_SECRET"); d != nil {
		value = d.(string)
	}
	return value
}

// A pre-configured JWT authentication token for the Lagoon API.
func GetToken(ctx *pulumi.Context) string {
	v, err := config.Try(ctx, "lagoon:token")
	if err == nil {
		return v
	}
	var value string
	if d := internal.GetEnvOrDefault(nil, nil, "LAGOON_TOKEN"); d != nil {
		value = d.(string)
	}
	return value
}
