// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package lagoon

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/internal"
)

// Manages a Lagoon Slack notification configuration.
type NotificationSlack struct {
	pulumi.CustomResourceState

	// The Slack channel (e.g., '#deployments').
	Channel  pulumi.StringOutput `pulumi:"channel"`
	LagoonId pulumi.IntOutput    `pulumi:"lagoonId"`
	// The notification name.
	Name pulumi.StringOutput `pulumi:"name"`
	// The Slack webhook URL (stored as secret).
	Webhook pulumi.StringOutput `pulumi:"webhook"`
}

// NewNotificationSlack registers a new resource with the given unique name, arguments, and options.
func NewNotificationSlack(ctx *pulumi.Context,
	name string, args *NotificationSlackArgs, opts ...pulumi.ResourceOption) (*NotificationSlack, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Channel == nil {
		return nil, errors.New("invalid value for required argument 'Channel'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Webhook == nil {
		return nil, errors.New("invalid value for required argument 'Webhook'")
	}
	if args.Webhook != nil {
		args.Webhook = pulumi.ToSecret(args.Webhook).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"webhook",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NotificationSlack
	err := ctx.RegisterResource("lagoon:lagoon:NotificationSlack", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNotificationSlack gets an existing NotificationSlack resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNotificationSlack(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NotificationSlackState, opts ...pulumi.ResourceOption) (*NotificationSlack, error) {
	var resource NotificationSlack
	err := ctx.ReadResource("lagoon:lagoon:NotificationSlack", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NotificationSlack resources.
type notificationSlackState struct {
}

type NotificationSlackState struct {
}

func (NotificationSlackState) ElementType() reflect.Type {
	return reflect.TypeOf((*notificationSlackState)(nil)).Elem()
}

type notificationSlackArgs struct {
	// The Slack channel (e.g., '#deployments').
	Channel string `pulumi:"channel"`
	// The notification name.
	Name string `pulumi:"name"`
	// The Slack webhook URL (stored as secret).
	Webhook string `pulumi:"webhook"`
}

// The set of arguments for constructing a NotificationSlack resource.
type NotificationSlackArgs struct {
	// The Slack channel (e.g., '#deployments').
	Channel pulumi.StringInput
	// The notification name.
	Name pulumi.StringInput
	// The Slack webhook URL (stored as secret).
	Webhook pulumi.StringInput
}

func (NotificationSlackArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*notificationSlackArgs)(nil)).Elem()
}

type NotificationSlackInput interface {
	pulumi.Input

	ToNotificationSlackOutput() NotificationSlackOutput
	ToNotificationSlackOutputWithContext(ctx context.Context) NotificationSlackOutput
}

func (*NotificationSlack) ElementType() reflect.Type {
	return reflect.TypeOf((**NotificationSlack)(nil)).Elem()
}

func (i *NotificationSlack) ToNotificationSlackOutput() NotificationSlackOutput {
	return i.ToNotificationSlackOutputWithContext(context.Background())
}

func (i *NotificationSlack) ToNotificationSlackOutputWithContext(ctx context.Context) NotificationSlackOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NotificationSlackOutput)
}

// NotificationSlackArrayInput is an input type that accepts NotificationSlackArray and NotificationSlackArrayOutput values.
// You can construct a concrete instance of `NotificationSlackArrayInput` via:
//
//	NotificationSlackArray{ NotificationSlackArgs{...} }
type NotificationSlackArrayInput interface {
	pulumi.Input

	ToNotificationSlackArrayOutput() NotificationSlackArrayOutput
	ToNotificationSlackArrayOutputWithContext(context.Context) NotificationSlackArrayOutput
}

type NotificationSlackArray []NotificationSlackInput

func (NotificationSlackArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NotificationSlack)(nil)).Elem()
}

func (i NotificationSlackArray) ToNotificationSlackArrayOutput() NotificationSlackArrayOutput {
	return i.ToNotificationSlackArrayOutputWithContext(context.Background())
}

func (i NotificationSlackArray) ToNotificationSlackArrayOutputWithContext(ctx context.Context) NotificationSlackArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NotificationSlackArrayOutput)
}

// NotificationSlackMapInput is an input type that accepts NotificationSlackMap and NotificationSlackMapOutput values.
// You can construct a concrete instance of `NotificationSlackMapInput` via:
//
//	NotificationSlackMap{ "key": NotificationSlackArgs{...} }
type NotificationSlackMapInput interface {
	pulumi.Input

	ToNotificationSlackMapOutput() NotificationSlackMapOutput
	ToNotificationSlackMapOutputWithContext(context.Context) NotificationSlackMapOutput
}

type NotificationSlackMap map[string]NotificationSlackInput

func (NotificationSlackMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NotificationSlack)(nil)).Elem()
}

func (i NotificationSlackMap) ToNotificationSlackMapOutput() NotificationSlackMapOutput {
	return i.ToNotificationSlackMapOutputWithContext(context.Background())
}

func (i NotificationSlackMap) ToNotificationSlackMapOutputWithContext(ctx context.Context) NotificationSlackMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NotificationSlackMapOutput)
}

type NotificationSlackOutput struct{ *pulumi.OutputState }

func (NotificationSlackOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NotificationSlack)(nil)).Elem()
}

func (o NotificationSlackOutput) ToNotificationSlackOutput() NotificationSlackOutput {
	return o
}

func (o NotificationSlackOutput) ToNotificationSlackOutputWithContext(ctx context.Context) NotificationSlackOutput {
	return o
}

// The Slack channel (e.g., '#deployments').
func (o NotificationSlackOutput) Channel() pulumi.StringOutput {
	return o.ApplyT(func(v *NotificationSlack) pulumi.StringOutput { return v.Channel }).(pulumi.StringOutput)
}

func (o NotificationSlackOutput) LagoonId() pulumi.IntOutput {
	return o.ApplyT(func(v *NotificationSlack) pulumi.IntOutput { return v.LagoonId }).(pulumi.IntOutput)
}

// The notification name.
func (o NotificationSlackOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NotificationSlack) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The Slack webhook URL (stored as secret).
func (o NotificationSlackOutput) Webhook() pulumi.StringOutput {
	return o.ApplyT(func(v *NotificationSlack) pulumi.StringOutput { return v.Webhook }).(pulumi.StringOutput)
}

type NotificationSlackArrayOutput struct{ *pulumi.OutputState }

func (NotificationSlackArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NotificationSlack)(nil)).Elem()
}

func (o NotificationSlackArrayOutput) ToNotificationSlackArrayOutput() NotificationSlackArrayOutput {
	return o
}

func (o NotificationSlackArrayOutput) ToNotificationSlackArrayOutputWithContext(ctx context.Context) NotificationSlackArrayOutput {
	return o
}

func (o NotificationSlackArrayOutput) Index(i pulumi.IntInput) NotificationSlackOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *NotificationSlack {
		return vs[0].([]*NotificationSlack)[vs[1].(int)]
	}).(NotificationSlackOutput)
}

type NotificationSlackMapOutput struct{ *pulumi.OutputState }

func (NotificationSlackMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NotificationSlack)(nil)).Elem()
}

func (o NotificationSlackMapOutput) ToNotificationSlackMapOutput() NotificationSlackMapOutput {
	return o
}

func (o NotificationSlackMapOutput) ToNotificationSlackMapOutputWithContext(ctx context.Context) NotificationSlackMapOutput {
	return o
}

func (o NotificationSlackMapOutput) MapIndex(k pulumi.StringInput) NotificationSlackOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *NotificationSlack {
		return vs[0].(map[string]*NotificationSlack)[vs[1].(string)]
	}).(NotificationSlackOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NotificationSlackInput)(nil)).Elem(), &NotificationSlack{})
	pulumi.RegisterInputType(reflect.TypeOf((*NotificationSlackArrayInput)(nil)).Elem(), NotificationSlackArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NotificationSlackMapInput)(nil)).Elem(), NotificationSlackMap{})
	pulumi.RegisterOutputType(NotificationSlackOutput{})
	pulumi.RegisterOutputType(NotificationSlackArrayOutput{})
	pulumi.RegisterOutputType(NotificationSlackMapOutput{})
}
