// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package lagoon

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/internal"
)

// Manages a Lagoon Email notification configuration.
type NotificationEmail struct {
	pulumi.CustomResourceState

	// The email address to send notifications to.
	EmailAddress pulumi.StringOutput `pulumi:"emailAddress"`
	LagoonId     pulumi.IntOutput    `pulumi:"lagoonId"`
	// The notification name.
	Name pulumi.StringOutput `pulumi:"name"`
}

// NewNotificationEmail registers a new resource with the given unique name, arguments, and options.
func NewNotificationEmail(ctx *pulumi.Context,
	name string, args *NotificationEmailArgs, opts ...pulumi.ResourceOption) (*NotificationEmail, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EmailAddress == nil {
		return nil, errors.New("invalid value for required argument 'EmailAddress'")
	}
	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NotificationEmail
	err := ctx.RegisterResource("lagoon:lagoon:NotificationEmail", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNotificationEmail gets an existing NotificationEmail resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNotificationEmail(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NotificationEmailState, opts ...pulumi.ResourceOption) (*NotificationEmail, error) {
	var resource NotificationEmail
	err := ctx.ReadResource("lagoon:lagoon:NotificationEmail", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NotificationEmail resources.
type notificationEmailState struct {
}

type NotificationEmailState struct {
}

func (NotificationEmailState) ElementType() reflect.Type {
	return reflect.TypeOf((*notificationEmailState)(nil)).Elem()
}

type notificationEmailArgs struct {
	// The email address to send notifications to.
	EmailAddress string `pulumi:"emailAddress"`
	// The notification name.
	Name string `pulumi:"name"`
}

// The set of arguments for constructing a NotificationEmail resource.
type NotificationEmailArgs struct {
	// The email address to send notifications to.
	EmailAddress pulumi.StringInput
	// The notification name.
	Name pulumi.StringInput
}

func (NotificationEmailArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*notificationEmailArgs)(nil)).Elem()
}

type NotificationEmailInput interface {
	pulumi.Input

	ToNotificationEmailOutput() NotificationEmailOutput
	ToNotificationEmailOutputWithContext(ctx context.Context) NotificationEmailOutput
}

func (*NotificationEmail) ElementType() reflect.Type {
	return reflect.TypeOf((**NotificationEmail)(nil)).Elem()
}

func (i *NotificationEmail) ToNotificationEmailOutput() NotificationEmailOutput {
	return i.ToNotificationEmailOutputWithContext(context.Background())
}

func (i *NotificationEmail) ToNotificationEmailOutputWithContext(ctx context.Context) NotificationEmailOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NotificationEmailOutput)
}

// NotificationEmailArrayInput is an input type that accepts NotificationEmailArray and NotificationEmailArrayOutput values.
// You can construct a concrete instance of `NotificationEmailArrayInput` via:
//
//	NotificationEmailArray{ NotificationEmailArgs{...} }
type NotificationEmailArrayInput interface {
	pulumi.Input

	ToNotificationEmailArrayOutput() NotificationEmailArrayOutput
	ToNotificationEmailArrayOutputWithContext(context.Context) NotificationEmailArrayOutput
}

type NotificationEmailArray []NotificationEmailInput

func (NotificationEmailArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NotificationEmail)(nil)).Elem()
}

func (i NotificationEmailArray) ToNotificationEmailArrayOutput() NotificationEmailArrayOutput {
	return i.ToNotificationEmailArrayOutputWithContext(context.Background())
}

func (i NotificationEmailArray) ToNotificationEmailArrayOutputWithContext(ctx context.Context) NotificationEmailArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NotificationEmailArrayOutput)
}

// NotificationEmailMapInput is an input type that accepts NotificationEmailMap and NotificationEmailMapOutput values.
// You can construct a concrete instance of `NotificationEmailMapInput` via:
//
//	NotificationEmailMap{ "key": NotificationEmailArgs{...} }
type NotificationEmailMapInput interface {
	pulumi.Input

	ToNotificationEmailMapOutput() NotificationEmailMapOutput
	ToNotificationEmailMapOutputWithContext(context.Context) NotificationEmailMapOutput
}

type NotificationEmailMap map[string]NotificationEmailInput

func (NotificationEmailMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NotificationEmail)(nil)).Elem()
}

func (i NotificationEmailMap) ToNotificationEmailMapOutput() NotificationEmailMapOutput {
	return i.ToNotificationEmailMapOutputWithContext(context.Background())
}

func (i NotificationEmailMap) ToNotificationEmailMapOutputWithContext(ctx context.Context) NotificationEmailMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NotificationEmailMapOutput)
}

type NotificationEmailOutput struct{ *pulumi.OutputState }

func (NotificationEmailOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NotificationEmail)(nil)).Elem()
}

func (o NotificationEmailOutput) ToNotificationEmailOutput() NotificationEmailOutput {
	return o
}

func (o NotificationEmailOutput) ToNotificationEmailOutputWithContext(ctx context.Context) NotificationEmailOutput {
	return o
}

// The email address to send notifications to.
func (o NotificationEmailOutput) EmailAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *NotificationEmail) pulumi.StringOutput { return v.EmailAddress }).(pulumi.StringOutput)
}

func (o NotificationEmailOutput) LagoonId() pulumi.IntOutput {
	return o.ApplyT(func(v *NotificationEmail) pulumi.IntOutput { return v.LagoonId }).(pulumi.IntOutput)
}

// The notification name.
func (o NotificationEmailOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NotificationEmail) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

type NotificationEmailArrayOutput struct{ *pulumi.OutputState }

func (NotificationEmailArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NotificationEmail)(nil)).Elem()
}

func (o NotificationEmailArrayOutput) ToNotificationEmailArrayOutput() NotificationEmailArrayOutput {
	return o
}

func (o NotificationEmailArrayOutput) ToNotificationEmailArrayOutputWithContext(ctx context.Context) NotificationEmailArrayOutput {
	return o
}

func (o NotificationEmailArrayOutput) Index(i pulumi.IntInput) NotificationEmailOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *NotificationEmail {
		return vs[0].([]*NotificationEmail)[vs[1].(int)]
	}).(NotificationEmailOutput)
}

type NotificationEmailMapOutput struct{ *pulumi.OutputState }

func (NotificationEmailMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NotificationEmail)(nil)).Elem()
}

func (o NotificationEmailMapOutput) ToNotificationEmailMapOutput() NotificationEmailMapOutput {
	return o
}

func (o NotificationEmailMapOutput) ToNotificationEmailMapOutputWithContext(ctx context.Context) NotificationEmailMapOutput {
	return o
}

func (o NotificationEmailMapOutput) MapIndex(k pulumi.StringInput) NotificationEmailOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *NotificationEmail {
		return vs[0].(map[string]*NotificationEmail)[vs[1].(string)]
	}).(NotificationEmailOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NotificationEmailInput)(nil)).Elem(), &NotificationEmail{})
	pulumi.RegisterInputType(reflect.TypeOf((*NotificationEmailArrayInput)(nil)).Elem(), NotificationEmailArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NotificationEmailMapInput)(nil)).Elem(), NotificationEmailMap{})
	pulumi.RegisterOutputType(NotificationEmailOutput{})
	pulumi.RegisterOutputType(NotificationEmailArrayOutput{})
	pulumi.RegisterOutputType(NotificationEmailMapOutput{})
}
