// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package lagoon

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/tag1consulting/pulumi-lagoon-provider/sdk/go/lagoon/internal"
)

// Manages a Lagoon Microsoft Teams notification configuration.
type NotificationMicrosoftTeams struct {
	pulumi.CustomResourceState

	LagoonId pulumi.IntOutput `pulumi:"lagoonId"`
	// The notification name.
	Name pulumi.StringOutput `pulumi:"name"`
	// The Microsoft Teams webhook URL (stored as secret).
	Webhook pulumi.StringOutput `pulumi:"webhook"`
}

// NewNotificationMicrosoftTeams registers a new resource with the given unique name, arguments, and options.
func NewNotificationMicrosoftTeams(ctx *pulumi.Context,
	name string, args *NotificationMicrosoftTeamsArgs, opts ...pulumi.ResourceOption) (*NotificationMicrosoftTeams, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	if args.Webhook == nil {
		return nil, errors.New("invalid value for required argument 'Webhook'")
	}
	if args.Webhook != nil {
		args.Webhook = pulumi.ToSecret(args.Webhook).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"webhook",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource NotificationMicrosoftTeams
	err := ctx.RegisterResource("lagoon:lagoon:NotificationMicrosoftTeams", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetNotificationMicrosoftTeams gets an existing NotificationMicrosoftTeams resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetNotificationMicrosoftTeams(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *NotificationMicrosoftTeamsState, opts ...pulumi.ResourceOption) (*NotificationMicrosoftTeams, error) {
	var resource NotificationMicrosoftTeams
	err := ctx.ReadResource("lagoon:lagoon:NotificationMicrosoftTeams", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering NotificationMicrosoftTeams resources.
type notificationMicrosoftTeamsState struct {
}

type NotificationMicrosoftTeamsState struct {
}

func (NotificationMicrosoftTeamsState) ElementType() reflect.Type {
	return reflect.TypeOf((*notificationMicrosoftTeamsState)(nil)).Elem()
}

type notificationMicrosoftTeamsArgs struct {
	// The notification name.
	Name string `pulumi:"name"`
	// The Microsoft Teams webhook URL (stored as secret).
	Webhook string `pulumi:"webhook"`
}

// The set of arguments for constructing a NotificationMicrosoftTeams resource.
type NotificationMicrosoftTeamsArgs struct {
	// The notification name.
	Name pulumi.StringInput
	// The Microsoft Teams webhook URL (stored as secret).
	Webhook pulumi.StringInput
}

func (NotificationMicrosoftTeamsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*notificationMicrosoftTeamsArgs)(nil)).Elem()
}

type NotificationMicrosoftTeamsInput interface {
	pulumi.Input

	ToNotificationMicrosoftTeamsOutput() NotificationMicrosoftTeamsOutput
	ToNotificationMicrosoftTeamsOutputWithContext(ctx context.Context) NotificationMicrosoftTeamsOutput
}

func (*NotificationMicrosoftTeams) ElementType() reflect.Type {
	return reflect.TypeOf((**NotificationMicrosoftTeams)(nil)).Elem()
}

func (i *NotificationMicrosoftTeams) ToNotificationMicrosoftTeamsOutput() NotificationMicrosoftTeamsOutput {
	return i.ToNotificationMicrosoftTeamsOutputWithContext(context.Background())
}

func (i *NotificationMicrosoftTeams) ToNotificationMicrosoftTeamsOutputWithContext(ctx context.Context) NotificationMicrosoftTeamsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NotificationMicrosoftTeamsOutput)
}

// NotificationMicrosoftTeamsArrayInput is an input type that accepts NotificationMicrosoftTeamsArray and NotificationMicrosoftTeamsArrayOutput values.
// You can construct a concrete instance of `NotificationMicrosoftTeamsArrayInput` via:
//
//	NotificationMicrosoftTeamsArray{ NotificationMicrosoftTeamsArgs{...} }
type NotificationMicrosoftTeamsArrayInput interface {
	pulumi.Input

	ToNotificationMicrosoftTeamsArrayOutput() NotificationMicrosoftTeamsArrayOutput
	ToNotificationMicrosoftTeamsArrayOutputWithContext(context.Context) NotificationMicrosoftTeamsArrayOutput
}

type NotificationMicrosoftTeamsArray []NotificationMicrosoftTeamsInput

func (NotificationMicrosoftTeamsArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NotificationMicrosoftTeams)(nil)).Elem()
}

func (i NotificationMicrosoftTeamsArray) ToNotificationMicrosoftTeamsArrayOutput() NotificationMicrosoftTeamsArrayOutput {
	return i.ToNotificationMicrosoftTeamsArrayOutputWithContext(context.Background())
}

func (i NotificationMicrosoftTeamsArray) ToNotificationMicrosoftTeamsArrayOutputWithContext(ctx context.Context) NotificationMicrosoftTeamsArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NotificationMicrosoftTeamsArrayOutput)
}

// NotificationMicrosoftTeamsMapInput is an input type that accepts NotificationMicrosoftTeamsMap and NotificationMicrosoftTeamsMapOutput values.
// You can construct a concrete instance of `NotificationMicrosoftTeamsMapInput` via:
//
//	NotificationMicrosoftTeamsMap{ "key": NotificationMicrosoftTeamsArgs{...} }
type NotificationMicrosoftTeamsMapInput interface {
	pulumi.Input

	ToNotificationMicrosoftTeamsMapOutput() NotificationMicrosoftTeamsMapOutput
	ToNotificationMicrosoftTeamsMapOutputWithContext(context.Context) NotificationMicrosoftTeamsMapOutput
}

type NotificationMicrosoftTeamsMap map[string]NotificationMicrosoftTeamsInput

func (NotificationMicrosoftTeamsMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NotificationMicrosoftTeams)(nil)).Elem()
}

func (i NotificationMicrosoftTeamsMap) ToNotificationMicrosoftTeamsMapOutput() NotificationMicrosoftTeamsMapOutput {
	return i.ToNotificationMicrosoftTeamsMapOutputWithContext(context.Background())
}

func (i NotificationMicrosoftTeamsMap) ToNotificationMicrosoftTeamsMapOutputWithContext(ctx context.Context) NotificationMicrosoftTeamsMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NotificationMicrosoftTeamsMapOutput)
}

type NotificationMicrosoftTeamsOutput struct{ *pulumi.OutputState }

func (NotificationMicrosoftTeamsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**NotificationMicrosoftTeams)(nil)).Elem()
}

func (o NotificationMicrosoftTeamsOutput) ToNotificationMicrosoftTeamsOutput() NotificationMicrosoftTeamsOutput {
	return o
}

func (o NotificationMicrosoftTeamsOutput) ToNotificationMicrosoftTeamsOutputWithContext(ctx context.Context) NotificationMicrosoftTeamsOutput {
	return o
}

func (o NotificationMicrosoftTeamsOutput) LagoonId() pulumi.IntOutput {
	return o.ApplyT(func(v *NotificationMicrosoftTeams) pulumi.IntOutput { return v.LagoonId }).(pulumi.IntOutput)
}

// The notification name.
func (o NotificationMicrosoftTeamsOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *NotificationMicrosoftTeams) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The Microsoft Teams webhook URL (stored as secret).
func (o NotificationMicrosoftTeamsOutput) Webhook() pulumi.StringOutput {
	return o.ApplyT(func(v *NotificationMicrosoftTeams) pulumi.StringOutput { return v.Webhook }).(pulumi.StringOutput)
}

type NotificationMicrosoftTeamsArrayOutput struct{ *pulumi.OutputState }

func (NotificationMicrosoftTeamsArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*NotificationMicrosoftTeams)(nil)).Elem()
}

func (o NotificationMicrosoftTeamsArrayOutput) ToNotificationMicrosoftTeamsArrayOutput() NotificationMicrosoftTeamsArrayOutput {
	return o
}

func (o NotificationMicrosoftTeamsArrayOutput) ToNotificationMicrosoftTeamsArrayOutputWithContext(ctx context.Context) NotificationMicrosoftTeamsArrayOutput {
	return o
}

func (o NotificationMicrosoftTeamsArrayOutput) Index(i pulumi.IntInput) NotificationMicrosoftTeamsOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *NotificationMicrosoftTeams {
		return vs[0].([]*NotificationMicrosoftTeams)[vs[1].(int)]
	}).(NotificationMicrosoftTeamsOutput)
}

type NotificationMicrosoftTeamsMapOutput struct{ *pulumi.OutputState }

func (NotificationMicrosoftTeamsMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*NotificationMicrosoftTeams)(nil)).Elem()
}

func (o NotificationMicrosoftTeamsMapOutput) ToNotificationMicrosoftTeamsMapOutput() NotificationMicrosoftTeamsMapOutput {
	return o
}

func (o NotificationMicrosoftTeamsMapOutput) ToNotificationMicrosoftTeamsMapOutputWithContext(ctx context.Context) NotificationMicrosoftTeamsMapOutput {
	return o
}

func (o NotificationMicrosoftTeamsMapOutput) MapIndex(k pulumi.StringInput) NotificationMicrosoftTeamsOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *NotificationMicrosoftTeams {
		return vs[0].(map[string]*NotificationMicrosoftTeams)[vs[1].(string)]
	}).(NotificationMicrosoftTeamsOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*NotificationMicrosoftTeamsInput)(nil)).Elem(), &NotificationMicrosoftTeams{})
	pulumi.RegisterInputType(reflect.TypeOf((*NotificationMicrosoftTeamsArrayInput)(nil)).Elem(), NotificationMicrosoftTeamsArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*NotificationMicrosoftTeamsMapInput)(nil)).Elem(), NotificationMicrosoftTeamsMap{})
	pulumi.RegisterOutputType(NotificationMicrosoftTeamsOutput{})
	pulumi.RegisterOutputType(NotificationMicrosoftTeamsArrayOutput{})
	pulumi.RegisterOutputType(NotificationMicrosoftTeamsMapOutput{})
}
