#!/usr/bin/env bash
#
# post-review.sh — Post AI review results to a GitHub PR.
#
# Posts Block A (summary) as a PR comment and Block B (findings) as a pull request review
# with inline comments.
#
# Usage:
#   ./post-review.sh <pr_number> <summary_file> <findings_file> <findings_json_file> <diff_file> <head_sha>
#
# Environment:
#   GH_TOKEN     — GitHub token for API access
#   GITHUB_REPOSITORY — owner/repo (set automatically in GitHub Actions)

set -euo pipefail

PR_NUMBER="${1:?Usage: post-review.sh <pr_number> <summary_file> <findings_file> <findings_json_file> <diff_file> <head_sha>}"
SUMMARY_FILE="${2:?Missing summary file}"
FINDINGS_FILE="${3:?Missing findings file}"
FINDINGS_JSON_FILE="${4:?Missing findings JSON file}"
DIFF_FILE="${5:?Missing diff file}"
HEAD_SHA="${6:?Missing head SHA}"

: "${GH_TOKEN:?GH_TOKEN is required}"
: "${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"

OWNER="${GITHUB_REPOSITORY%%/*}"
REPO="${GITHUB_REPOSITORY##*/}"
MARKER="<!-- ai-pr-review-summary -->"

# Temp files — cleaned up on exit
TMPFILES=()
cleanup() {
  rm -f "${TMPFILES[@]}" 2>/dev/null || true
}
trap cleanup EXIT

mktemp_tracked() {
  local f
  f=$(mktemp "$@")
  TMPFILES+=("$f")
  echo "$f"
}

# ---------------------------------------------------------------------------
# Post Block A: Summary comment (idempotent via marker)
# ---------------------------------------------------------------------------
post_summary() {
  local summary
  summary=$(cat "$SUMMARY_FILE")

  if [[ -z "$summary" || "$summary" == "NONE" ]]; then
    echo "No summary to post." >&2
    return 0
  fi

  local body="${MARKER}
${summary}

---
*AI Review Summary — generated by [ai-pr-review](https://github.com/tag1consulting/ai-pr-review)*"

  # Find existing summary comment by marker
  local existing_comment_id
  existing_comment_id=$(gh api "repos/${OWNER}/${REPO}/issues/${PR_NUMBER}/comments" \
    --paginate --jq ".[] | select(.body | contains(\"${MARKER}\")) | .id" 2>/dev/null | head -1) || true

  if [[ -n "$existing_comment_id" ]]; then
    echo "Updating existing summary comment #${existing_comment_id}..." >&2
    gh api "repos/${OWNER}/${REPO}/issues/comments/${existing_comment_id}" \
      --method PATCH \
      --field body="$body" > /dev/null
  else
    echo "Posting new summary comment..." >&2
    gh api "repos/${OWNER}/${REPO}/issues/${PR_NUMBER}/comments" \
      --method POST \
      --field body="$body" > /dev/null
  fi

  echo "Summary comment posted to PR #${PR_NUMBER}." >&2
}

# ---------------------------------------------------------------------------
# Parse diff hunks to determine valid inline comment lines
# ---------------------------------------------------------------------------
# Builds a lookup of file:line pairs that are valid targets for inline comments.
# Only lines that appear in the "+" side of diff hunks are valid.
parse_valid_lines() {
  local diff_file="$1"
  local current_file=""
  local new_line=0

  while IFS= read -r line; do
    if [[ "$line" =~ ^diff\ --git\ a/(.+)\ b/(.+) ]]; then
      current_file="${BASH_REMATCH[2]}"
      new_line=0
    elif [[ "$new_line" -eq 0 ]] && [[ "$line" =~ ^\+\+\+\  || "$line" =~ ^---\  ]]; then
      # Skip diff file headers — only match before the first hunk (@@ line)
      continue
    elif [[ "$line" =~ ^@@\ -[0-9]+(,[0-9]+)?\ \+([0-9]+)(,[0-9]+)?\ @@ ]]; then
      new_line="${BASH_REMATCH[2]}"
    elif [[ -n "$current_file" && "$new_line" -gt 0 ]]; then
      if [[ "$line" =~ ^\+ ]]; then
        echo "${current_file}:${new_line}"
        new_line=$((new_line + 1))
      elif [[ "$line" =~ ^- ]]; then
        : # deleted line — don't increment new_line
      else
        new_line=$((new_line + 1))
      fi
    fi
  done < "$diff_file"
}

# ---------------------------------------------------------------------------
# Post Block B: Findings as a pull request review with inline comments
# ---------------------------------------------------------------------------
post_findings() {
  local findings
  findings=$(cat "$FINDINGS_FILE")

  if [[ -z "$findings" || "$findings" == "NONE" ]]; then
    echo "No findings to post." >&2
    return 0
  fi

  # Parse the JSON findings for inline comments
  local findings_json="[]"
  if [[ -f "$FINDINGS_JSON_FILE" ]]; then
    findings_json=$(cat "$FINDINGS_JSON_FILE")
    # Validate it's valid JSON array
    if ! echo "$findings_json" | jq -e 'type == "array"' > /dev/null 2>&1; then
      echo "WARNING: Invalid findings JSON, posting as body-only review." >&2
      findings_json="[]"
    fi
  fi

  # Build valid lines lookup from diff
  local valid_lines_file
  valid_lines_file=$(mktemp_tracked /tmp/valid-lines-XXXXXXXX.txt)
  parse_valid_lines "$DIFF_FILE" > "$valid_lines_file"

  # Partition findings into inline (valid diff line) and body (everything else)
  local inline_comments="[]"
  local body_findings=""
  local inline_count=0
  local max_inline=25

  local total
  total=$(echo "$findings_json" | jq 'length')

  for i in $(seq 0 $((total - 1))); do
    local file line severity finding remediation
    file=$(echo "$findings_json" | jq -r ".[$i].file // empty")
    line=$(echo "$findings_json" | jq -r ".[$i].line // empty")
    severity=$(echo "$findings_json" | jq -r ".[$i].severity // \"Medium\"")
    finding=$(echo "$findings_json" | jq -r ".[$i].finding // empty")
    remediation=$(echo "$findings_json" | jq -r ".[$i].remediation // empty")

    if [[ -z "$file" || -z "$line" || -z "$finding" ]]; then
      continue
    fi

    # Validate line is a positive integer (LLM may return non-numeric values)
    if ! [[ "$line" =~ ^[0-9]+$ ]]; then
      echo "WARNING: Skipping finding with non-numeric line: ${file}:${line}" >&2
      body_findings="${body_findings}
- **[${severity}]** ${finding} — \`${file}:${line}\`"
      continue
    fi

    # Check if this line is a valid inline comment target (whole-line match)
    if grep -qxF "${file}:${line}" "$valid_lines_file" && [[ "$inline_count" -lt "$max_inline" ]]; then
      local comment_body="**[${severity}]** ${finding}"
      if [[ -n "$remediation" ]]; then
        comment_body="${comment_body}

**Remediation:** ${remediation}"
      fi

      inline_comments=$(echo "$inline_comments" | jq \
        --arg path "$file" \
        --argjson line "$line" \
        --arg body "$comment_body" \
        '. + [{"path": $path, "line": $line, "body": $body}]')
      inline_count=$((inline_count + 1))
    else
      body_findings="${body_findings}
- **[${severity}]** ${finding} — \`${file}:${line}\`"
    fi
  done

  # Determine overall risk from highest severity found
  local overall_risk="Low"
  if echo "$findings_json" | jq -e '.[] | select(.severity == "Critical")' > /dev/null 2>&1; then
    overall_risk="Critical"
  elif echo "$findings_json" | jq -e '.[] | select(.severity == "High")' > /dev/null 2>&1; then
    overall_risk="High"
  elif echo "$findings_json" | jq -e '.[] | select(.severity == "Medium")' > /dev/null 2>&1; then
    overall_risk="Medium"
  fi

  # Build review body
  local review_body="## AI Review Findings

**Overall Risk:** ${overall_risk}
**Agents:** pr-summarizer, code-reviewer"

  if [[ -n "$body_findings" ]]; then
    review_body="${review_body}

### Findings not attached to specific lines
${body_findings}"
  elif [[ "$inline_count" -gt 0 ]]; then
    review_body="${review_body}

All findings are attached as inline comments."
  fi

  review_body="${review_body}

---
*AI Review — generated by [ai-pr-review](https://github.com/tag1consulting/ai-pr-review)*"

  # Build the review request JSON with commit_id to anchor inline comments
  local review_json
  review_json=$(jq -n \
    --arg body "$review_body" \
    --arg event "COMMENT" \
    --arg commit_id "$HEAD_SHA" \
    --argjson comments "$inline_comments" \
    '{body: $body, event: $event, commit_id: $commit_id, comments: $comments}')

  echo "Posting review with ${inline_count} inline comments..." >&2

  local review_result
  review_result=$(echo "$review_json" | gh api "repos/${OWNER}/${REPO}/pulls/${PR_NUMBER}/reviews" \
    --method POST \
    --input - 2>&1) || {
    echo "ERROR: Failed to post pull request review: ${review_result}" >&2
    # Fallback: post as a regular comment
    echo "Falling back to posting findings as a PR comment..." >&2
    gh api "repos/${OWNER}/${REPO}/issues/${PR_NUMBER}/comments" \
      --method POST \
      --field body="${review_body}" > /dev/null || true
    return 1
  }

  echo "Review posted to PR #${PR_NUMBER}: ${inline_count} inline, overflow in body." >&2
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
post_summary
post_findings
