#!/usr/bin/env bash
#
# post-review.sh — Post AI review results to a GitHub PR.
#
# Posts Block A (summary) as a PR comment and Block B (findings) as a pull request review
# with inline comments.
#
# Usage:
#   ./post-review.sh <pr_number> <summary_file> <findings_file> <findings_json_file> <diff_file> <head_sha>
#
# Environment:
#   GH_TOKEN     — GitHub token for API access
#   GITHUB_REPOSITORY — owner/repo (set automatically in GitHub Actions)

set -euo pipefail

PR_NUMBER="${1:?Usage: post-review.sh <pr_number> <summary_file> <findings_file> <findings_json_file> <diff_file> <head_sha>}"
SUMMARY_FILE="${2:?Missing summary file}"
FINDINGS_FILE="${3:?Missing findings file}"
FINDINGS_JSON_FILE="${4:?Missing findings JSON file}"
DIFF_FILE="${5:?Missing diff file}"
HEAD_SHA="${6:?Missing head SHA}"

: "${GH_TOKEN:?GH_TOKEN is required}"
: "${GITHUB_REPOSITORY:?GITHUB_REPOSITORY is required}"

OWNER="${GITHUB_REPOSITORY%%/*}"
REPO="${GITHUB_REPOSITORY##*/}"
MARKER_PREFIX="<!-- ai-pr-review-summary"
# MARKER_PREFIX is embedded in comment bodies to identify our summary comments.
# The full marker includes an optional sha= field: <!-- ai-pr-review-summary sha=<sha> -->

# Temp files — cleaned up on exit
TMPFILES=()
cleanup() {
  rm -f "${TMPFILES[@]}" 2>/dev/null || true
}
trap cleanup EXIT

mktemp_tracked() {
  local f
  f=$(mktemp "$@")
  TMPFILES+=("$f")
  echo "$f"
}

# ---------------------------------------------------------------------------
# Find the last-reviewed SHA from the existing summary comment.
# Returns the SHA via stdout, or empty string if no prior review.
# ---------------------------------------------------------------------------
get_last_reviewed_sha() {
  local comment_body
  comment_body=$(gh api "repos/${OWNER}/${REPO}/issues/${PR_NUMBER}/comments" \
    --paginate --jq ".[] | select(.body | contains(\"${MARKER_PREFIX}\")) | .body" \
    2>/dev/null | head -1) || true

  if [[ -n "$comment_body" ]]; then
    # Extract sha= value from marker: <!-- ai-pr-review-summary sha=abc1234 -->
    echo "$comment_body" | grep -oE "${MARKER_PREFIX} sha=[0-9a-f]+" | sed "s|${MARKER_PREFIX} sha=||" | head -1 || true
  fi
}

# ---------------------------------------------------------------------------
# Auto-resolve unresolved review threads posted by github-actions[bot]
# ---------------------------------------------------------------------------
resolve_stale_threads() {
  echo "Resolving stale review threads..." >&2

  # Fetch all unresolved review threads on this PR with their author login
  local threads_json
  threads_json=$(gh api graphql -f query='
    query($owner: String!, $repo: String!, $pr: Int!) {
      repository(owner: $owner, name: $repo) {
        pullRequest(number: $pr) {
          reviewThreads(first: 100) {
            nodes {
              id
              isResolved
              comments(first: 1) {
                nodes {
                  author {
                    login
                  }
                }
              }
            }
          }
        }
      }
    }' \
    -f owner="$OWNER" -f repo="$REPO" -F pr="$PR_NUMBER" \
    --jq '.data.repository.pullRequest.reviewThreads.nodes' 2>/dev/null) || {
    echo "WARNING: Could not fetch review threads for resolution." >&2
    return 0
  }

  # Filter to unresolved threads posted by github-actions[bot]
  local thread_ids
  thread_ids=$(echo "$threads_json" | jq -r '
    .[] | select(
      .isResolved == false and
      (.comments.nodes[0].author.login // "") == "github-actions[bot]"
    ) | .id
  ' 2>/dev/null) || true

  if [[ -z "$thread_ids" ]]; then
    echo "No stale threads to resolve." >&2
    return 0
  fi

  local resolved=0
  while IFS= read -r thread_id; do
    [[ -z "$thread_id" ]] && continue
    local resolve_result
    resolve_result=$(gh api graphql -f query='
      mutation($threadId: ID!) {
        resolveReviewThread(input: {threadId: $threadId}) {
          thread { id isResolved }
        }
      }' \
      -f threadId="$thread_id" 2>&1) || {
      echo "WARNING: Could not resolve thread ${thread_id}: ${resolve_result}" >&2
      continue
    }
    resolved=$(( resolved + 1 ))
  done <<< "$thread_ids"

  echo "Resolved ${resolved} stale review thread(s)." >&2
}

# ---------------------------------------------------------------------------
# Post Block A: Summary comment (idempotent via marker, embeds reviewed SHA)
# ---------------------------------------------------------------------------
post_summary() {
  local summary
  summary=$(cat "$SUMMARY_FILE")

  if [[ -z "$summary" ]]; then
    echo "No summary to post." >&2
    return 0
  fi

  # Embed the HEAD_SHA in the marker so subsequent runs can find the last-reviewed SHA
  local sha_marker="${MARKER_PREFIX} sha=${HEAD_SHA} -->"
  local body="${sha_marker}
${summary}

---
*AI Review Summary — generated by [ai-pr-review](https://github.com/tag1consulting/ai-pr-review)*"

  # Find existing summary comment by marker prefix
  local existing_comment_id
  existing_comment_id=$(gh api "repos/${OWNER}/${REPO}/issues/${PR_NUMBER}/comments" \
    --paginate --jq ".[] | select(.body | contains(\"${MARKER_PREFIX}\")) | .id" \
    2>/dev/null | head -1) || true

  if [[ -n "$existing_comment_id" ]]; then
    echo "Updating existing summary comment #${existing_comment_id}..." >&2
    gh api "repos/${OWNER}/${REPO}/issues/comments/${existing_comment_id}" \
      --method PATCH \
      --field body="$body" > /dev/null || {
      echo "ERROR: Failed to update summary comment #${existing_comment_id}." >&2
      return 1
    }
  else
    echo "Posting new summary comment..." >&2
    gh api "repos/${OWNER}/${REPO}/issues/${PR_NUMBER}/comments" \
      --method POST \
      --field body="$body" > /dev/null || {
      echo "ERROR: Failed to post summary comment." >&2
      return 1
    }
  fi

  echo "Summary comment posted to PR #${PR_NUMBER}." >&2
}

# ---------------------------------------------------------------------------
# Parse diff hunks to determine valid inline comment lines
# ---------------------------------------------------------------------------
# Builds a lookup of file:line pairs that are valid targets for inline comments.
# Only lines that appear in the "+" side of diff hunks are valid.
parse_valid_lines() {
  local diff_file="$1"
  local current_file=""
  local new_line=0

  while IFS= read -r line; do
    if [[ "$line" =~ ^diff\ --git\ a/(.+)\ b/(.+) ]]; then
      current_file="${BASH_REMATCH[2]}"
      new_line=0
    elif [[ "$line" =~ ^\+\+\+\  || "$line" =~ ^---\  ]]; then
      # Skip diff file headers (+++ b/file, --- a/file) — never treat as content
      continue
    elif [[ "$line" =~ ^@@\ -[0-9]+(,[0-9]+)?\ \+([0-9]+)(,[0-9]+)?\ @@ ]]; then
      new_line="${BASH_REMATCH[2]}"
    elif [[ -n "$current_file" && "$new_line" -gt 0 ]]; then
      if [[ "$line" =~ ^\+ ]]; then
        echo "${current_file}:${new_line}"
        new_line=$((new_line + 1))
      elif [[ "$line" =~ ^- ]]; then
        : # deleted line — don't increment new_line
      elif [[ "$line" =~ ^\\ ]]; then
        : # "\ No newline at end of file" — don't increment new_line
      else
        new_line=$((new_line + 1))
      fi
    fi
  done < "$diff_file"
}

# ---------------------------------------------------------------------------
# Post Block B: Findings as a pull request review with inline comments
# ---------------------------------------------------------------------------
post_findings() {
  local findings
  findings=$(cat "$FINDINGS_FILE")

  if [[ -z "$findings" || "$findings" == "NONE" ]]; then
    echo "No findings to post." >&2
    return 0
  fi

  # Parse the JSON findings for inline comments
  local findings_json="[]"
  if [[ -f "$FINDINGS_JSON_FILE" ]]; then
    findings_json=$(cat "$FINDINGS_JSON_FILE")
    # Validate it's valid JSON array
    if ! echo "$findings_json" | jq -e 'type == "array"' > /dev/null 2>&1; then
      echo "WARNING: Invalid findings JSON, posting as body-only review." >&2
      findings_json="[]"
    fi
  fi

  # Build valid lines lookup from diff
  local valid_lines_file
  valid_lines_file=$(mktemp_tracked /tmp/valid-lines-XXXXXXXX.txt)
  parse_valid_lines "$DIFF_FILE" > "$valid_lines_file"

  # Partition findings into inline (valid diff line) and body (everything else)
  local inline_comments="[]"
  local body_findings=""
  local inline_count=0
  local max_inline=25

  # Extract findings as newline-delimited JSON objects for safe iteration
  # (avoids seq 0 $((total-1)) which breaks on BSD when total=0)
  local findings_ndjson
  findings_ndjson=$(echo "$findings_json" | jq -c '.[]' 2>/dev/null || true)

  while IFS= read -r finding_obj; do
    [[ -z "$finding_obj" ]] && continue
    local file line severity finding remediation
    file=$(echo "$finding_obj" | jq -r '.file // empty')
    line=$(echo "$finding_obj" | jq -r '.line // empty')
    severity=$(echo "$finding_obj" | jq -r '.severity // "Medium"')
    finding=$(echo "$finding_obj" | jq -r '.finding // empty')
    remediation=$(echo "$finding_obj" | jq -r '.remediation // empty')

    if [[ -z "$file" || -z "$line" || -z "$finding" ]]; then
      continue
    fi

    # Validate line is a positive integer (LLM may return non-numeric values)
    if ! [[ "$line" =~ ^[0-9]+$ ]]; then
      echo "WARNING: Skipping finding with non-numeric line: ${file}:${line}" >&2
      body_findings="${body_findings}
- **[${severity}]** ${finding} — \`${file}:${line}\`"
      continue
    fi

    # Check if this line is a valid inline comment target (whole-line match)
    if grep -qxF "${file}:${line}" "$valid_lines_file" && [[ "$inline_count" -lt "$max_inline" ]]; then
      local comment_body="**[${severity}]** ${finding}"
      if [[ -n "$remediation" ]]; then
        comment_body="${comment_body}

**Remediation:** ${remediation}"
      fi

      inline_comments=$(echo "$inline_comments" | jq \
        --arg path "$file" \
        --argjson line "$line" \
        --arg body "$comment_body" \
        '. + [{"path": $path, "line": $line, "body": $body}]')
      inline_count=$((inline_count + 1))
    else
      body_findings="${body_findings}
- **[${severity}]** ${finding} — \`${file}:${line}\`"
    fi
  done <<< "$findings_ndjson"

  # Determine overall risk and review event from highest severity found
  #   No findings          → APPROVE
  #   Medium/Low findings  → COMMENT  (informational, non-blocking)
  #   High/Critical        → REQUEST_CHANGES (blocking)
  local overall_risk finding_total review_event
  finding_total=$(echo "$findings_json" | jq 'length')

  if [[ "$finding_total" -eq 0 ]]; then
    overall_risk="None"
    review_event="APPROVE"
  elif echo "$findings_json" | jq -e '.[] | select(.severity == "Critical")' > /dev/null 2>&1; then
    overall_risk="Critical"
    review_event="REQUEST_CHANGES"
  elif echo "$findings_json" | jq -e '.[] | select(.severity == "High")' > /dev/null 2>&1; then
    overall_risk="High"
    review_event="REQUEST_CHANGES"
  elif echo "$findings_json" | jq -e '.[] | select(.severity == "Medium")' > /dev/null 2>&1; then
    overall_risk="Medium"
    review_event="COMMENT"
  else
    overall_risk="Low"
    review_event="COMMENT"
  fi

  # Build review body
  local review_body
  if [[ "$review_event" == "APPROVE" ]]; then
    review_body="## AI Review: Approved

No findings above the confidence threshold. The changes look good.

---
*AI Review — generated by [ai-pr-review](https://github.com/tag1consulting/ai-pr-review)*"
  else
    review_body="## AI Review Findings

**Overall Risk:** ${overall_risk} | **Findings:** ${finding_total} (${inline_count} inline)"

    if [[ -n "$body_findings" ]]; then
      review_body="${review_body}

### Findings not attached to specific lines
${body_findings}"
    elif [[ "$inline_count" -gt 0 ]]; then
      review_body="${review_body}

All findings are attached as inline comments."
    fi

    review_body="${review_body}

---
*AI Review — generated by [ai-pr-review](https://github.com/tag1consulting/ai-pr-review)*"
  fi

  # APPROVE does not support inline comments — clear them if present
  if [[ "$review_event" == "APPROVE" ]]; then
    inline_comments="[]"
    inline_count=0
  fi

  # Build the review request JSON with commit_id to anchor inline comments
  local review_json
  review_json=$(jq -n \
    --arg body "$review_body" \
    --arg event "$review_event" \
    --arg commit_id "$HEAD_SHA" \
    --argjson comments "$inline_comments" \
    '{body: $body, event: $event, commit_id: $commit_id, comments: $comments}')

  echo "Posting review (${review_event}) with ${inline_count} inline comments..." >&2

  local review_result
  review_result=$(echo "$review_json" | gh api "repos/${OWNER}/${REPO}/pulls/${PR_NUMBER}/reviews" \
    --method POST \
    --input - 2>&1) || {
    echo "WARNING: Failed to post ${review_event} review: ${review_result}" >&2

    # If REQUEST_CHANGES or APPROVE failed (e.g. GITHUB_TOKEN can't approve/block
    # its own PR author's work), retry as COMMENT
    if [[ "$review_event" == "REQUEST_CHANGES" || "$review_event" == "APPROVE" ]]; then
      echo "Retrying as COMMENT review..." >&2
      review_json=$(echo "$review_json" | jq '.event = "COMMENT"')
      review_result=$(echo "$review_json" | gh api "repos/${OWNER}/${REPO}/pulls/${PR_NUMBER}/reviews" \
        --method POST \
        --input - 2>&1) || {
        echo "ERROR: COMMENT review also failed: ${review_result}" >&2
        echo "Falling back to posting as a PR comment..." >&2
        gh api "repos/${OWNER}/${REPO}/issues/${PR_NUMBER}/comments" \
          --method POST \
          --field body="${review_body}" > /dev/null || \
          echo "ERROR: All three posting attempts failed (${review_event} → COMMENT → PR comment)." >&2
        return 1
      }
      echo "Review posted as COMMENT (${review_event} unavailable) to PR #${PR_NUMBER}." >&2
      return 0
    fi

    # COMMENT also failed — fall back to regular PR comment
    echo "Falling back to posting as a PR comment..." >&2
    gh api "repos/${OWNER}/${REPO}/issues/${PR_NUMBER}/comments" \
      --method POST \
      --field body="${review_body}" > /dev/null || \
      echo "ERROR: All three posting attempts failed (${review_event} → COMMENT → PR comment)." >&2
    return 1
  }

  echo "Review posted (${review_event}) to PR #${PR_NUMBER}: ${inline_count} inline, overflow in body." >&2
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

# If called with --get-last-sha, just return the last reviewed SHA and exit.
# Used by review.sh to determine the incremental diff base.
if [[ "${1:-}" == "--get-last-sha" ]]; then
  get_last_reviewed_sha
  exit 0
fi

resolve_stale_threads
post_summary
post_findings
