// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("lagoon");

/**
 * The Lagoon GraphQL API endpoint URL.
 */
export declare const apiUrl: string;
Object.defineProperty(exports, "apiUrl", {
    get() {
        return __config.get("apiUrl") ?? (utilities.getEnv("LAGOON_API_URL") || "https://api.lagoon.sh/graphql");
    },
    enumerable: true,
});

/**
 * Disable SSL certificate verification when connecting to the Lagoon API.
 */
export declare const insecure: boolean;
Object.defineProperty(exports, "insecure", {
    get() {
        return __config.getObject<boolean>("insecure") ?? (utilities.getEnvBoolean("LAGOON_INSECURE") || false);
    },
    enumerable: true,
});

/**
 * The audience claim for generated JWT tokens. Defaults to 'api.dev'.
 */
export declare const jwtAudience: string;
Object.defineProperty(exports, "jwtAudience", {
    get() {
        return __config.get("jwtAudience") ?? (utilities.getEnv("LAGOON_JWT_AUDIENCE") || "api.dev");
    },
    enumerable: true,
});

/**
 * The Lagoon core JWTSECRET. Used to generate admin tokens on-the-fly.
 */
export declare const jwtSecret: string | undefined;
Object.defineProperty(exports, "jwtSecret", {
    get() {
        return __config.get("jwtSecret") ?? utilities.getEnv("LAGOON_JWT_SECRET");
    },
    enumerable: true,
});

/**
 * A pre-configured JWT authentication token for the Lagoon API.
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token") ?? utilities.getEnv("LAGOON_TOKEN");
    },
    enumerable: true,
});

