// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Tag1Consulting.Lagoon.Lagoon
{
    /// <summary>
    /// Manages a Lagoon Kubernetes deploy target (cluster).
    /// </summary>
    [LagoonResourceType("lagoon:lagoon:DeployTarget")]
    public partial class DeployTarget : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Custom build image.
        /// </summary>
        [Output("buildImage")]
        public Output<string?> BuildImage { get; private set; } = null!;

        /// <summary>
        /// Cloud provider (e.g., 'kind', 'aws', 'gcp'). Defaults to 'kind'.
        /// </summary>
        [Output("cloudProvider")]
        public Output<string?> CloudProvider { get; private set; } = null!;

        /// <summary>
        /// Cloud region (e.g., 'us-east-1', 'local'). Defaults to 'local'.
        /// </summary>
        [Output("cloudRegion")]
        public Output<string?> CloudRegion { get; private set; } = null!;

        /// <summary>
        /// The Kubernetes API URL.
        /// </summary>
        [Output("consoleUrl")]
        public Output<string> ConsoleUrl { get; private set; } = null!;

        [Output("created")]
        public Output<string> Created { get; private set; } = null!;

        /// <summary>
        /// Whether the deploy target is disabled.
        /// </summary>
        [Output("disabled")]
        public Output<bool?> Disabled { get; private set; } = null!;

        [Output("lagoonId")]
        public Output<int> LagoonId { get; private set; } = null!;

        /// <summary>
        /// The deploy target name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Router pattern for the deploy target.
        /// </summary>
        [Output("routerPattern")]
        public Output<string?> RouterPattern { get; private set; } = null!;

        /// <summary>
        /// SSH host for builds.
        /// </summary>
        [Output("sshHost")]
        public Output<string?> SshHost { get; private set; } = null!;

        /// <summary>
        /// SSH port for builds.
        /// </summary>
        [Output("sshPort")]
        public Output<string?> SshPort { get; private set; } = null!;


        /// <summary>
        /// Create a DeployTarget resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public DeployTarget(string name, DeployTargetArgs args, CustomResourceOptions? options = null)
            : base("lagoon:lagoon:DeployTarget", name, args ?? new DeployTargetArgs(), MakeResourceOptions(options, ""))
        {
        }

        private DeployTarget(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("lagoon:lagoon:DeployTarget", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/tag1consulting/pulumi-lagoon-provider",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing DeployTarget resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static DeployTarget Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new DeployTarget(name, id, options);
        }
    }

    public sealed class DeployTargetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Custom build image.
        /// </summary>
        [Input("buildImage")]
        public Input<string>? BuildImage { get; set; }

        /// <summary>
        /// Cloud provider (e.g., 'kind', 'aws', 'gcp'). Defaults to 'kind'.
        /// </summary>
        [Input("cloudProvider")]
        public Input<string>? CloudProvider { get; set; }

        /// <summary>
        /// Cloud region (e.g., 'us-east-1', 'local'). Defaults to 'local'.
        /// </summary>
        [Input("cloudRegion")]
        public Input<string>? CloudRegion { get; set; }

        /// <summary>
        /// The Kubernetes API URL.
        /// </summary>
        [Input("consoleUrl", required: true)]
        public Input<string> ConsoleUrl { get; set; } = null!;

        /// <summary>
        /// Whether the deploy target is disabled.
        /// </summary>
        [Input("disabled")]
        public Input<bool>? Disabled { get; set; }

        /// <summary>
        /// The deploy target name.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Router pattern for the deploy target.
        /// </summary>
        [Input("routerPattern")]
        public Input<string>? RouterPattern { get; set; }

        /// <summary>
        /// SSH host for builds.
        /// </summary>
        [Input("sshHost")]
        public Input<string>? SshHost { get; set; }

        /// <summary>
        /// SSH port for builds.
        /// </summary>
        [Input("sshPort")]
        public Input<string>? SshPort { get; set; }

        public DeployTargetArgs()
        {
        }
        public static new DeployTargetArgs Empty => new DeployTargetArgs();
    }
}
