// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Tag1Consulting.Lagoon.Lagoon
{
    /// <summary>
    /// Manages a Lagoon environment (branch/PR deployment).
    /// </summary>
    [LagoonResourceType("lagoon:lagoon:Environment")]
    public partial class Environment : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether to auto-idle this environment (1=yes, 0=no).
        /// </summary>
        [Output("autoIdle")]
        public Output<int?> AutoIdle { get; private set; } = null!;

        /// <summary>
        /// The creation timestamp.
        /// </summary>
        [Output("created")]
        public Output<string> Created { get; private set; } = null!;

        /// <summary>
        /// The base ref for the deployment.
        /// </summary>
        [Output("deployBaseRef")]
        public Output<string?> DeployBaseRef { get; private set; } = null!;

        /// <summary>
        /// The head ref for pull request deployments.
        /// </summary>
        [Output("deployHeadRef")]
        public Output<string?> DeployHeadRef { get; private set; } = null!;

        /// <summary>
        /// Title for pull request deployments.
        /// </summary>
        [Output("deployTitle")]
        public Output<string?> DeployTitle { get; private set; } = null!;

        /// <summary>
        /// Deployment type: 'branch' or 'pullrequest'.
        /// </summary>
        [Output("deployType")]
        public Output<string> DeployType { get; private set; } = null!;

        /// <summary>
        /// Environment type: 'production' or 'development'.
        /// </summary>
        [Output("environmentType")]
        public Output<string> EnvironmentType { get; private set; } = null!;

        /// <summary>
        /// The Lagoon-assigned numeric ID of the environment.
        /// </summary>
        [Output("lagoonId")]
        public Output<int> LagoonId { get; private set; } = null!;

        /// <summary>
        /// The environment name (typically the branch name).
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Override namespace name on the cluster.
        /// </summary>
        [Output("openshiftProjectName")]
        public Output<string?> OpenshiftProjectName { get; private set; } = null!;

        /// <summary>
        /// The parent project ID.
        /// </summary>
        [Output("projectId")]
        public Output<int> ProjectId { get; private set; } = null!;

        /// <summary>
        /// The primary route URL for this environment.
        /// </summary>
        [Output("route")]
        public Output<string> Route { get; private set; } = null!;

        /// <summary>
        /// All route URLs for this environment.
        /// </summary>
        [Output("routes")]
        public Output<string> Routes { get; private set; } = null!;


        /// <summary>
        /// Create a Environment resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Environment(string name, EnvironmentArgs args, CustomResourceOptions? options = null)
            : base("lagoon:lagoon:Environment", name, args ?? new EnvironmentArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Environment(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("lagoon:lagoon:Environment", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/tag1consulting/pulumi-lagoon-provider",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Environment resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Environment Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Environment(name, id, options);
        }
    }

    public sealed class EnvironmentArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to auto-idle this environment (1=yes, 0=no).
        /// </summary>
        [Input("autoIdle")]
        public Input<int>? AutoIdle { get; set; }

        /// <summary>
        /// The base ref for the deployment.
        /// </summary>
        [Input("deployBaseRef")]
        public Input<string>? DeployBaseRef { get; set; }

        /// <summary>
        /// The head ref for pull request deployments.
        /// </summary>
        [Input("deployHeadRef")]
        public Input<string>? DeployHeadRef { get; set; }

        /// <summary>
        /// Title for pull request deployments.
        /// </summary>
        [Input("deployTitle")]
        public Input<string>? DeployTitle { get; set; }

        /// <summary>
        /// Deployment type: 'branch' or 'pullrequest'.
        /// </summary>
        [Input("deployType", required: true)]
        public Input<string> DeployType { get; set; } = null!;

        /// <summary>
        /// Environment type: 'production' or 'development'.
        /// </summary>
        [Input("environmentType", required: true)]
        public Input<string> EnvironmentType { get; set; } = null!;

        /// <summary>
        /// The environment name (typically the branch name).
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Override namespace name on the cluster.
        /// </summary>
        [Input("openshiftProjectName")]
        public Input<string>? OpenshiftProjectName { get; set; }

        /// <summary>
        /// The parent project ID.
        /// </summary>
        [Input("projectId", required: true)]
        public Input<int> ProjectId { get; set; } = null!;

        public EnvironmentArgs()
        {
        }
        public static new EnvironmentArgs Empty => new EnvironmentArgs();
    }
}
