// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Tag1Consulting.Lagoon.Lagoon
{
    /// <summary>
    /// Manages a Lagoon RocketChat notification configuration.
    /// </summary>
    [LagoonResourceType("lagoon:lagoon:NotificationRocketChat")]
    public partial class NotificationRocketChat : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The RocketChat channel.
        /// </summary>
        [Output("channel")]
        public Output<string> Channel { get; private set; } = null!;

        [Output("lagoonId")]
        public Output<int> LagoonId { get; private set; } = null!;

        /// <summary>
        /// The notification name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The RocketChat webhook URL (stored as secret).
        /// </summary>
        [Output("webhook")]
        public Output<string> Webhook { get; private set; } = null!;


        /// <summary>
        /// Create a NotificationRocketChat resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NotificationRocketChat(string name, NotificationRocketChatArgs args, CustomResourceOptions? options = null)
            : base("lagoon:lagoon:NotificationRocketChat", name, args ?? new NotificationRocketChatArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NotificationRocketChat(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("lagoon:lagoon:NotificationRocketChat", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/tag1consulting/pulumi-lagoon-provider",
                AdditionalSecretOutputs =
                {
                    "webhook",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NotificationRocketChat resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NotificationRocketChat Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new NotificationRocketChat(name, id, options);
        }
    }

    public sealed class NotificationRocketChatArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The RocketChat channel.
        /// </summary>
        [Input("channel", required: true)]
        public Input<string> Channel { get; set; } = null!;

        /// <summary>
        /// The notification name.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("webhook", required: true)]
        private Input<string>? _webhook;

        /// <summary>
        /// The RocketChat webhook URL (stored as secret).
        /// </summary>
        public Input<string>? Webhook
        {
            get => _webhook;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _webhook = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public NotificationRocketChatArgs()
        {
        }
        public static new NotificationRocketChatArgs Empty => new NotificationRocketChatArgs();
    }
}
