// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Tag1Consulting.Lagoon.Lagoon
{
    /// <summary>
    /// Manages a Lagoon project (application/site).
    /// </summary>
    [LagoonResourceType("lagoon:lagoon:Project")]
    public partial class Project : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether to auto-idle environments (1=yes, 0=no).
        /// </summary>
        [Output("autoIdle")]
        public Output<int?> AutoIdle { get; private set; } = null!;

        /// <summary>
        /// Regex pattern for branches to deploy.
        /// </summary>
        [Output("branches")]
        public Output<string?> Branches { get; private set; } = null!;

        /// <summary>
        /// The creation timestamp of the project.
        /// </summary>
        [Output("created")]
        public Output<string> Created { get; private set; } = null!;

        /// <summary>
        /// The deploy target (Kubernetes cluster) ID.
        /// </summary>
        [Output("deploytargetId")]
        public Output<int> DeploytargetId { get; private set; } = null!;

        /// <summary>
        /// The Git repository URL (SSH or HTTPS format).
        /// </summary>
        [Output("gitUrl")]
        public Output<string> GitUrl { get; private set; } = null!;

        /// <summary>
        /// The Lagoon-assigned numeric ID of the project.
        /// </summary>
        [Output("lagoonId")]
        public Output<int> LagoonId { get; private set; } = null!;

        /// <summary>
        /// The project name. Must be unique, lowercase alphanumeric with hyphens.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Namespace pattern for the project on the cluster.
        /// </summary>
        [Output("openshiftProjectPattern")]
        public Output<string?> OpenshiftProjectPattern { get; private set; } = null!;

        /// <summary>
        /// Name of the production branch/environment.
        /// </summary>
        [Output("productionEnvironment")]
        public Output<string?> ProductionEnvironment { get; private set; } = null!;

        /// <summary>
        /// The SSH public deploy key generated by Lagoon. Add this to the Git repository to grant Lagoon read access.
        /// </summary>
        [Output("publicKey")]
        public Output<string> PublicKey { get; private set; } = null!;

        /// <summary>
        /// Regex pattern for pull requests to deploy.
        /// </summary>
        [Output("pullrequests")]
        public Output<string?> Pullrequests { get; private set; } = null!;

        /// <summary>
        /// Whether to calculate storage (1=yes, 0=no).
        /// </summary>
        [Output("storageCalc")]
        public Output<int?> StorageCalc { get; private set; } = null!;


        /// <summary>
        /// Create a Project resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Project(string name, ProjectArgs args, CustomResourceOptions? options = null)
            : base("lagoon:lagoon:Project", name, args ?? new ProjectArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Project(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("lagoon:lagoon:Project", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/tag1consulting/pulumi-lagoon-provider",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Project resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Project Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Project(name, id, options);
        }
    }

    public sealed class ProjectArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to auto-idle environments (1=yes, 0=no).
        /// </summary>
        [Input("autoIdle")]
        public Input<int>? AutoIdle { get; set; }

        /// <summary>
        /// Regex pattern for branches to deploy.
        /// </summary>
        [Input("branches")]
        public Input<string>? Branches { get; set; }

        /// <summary>
        /// The deploy target (Kubernetes cluster) ID.
        /// </summary>
        [Input("deploytargetId", required: true)]
        public Input<int> DeploytargetId { get; set; } = null!;

        /// <summary>
        /// The Git repository URL (SSH or HTTPS format).
        /// </summary>
        [Input("gitUrl", required: true)]
        public Input<string> GitUrl { get; set; } = null!;

        /// <summary>
        /// The project name. Must be unique, lowercase alphanumeric with hyphens.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Namespace pattern for the project on the cluster.
        /// </summary>
        [Input("openshiftProjectPattern")]
        public Input<string>? OpenshiftProjectPattern { get; set; }

        /// <summary>
        /// Name of the production branch/environment.
        /// </summary>
        [Input("productionEnvironment")]
        public Input<string>? ProductionEnvironment { get; set; }

        /// <summary>
        /// Regex pattern for pull requests to deploy.
        /// </summary>
        [Input("pullrequests")]
        public Input<string>? Pullrequests { get; set; }

        /// <summary>
        /// Whether to calculate storage (1=yes, 0=no).
        /// </summary>
        [Input("storageCalc")]
        public Input<int>? StorageCalc { get; set; }

        public ProjectArgs()
        {
        }
        public static new ProjectArgs Empty => new ProjectArgs();
    }
}
