// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Tag1Consulting.Lagoon.Lagoon
{
    /// <summary>
    /// Manages a Lagoon API-defined route on a project (requires Lagoon v2.29.0+).
    /// </summary>
    [LagoonResourceType("lagoon:lagoon:Route")]
    public partial class Route : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Additional SAN domains for the TLS certificate (max 25).
        /// </summary>
        [Output("alternativeNames")]
        public Output<ImmutableArray<string>> AlternativeNames { get; private set; } = null!;

        /// <summary>
        /// Ingress annotations (key/value pairs, max 10).
        /// </summary>
        [Output("annotations")]
        public Output<ImmutableArray<Tag1Consulting.Lagoon.Resources.Outputs.RouteAnnotationInput>> Annotations { get; private set; } = null!;

        /// <summary>
        /// Timestamp when the route was created.
        /// </summary>
        [Output("created")]
        public Output<string> Created { get; private set; } = null!;

        /// <summary>
        /// Whether to disable request verification.
        /// </summary>
        [Output("disableRequestVerification")]
        public Output<bool?> DisableRequestVerification { get; private set; } = null!;

        /// <summary>
        /// The primary domain for the route (e.g., 'example.com'). Changing this forces replacement.
        /// </summary>
        [Output("domain")]
        public Output<string> Domain { get; private set; } = null!;

        /// <summary>
        /// The environment to attach this route to.
        /// </summary>
        [Output("environment")]
        public Output<string?> Environment { get; private set; } = null!;

        /// <summary>
        /// Whether to enable HTTP Strict Transport Security.
        /// </summary>
        [Output("hstsEnabled")]
        public Output<bool?> HstsEnabled { get; private set; } = null!;

        /// <summary>
        /// Whether to include subdomains in HSTS.
        /// </summary>
        [Output("hstsIncludeSubdomains")]
        public Output<bool?> HstsIncludeSubdomains { get; private set; } = null!;

        /// <summary>
        /// HSTS max-age in seconds.
        /// </summary>
        [Output("hstsMaxAge")]
        public Output<int?> HstsMaxAge { get; private set; } = null!;

        /// <summary>
        /// Whether to include the preload directive in HSTS.
        /// </summary>
        [Output("hstsPreload")]
        public Output<bool?> HstsPreload { get; private set; } = null!;

        /// <summary>
        /// How to handle insecure (HTTP) traffic: Allow, Redirect, or None. Defaults to Redirect.
        /// </summary>
        [Output("insecure")]
        public Output<string?> Insecure { get; private set; } = null!;

        /// <summary>
        /// The Lagoon-assigned numeric route ID.
        /// </summary>
        [Output("lagoonId")]
        public Output<int> LagoonId { get; private set; } = null!;

        /// <summary>
        /// Path to use for uptime monitoring.
        /// </summary>
        [Output("monitoringPath")]
        public Output<string?> MonitoringPath { get; private set; } = null!;

        /// <summary>
        /// Path-based routing rules (max 10).
        /// </summary>
        [Output("pathRoutes")]
        public Output<ImmutableArray<Tag1Consulting.Lagoon.Resources.Outputs.RoutePathRouteInput>> PathRoutes { get; private set; } = null!;

        /// <summary>
        /// Whether this is the primary route.
        /// </summary>
        [Output("primary")]
        public Output<bool?> Primary { get; private set; } = null!;

        /// <summary>
        /// The Lagoon project name this route belongs to.
        /// </summary>
        [Output("projectName")]
        public Output<string> ProjectName { get; private set; } = null!;

        /// <summary>
        /// Route type for active/standby: STANDARD, ACTIVE, or STANDBY.
        /// </summary>
        [Output("routeType")]
        public Output<string?> RouteType { get; private set; } = null!;

        /// <summary>
        /// The service to route traffic to (e.g., 'nginx').
        /// </summary>
        [Output("service")]
        public Output<string?> Service { get; private set; } = null!;

        /// <summary>
        /// The source of this route: API, YAML, or AUTOGENERATED.
        /// </summary>
        [Output("source")]
        public Output<string> Source { get; private set; } = null!;

        /// <summary>
        /// Whether to use Let's Encrypt for TLS. Defaults to true.
        /// </summary>
        [Output("tlsAcme")]
        public Output<bool?> TlsAcme { get; private set; } = null!;

        /// <summary>
        /// Timestamp when the route was last updated.
        /// </summary>
        [Output("updated")]
        public Output<string> Updated { get; private set; } = null!;


        /// <summary>
        /// Create a Route resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Route(string name, RouteArgs args, CustomResourceOptions? options = null)
            : base("lagoon:lagoon:Route", name, args ?? new RouteArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Route(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("lagoon:lagoon:Route", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/tag1consulting/pulumi-lagoon-provider",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Route resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Route Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Route(name, id, options);
        }
    }

    public sealed class RouteArgs : global::Pulumi.ResourceArgs
    {
        [Input("alternativeNames")]
        private InputList<string>? _alternativeNames;

        /// <summary>
        /// Additional SAN domains for the TLS certificate (max 25).
        /// </summary>
        public InputList<string> AlternativeNames
        {
            get => _alternativeNames ?? (_alternativeNames = new InputList<string>());
            set => _alternativeNames = value;
        }

        [Input("annotations")]
        private InputList<Tag1Consulting.Lagoon.Resources.Inputs.RouteAnnotationInputArgs>? _annotations;

        /// <summary>
        /// Ingress annotations (key/value pairs, max 10).
        /// </summary>
        public InputList<Tag1Consulting.Lagoon.Resources.Inputs.RouteAnnotationInputArgs> Annotations
        {
            get => _annotations ?? (_annotations = new InputList<Tag1Consulting.Lagoon.Resources.Inputs.RouteAnnotationInputArgs>());
            set => _annotations = value;
        }

        /// <summary>
        /// Whether to disable request verification.
        /// </summary>
        [Input("disableRequestVerification")]
        public Input<bool>? DisableRequestVerification { get; set; }

        /// <summary>
        /// The primary domain for the route (e.g., 'example.com'). Changing this forces replacement.
        /// </summary>
        [Input("domain", required: true)]
        public Input<string> Domain { get; set; } = null!;

        /// <summary>
        /// The environment to attach this route to.
        /// </summary>
        [Input("environment")]
        public Input<string>? Environment { get; set; }

        /// <summary>
        /// Whether to enable HTTP Strict Transport Security.
        /// </summary>
        [Input("hstsEnabled")]
        public Input<bool>? HstsEnabled { get; set; }

        /// <summary>
        /// Whether to include subdomains in HSTS.
        /// </summary>
        [Input("hstsIncludeSubdomains")]
        public Input<bool>? HstsIncludeSubdomains { get; set; }

        /// <summary>
        /// HSTS max-age in seconds.
        /// </summary>
        [Input("hstsMaxAge")]
        public Input<int>? HstsMaxAge { get; set; }

        /// <summary>
        /// Whether to include the preload directive in HSTS.
        /// </summary>
        [Input("hstsPreload")]
        public Input<bool>? HstsPreload { get; set; }

        /// <summary>
        /// How to handle insecure (HTTP) traffic: Allow, Redirect, or None. Defaults to Redirect.
        /// </summary>
        [Input("insecure")]
        public Input<string>? Insecure { get; set; }

        /// <summary>
        /// Path to use for uptime monitoring.
        /// </summary>
        [Input("monitoringPath")]
        public Input<string>? MonitoringPath { get; set; }

        [Input("pathRoutes")]
        private InputList<Tag1Consulting.Lagoon.Resources.Inputs.RoutePathRouteInputArgs>? _pathRoutes;

        /// <summary>
        /// Path-based routing rules (max 10).
        /// </summary>
        public InputList<Tag1Consulting.Lagoon.Resources.Inputs.RoutePathRouteInputArgs> PathRoutes
        {
            get => _pathRoutes ?? (_pathRoutes = new InputList<Tag1Consulting.Lagoon.Resources.Inputs.RoutePathRouteInputArgs>());
            set => _pathRoutes = value;
        }

        /// <summary>
        /// Whether this is the primary route.
        /// </summary>
        [Input("primary")]
        public Input<bool>? Primary { get; set; }

        /// <summary>
        /// The Lagoon project name this route belongs to.
        /// </summary>
        [Input("projectName", required: true)]
        public Input<string> ProjectName { get; set; } = null!;

        /// <summary>
        /// Route type for active/standby: STANDARD, ACTIVE, or STANDBY.
        /// </summary>
        [Input("routeType")]
        public Input<string>? RouteType { get; set; }

        /// <summary>
        /// The service to route traffic to (e.g., 'nginx').
        /// </summary>
        [Input("service")]
        public Input<string>? Service { get; set; }

        /// <summary>
        /// Whether to use Let's Encrypt for TLS. Defaults to true.
        /// </summary>
        [Input("tlsAcme")]
        public Input<bool>? TlsAcme { get; set; }

        public RouteArgs()
        {
        }
        public static new RouteArgs Empty => new RouteArgs();
    }
}
