// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Tag1Consulting.Lagoon.Lagoon
{
    /// <summary>
    /// Manages a Lagoon advanced task definition.
    /// </summary>
    [LagoonResourceType("lagoon:lagoon:Task")]
    public partial class Task : global::Pulumi.CustomResource
    {
        /// <summary>
        /// List of argument definitions for the task.
        /// </summary>
        [Output("arguments")]
        public Output<ImmutableArray<Tag1Consulting.Lagoon.Resources.Outputs.TaskArgumentInput>> Arguments { get; private set; } = null!;

        /// <summary>
        /// Command to execute (required for 'command' type).
        /// </summary>
        [Output("command")]
        public Output<string?> Command { get; private set; } = null!;

        /// <summary>
        /// Text to display for user confirmation.
        /// </summary>
        [Output("confirmationText")]
        public Output<string?> ConfirmationText { get; private set; } = null!;

        [Output("created")]
        public Output<string> Created { get; private set; } = null!;

        /// <summary>
        /// Task description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Environment ID (for environment-scoped tasks).
        /// </summary>
        [Output("environmentId")]
        public Output<int?> EnvironmentId { get; private set; } = null!;

        /// <summary>
        /// Group name (for group-scoped tasks).
        /// </summary>
        [Output("groupName")]
        public Output<string?> GroupName { get; private set; } = null!;

        /// <summary>
        /// Container image to run (required for 'image' type).
        /// </summary>
        [Output("image")]
        public Output<string?> Image { get; private set; } = null!;

        [Output("lagoonId")]
        public Output<int> LagoonId { get; private set; } = null!;

        /// <summary>
        /// The task definition name.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Permission level: 'guest', 'developer', or 'maintainer'.
        /// </summary>
        [Output("permission")]
        public Output<string?> Permission { get; private set; } = null!;

        /// <summary>
        /// Project ID (for project-scoped tasks).
        /// </summary>
        [Output("projectId")]
        public Output<int?> ProjectId { get; private set; } = null!;

        /// <summary>
        /// Service container name to run the task in.
        /// </summary>
        [Output("service")]
        public Output<string> Service { get; private set; } = null!;

        /// <summary>
        /// If true, task is available system-wide (platform admin only).
        /// </summary>
        [Output("systemWide")]
        public Output<bool?> SystemWide { get; private set; } = null!;

        /// <summary>
        /// Task type: 'command' or 'image'.
        /// </summary>
        [Output("type")]
        public Output<string> Type { get; private set; } = null!;


        /// <summary>
        /// Create a Task resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Task(string name, TaskArgs args, CustomResourceOptions? options = null)
            : base("lagoon:lagoon:Task", name, args ?? new TaskArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Task(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("lagoon:lagoon:Task", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/tag1consulting/pulumi-lagoon-provider",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Task resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Task Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new Task(name, id, options);
        }
    }

    public sealed class TaskArgs : global::Pulumi.ResourceArgs
    {
        [Input("arguments")]
        private InputList<Tag1Consulting.Lagoon.Resources.Inputs.TaskArgumentInputArgs>? _arguments;

        /// <summary>
        /// List of argument definitions for the task.
        /// </summary>
        public InputList<Tag1Consulting.Lagoon.Resources.Inputs.TaskArgumentInputArgs> Arguments
        {
            get => _arguments ?? (_arguments = new InputList<Tag1Consulting.Lagoon.Resources.Inputs.TaskArgumentInputArgs>());
            set => _arguments = value;
        }

        /// <summary>
        /// Command to execute (required for 'command' type).
        /// </summary>
        [Input("command")]
        public Input<string>? Command { get; set; }

        /// <summary>
        /// Text to display for user confirmation.
        /// </summary>
        [Input("confirmationText")]
        public Input<string>? ConfirmationText { get; set; }

        /// <summary>
        /// Task description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Environment ID (for environment-scoped tasks).
        /// </summary>
        [Input("environmentId")]
        public Input<int>? EnvironmentId { get; set; }

        /// <summary>
        /// Group name (for group-scoped tasks).
        /// </summary>
        [Input("groupName")]
        public Input<string>? GroupName { get; set; }

        /// <summary>
        /// Container image to run (required for 'image' type).
        /// </summary>
        [Input("image")]
        public Input<string>? Image { get; set; }

        /// <summary>
        /// The task definition name.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Permission level: 'guest', 'developer', or 'maintainer'.
        /// </summary>
        [Input("permission")]
        public Input<string>? Permission { get; set; }

        /// <summary>
        /// Project ID (for project-scoped tasks).
        /// </summary>
        [Input("projectId")]
        public Input<int>? ProjectId { get; set; }

        /// <summary>
        /// Service container name to run the task in.
        /// </summary>
        [Input("service", required: true)]
        public Input<string> Service { get; set; } = null!;

        /// <summary>
        /// If true, task is available system-wide (platform admin only).
        /// </summary>
        [Input("systemWide")]
        public Input<bool>? SystemWide { get; set; }

        /// <summary>
        /// Task type: 'command' or 'image'.
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public TaskArgs()
        {
        }
        public static new TaskArgs Empty => new TaskArgs();
    }
}
