// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Tag1Consulting.Lagoon.Lagoon
{
    /// <summary>
    /// Assigns a platform-level role (OWNER or VIEWER) to a Lagoon user.
    /// </summary>
    [LagoonResourceType("lagoon:lagoon:UserPlatformRole")]
    public partial class UserPlatformRole : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The platform role: OWNER or VIEWER.
        /// </summary>
        [Output("role")]
        public Output<string> Role { get; private set; } = null!;

        /// <summary>
        /// The user's email address.
        /// </summary>
        [Output("userEmail")]
        public Output<string> UserEmail { get; private set; } = null!;


        /// <summary>
        /// Create a UserPlatformRole resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public UserPlatformRole(string name, UserPlatformRoleArgs args, CustomResourceOptions? options = null)
            : base("lagoon:lagoon:UserPlatformRole", name, args ?? new UserPlatformRoleArgs(), MakeResourceOptions(options, ""))
        {
        }

        private UserPlatformRole(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("lagoon:lagoon:UserPlatformRole", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/tag1consulting/pulumi-lagoon-provider",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing UserPlatformRole resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static UserPlatformRole Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new UserPlatformRole(name, id, options);
        }
    }

    public sealed class UserPlatformRoleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The platform role: OWNER or VIEWER.
        /// </summary>
        [Input("role", required: true)]
        public Input<string> Role { get; set; } = null!;

        /// <summary>
        /// The user's email address.
        /// </summary>
        [Input("userEmail", required: true)]
        public Input<string> UserEmail { get; set; } = null!;

        public UserPlatformRoleArgs()
        {
        }
        public static new UserPlatformRoleArgs Empty => new UserPlatformRoleArgs();
    }
}
