// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Tag1Consulting.Lagoon.Resources.Outputs
{

    [OutputType]
    public sealed class AutogeneratedPathRouteInput
    {
        public readonly string FromService;
        public readonly string Path;
        public readonly string ToService;

        [OutputConstructor]
        private AutogeneratedPathRouteInput(
            string fromService,

            string path,

            string toService)
        {
            FromService = fromService;
            Path = path;
            ToService = toService;
        }
    }
}
