// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Tag1Consulting.Lagoon.Resources.Outputs
{

    [OutputType]
    public sealed class RoutePathRouteInput
    {
        /// <summary>
        /// The URL path prefix to match (e.g., '/api').
        /// </summary>
        public readonly string Path;
        /// <summary>
        /// The service to route matching requests to.
        /// </summary>
        public readonly string ToService;

        [OutputConstructor]
        private RoutePathRouteInput(
            string path,

            string toService)
        {
            Path = path;
            ToService = toService;
        }
    }
}
