// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Tag1Consulting.Lagoon.Resources.Outputs
{

    [OutputType]
    public sealed class TaskArgumentInput
    {
        public readonly string DisplayName;
        public readonly string Name;
        public readonly string Type;

        [OutputConstructor]
        private TaskArgumentInput(
            string displayName,

            string name,

            string type)
        {
            DisplayName = displayName;
            Name = name;
            Type = type;
        }
    }
}
