// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Tag1Consulting.Lagoon.Resources.Outputs
{

    [OutputType]
    public sealed class TaskArgumentInput
    {
        /// <summary>
        /// The human-readable label shown in the Lagoon UI.
        /// </summary>
        public readonly string DisplayName;
        /// <summary>
        /// The argument identifier (used as the variable name).
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The argument type: STRING, ENVIRONMENT_SOURCE_NAME, or ENVIRONMENT_SOURCE_NAME_EXCLUDE_SELF.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private TaskArgumentInput(
            string displayName,

            string name,

            string type)
        {
            DisplayName = displayName;
            Name = name;
            Type = type;
        }
    }
}
