# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'AutogeneratedPathRouteInputArgs',
    'AutogeneratedPathRouteInputArgsDict',
    'RouteAnnotationInputArgs',
    'RouteAnnotationInputArgsDict',
    'RoutePathRouteInputArgs',
    'RoutePathRouteInputArgsDict',
    'TaskArgumentInputArgs',
    'TaskArgumentInputArgsDict',
]

class AutogeneratedPathRouteInputArgsDict(TypedDict):
    from_service: pulumi.Input[_builtins.str]
    path: pulumi.Input[_builtins.str]
    to_service: pulumi.Input[_builtins.str]

@pulumi.input_type
class AutogeneratedPathRouteInputArgs:
    def __init__(__self__, *,
                 from_service: pulumi.Input[_builtins.str],
                 path: pulumi.Input[_builtins.str],
                 to_service: pulumi.Input[_builtins.str]):
        pulumi.set(__self__, "from_service", from_service)
        pulumi.set(__self__, "path", path)
        pulumi.set(__self__, "to_service", to_service)

    @_builtins.property
    @pulumi.getter(name="fromService")
    def from_service(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "from_service")

    @from_service.setter
    def from_service(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "from_service", value)

    @_builtins.property
    @pulumi.getter
    def path(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "path", value)

    @_builtins.property
    @pulumi.getter(name="toService")
    def to_service(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "to_service")

    @to_service.setter
    def to_service(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "to_service", value)


class RouteAnnotationInputArgsDict(TypedDict):
    key: pulumi.Input[_builtins.str]
    value: pulumi.Input[_builtins.str]

@pulumi.input_type
class RouteAnnotationInputArgs:
    def __init__(__self__, *,
                 key: pulumi.Input[_builtins.str],
                 value: pulumi.Input[_builtins.str]):
        pulumi.set(__self__, "key", key)
        pulumi.set(__self__, "value", value)

    @_builtins.property
    @pulumi.getter
    def key(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "key")

    @key.setter
    def key(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "key", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "value", value)


class RoutePathRouteInputArgsDict(TypedDict):
    path: pulumi.Input[_builtins.str]
    to_service: pulumi.Input[_builtins.str]

@pulumi.input_type
class RoutePathRouteInputArgs:
    def __init__(__self__, *,
                 path: pulumi.Input[_builtins.str],
                 to_service: pulumi.Input[_builtins.str]):
        pulumi.set(__self__, "path", path)
        pulumi.set(__self__, "to_service", to_service)

    @_builtins.property
    @pulumi.getter
    def path(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "path", value)

    @_builtins.property
    @pulumi.getter(name="toService")
    def to_service(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "to_service")

    @to_service.setter
    def to_service(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "to_service", value)


class TaskArgumentInputArgsDict(TypedDict):
    display_name: pulumi.Input[_builtins.str]
    name: pulumi.Input[_builtins.str]
    type: pulumi.Input[_builtins.str]

@pulumi.input_type
class TaskArgumentInputArgs:
    def __init__(__self__, *,
                 display_name: pulumi.Input[_builtins.str],
                 name: pulumi.Input[_builtins.str],
                 type: pulumi.Input[_builtins.str]):
        pulumi.set(__self__, "display_name", display_name)
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "type", value)


