# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['DeployTargetConfigArgs', 'DeployTargetConfig']

@pulumi.input_type
class DeployTargetConfigArgs:
    def __init__(__self__, *,
                 deploy_target_id: pulumi.Input[_builtins.int],
                 project_id: pulumi.Input[_builtins.int],
                 branches: pulumi.Input[Optional[_builtins.str]] = None,
                 deploy_target_project_pattern: pulumi.Input[Optional[_builtins.str]] = None,
                 pullrequests: pulumi.Input[Optional[_builtins.str]] = None,
                 weight: pulumi.Input[Optional[_builtins.int]] = None):
        """
        The set of arguments for constructing a DeployTargetConfig resource.

        :param pulumi.Input[_builtins.int] deploy_target_id: The deploy target (Kubernetes cluster) ID.
        :param pulumi.Input[_builtins.int] project_id: The project ID.
        :param pulumi.Input[_builtins.str] branches: Regex pattern for branches to match.
        :param pulumi.Input[_builtins.str] deploy_target_project_pattern: Optional namespace pattern.
        :param pulumi.Input[_builtins.str] pullrequests: Whether to handle PRs ('true' or 'false').
        :param pulumi.Input[_builtins.int] weight: Priority weight (higher = more priority).
        """
        pulumi.set(__self__, "deploy_target_id", deploy_target_id)
        pulumi.set(__self__, "project_id", project_id)
        if branches is not None:
            pulumi.set(__self__, "branches", branches)
        if deploy_target_project_pattern is not None:
            pulumi.set(__self__, "deploy_target_project_pattern", deploy_target_project_pattern)
        if pullrequests is not None:
            pulumi.set(__self__, "pullrequests", pullrequests)
        if weight is not None:
            pulumi.set(__self__, "weight", weight)

    @_builtins.property
    @pulumi.getter(name="deployTargetId")
    def deploy_target_id(self) -> pulumi.Input[_builtins.int]:
        """
        The deploy target (Kubernetes cluster) ID.
        """
        return pulumi.get(self, "deploy_target_id")

    @deploy_target_id.setter
    def deploy_target_id(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "deploy_target_id", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.int]:
        """
        The project ID.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def branches(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Regex pattern for branches to match.
        """
        return pulumi.get(self, "branches")

    @branches.setter
    def branches(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "branches", value)

    @_builtins.property
    @pulumi.getter(name="deployTargetProjectPattern")
    def deploy_target_project_pattern(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional namespace pattern.
        """
        return pulumi.get(self, "deploy_target_project_pattern")

    @deploy_target_project_pattern.setter
    def deploy_target_project_pattern(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "deploy_target_project_pattern", value)

    @_builtins.property
    @pulumi.getter
    def pullrequests(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Whether to handle PRs ('true' or 'false').
        """
        return pulumi.get(self, "pullrequests")

    @pullrequests.setter
    def pullrequests(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "pullrequests", value)

    @_builtins.property
    @pulumi.getter
    def weight(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Priority weight (higher = more priority).
        """
        return pulumi.get(self, "weight")

    @weight.setter
    def weight(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "weight", value)


@pulumi.type_token("lagoon:lagoon:DeployTargetConfig")
class DeployTargetConfig(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 branches: pulumi.Input[Optional[_builtins.str]] = None,
                 deploy_target_id: pulumi.Input[Optional[_builtins.int]] = None,
                 deploy_target_project_pattern: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.int]] = None,
                 pullrequests: pulumi.Input[Optional[_builtins.str]] = None,
                 weight: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        """
        Manages a deploy target configuration to route branches/PRs to specific clusters.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] branches: Regex pattern for branches to match.
        :param pulumi.Input[_builtins.int] deploy_target_id: The deploy target (Kubernetes cluster) ID.
        :param pulumi.Input[_builtins.str] deploy_target_project_pattern: Optional namespace pattern.
        :param pulumi.Input[_builtins.int] project_id: The project ID.
        :param pulumi.Input[_builtins.str] pullrequests: Whether to handle PRs ('true' or 'false').
        :param pulumi.Input[_builtins.int] weight: Priority weight (higher = more priority).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DeployTargetConfigArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a deploy target configuration to route branches/PRs to specific clusters.


        :param str resource_name: The name of the resource.
        :param DeployTargetConfigArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DeployTargetConfigArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 branches: pulumi.Input[Optional[_builtins.str]] = None,
                 deploy_target_id: pulumi.Input[Optional[_builtins.int]] = None,
                 deploy_target_project_pattern: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.int]] = None,
                 pullrequests: pulumi.Input[Optional[_builtins.str]] = None,
                 weight: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DeployTargetConfigArgs.__new__(DeployTargetConfigArgs)

            __props__.__dict__["branches"] = branches
            if deploy_target_id is None and not opts.urn:
                raise TypeError("Missing required property 'deploy_target_id'")
            __props__.__dict__["deploy_target_id"] = deploy_target_id
            __props__.__dict__["deploy_target_project_pattern"] = deploy_target_project_pattern
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            __props__.__dict__["pullrequests"] = pullrequests
            __props__.__dict__["weight"] = weight
            __props__.__dict__["lagoon_id"] = None
        super(DeployTargetConfig, __self__).__init__(
            'lagoon:lagoon:DeployTargetConfig',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'DeployTargetConfig':
        """
        Get an existing DeployTargetConfig resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = DeployTargetConfigArgs.__new__(DeployTargetConfigArgs)

        __props__.__dict__["branches"] = None
        __props__.__dict__["deploy_target_id"] = None
        __props__.__dict__["deploy_target_project_pattern"] = None
        __props__.__dict__["lagoon_id"] = None
        __props__.__dict__["project_id"] = None
        __props__.__dict__["pullrequests"] = None
        __props__.__dict__["weight"] = None
        return DeployTargetConfig(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def branches(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Regex pattern for branches to match.
        """
        return pulumi.get(self, "branches")

    @_builtins.property
    @pulumi.getter(name="deployTargetId")
    def deploy_target_id(self) -> pulumi.Output[_builtins.int]:
        """
        The deploy target (Kubernetes cluster) ID.
        """
        return pulumi.get(self, "deploy_target_id")

    @_builtins.property
    @pulumi.getter(name="deployTargetProjectPattern")
    def deploy_target_project_pattern(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional namespace pattern.
        """
        return pulumi.get(self, "deploy_target_project_pattern")

    @_builtins.property
    @pulumi.getter(name="lagoonId")
    def lagoon_id(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "lagoon_id")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.int]:
        """
        The project ID.
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter
    def pullrequests(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Whether to handle PRs ('true' or 'false').
        """
        return pulumi.get(self, "pullrequests")

    @_builtins.property
    @pulumi.getter
    def weight(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Priority weight (higher = more priority).
        """
        return pulumi.get(self, "weight")

