# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['DeployTargetArgs', 'DeployTarget']

@pulumi.input_type
class DeployTargetArgs:
    def __init__(__self__, *,
                 console_url: pulumi.Input[_builtins.str],
                 name: pulumi.Input[_builtins.str],
                 build_image: pulumi.Input[Optional[_builtins.str]] = None,
                 cloud_provider: pulumi.Input[Optional[_builtins.str]] = None,
                 cloud_region: pulumi.Input[Optional[_builtins.str]] = None,
                 disabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 router_pattern: pulumi.Input[Optional[_builtins.str]] = None,
                 ssh_host: pulumi.Input[Optional[_builtins.str]] = None,
                 ssh_port: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a DeployTarget resource.

        :param pulumi.Input[_builtins.str] console_url: The Kubernetes API URL.
        :param pulumi.Input[_builtins.str] name: The deploy target name.
        :param pulumi.Input[_builtins.str] build_image: Custom build image.
        :param pulumi.Input[_builtins.str] cloud_provider: Cloud provider (e.g., 'kind', 'aws', 'gcp'). Defaults to 'kind'.
        :param pulumi.Input[_builtins.str] cloud_region: Cloud region (e.g., 'us-east-1', 'local'). Defaults to 'local'.
        :param pulumi.Input[_builtins.bool] disabled: Whether the deploy target is disabled.
        :param pulumi.Input[_builtins.str] router_pattern: Router pattern for the deploy target.
        :param pulumi.Input[_builtins.str] ssh_host: SSH host for builds.
        :param pulumi.Input[_builtins.str] ssh_port: SSH port for builds.
        """
        pulumi.set(__self__, "console_url", console_url)
        pulumi.set(__self__, "name", name)
        if build_image is not None:
            pulumi.set(__self__, "build_image", build_image)
        if cloud_provider is not None:
            pulumi.set(__self__, "cloud_provider", cloud_provider)
        if cloud_region is not None:
            pulumi.set(__self__, "cloud_region", cloud_region)
        if disabled is not None:
            pulumi.set(__self__, "disabled", disabled)
        if router_pattern is not None:
            pulumi.set(__self__, "router_pattern", router_pattern)
        if ssh_host is not None:
            pulumi.set(__self__, "ssh_host", ssh_host)
        if ssh_port is not None:
            pulumi.set(__self__, "ssh_port", ssh_port)

    @_builtins.property
    @pulumi.getter(name="consoleUrl")
    def console_url(self) -> pulumi.Input[_builtins.str]:
        """
        The Kubernetes API URL.
        """
        return pulumi.get(self, "console_url")

    @console_url.setter
    def console_url(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "console_url", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The deploy target name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="buildImage")
    def build_image(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Custom build image.
        """
        return pulumi.get(self, "build_image")

    @build_image.setter
    def build_image(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "build_image", value)

    @_builtins.property
    @pulumi.getter(name="cloudProvider")
    def cloud_provider(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Cloud provider (e.g., 'kind', 'aws', 'gcp'). Defaults to 'kind'.
        """
        return pulumi.get(self, "cloud_provider")

    @cloud_provider.setter
    def cloud_provider(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "cloud_provider", value)

    @_builtins.property
    @pulumi.getter(name="cloudRegion")
    def cloud_region(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Cloud region (e.g., 'us-east-1', 'local'). Defaults to 'local'.
        """
        return pulumi.get(self, "cloud_region")

    @cloud_region.setter
    def cloud_region(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "cloud_region", value)

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the deploy target is disabled.
        """
        return pulumi.get(self, "disabled")

    @disabled.setter
    def disabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "disabled", value)

    @_builtins.property
    @pulumi.getter(name="routerPattern")
    def router_pattern(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Router pattern for the deploy target.
        """
        return pulumi.get(self, "router_pattern")

    @router_pattern.setter
    def router_pattern(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "router_pattern", value)

    @_builtins.property
    @pulumi.getter(name="sshHost")
    def ssh_host(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        SSH host for builds.
        """
        return pulumi.get(self, "ssh_host")

    @ssh_host.setter
    def ssh_host(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ssh_host", value)

    @_builtins.property
    @pulumi.getter(name="sshPort")
    def ssh_port(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        SSH port for builds.
        """
        return pulumi.get(self, "ssh_port")

    @ssh_port.setter
    def ssh_port(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ssh_port", value)


@pulumi.type_token("lagoon:lagoon:DeployTarget")
class DeployTarget(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 build_image: pulumi.Input[Optional[_builtins.str]] = None,
                 cloud_provider: pulumi.Input[Optional[_builtins.str]] = None,
                 cloud_region: pulumi.Input[Optional[_builtins.str]] = None,
                 console_url: pulumi.Input[Optional[_builtins.str]] = None,
                 disabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 router_pattern: pulumi.Input[Optional[_builtins.str]] = None,
                 ssh_host: pulumi.Input[Optional[_builtins.str]] = None,
                 ssh_port: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Manages a Lagoon Kubernetes deploy target (cluster).


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] build_image: Custom build image.
        :param pulumi.Input[_builtins.str] cloud_provider: Cloud provider (e.g., 'kind', 'aws', 'gcp'). Defaults to 'kind'.
        :param pulumi.Input[_builtins.str] cloud_region: Cloud region (e.g., 'us-east-1', 'local'). Defaults to 'local'.
        :param pulumi.Input[_builtins.str] console_url: The Kubernetes API URL.
        :param pulumi.Input[_builtins.bool] disabled: Whether the deploy target is disabled.
        :param pulumi.Input[_builtins.str] name: The deploy target name.
        :param pulumi.Input[_builtins.str] router_pattern: Router pattern for the deploy target.
        :param pulumi.Input[_builtins.str] ssh_host: SSH host for builds.
        :param pulumi.Input[_builtins.str] ssh_port: SSH port for builds.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: DeployTargetArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a Lagoon Kubernetes deploy target (cluster).


        :param str resource_name: The name of the resource.
        :param DeployTargetArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DeployTargetArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 build_image: pulumi.Input[Optional[_builtins.str]] = None,
                 cloud_provider: pulumi.Input[Optional[_builtins.str]] = None,
                 cloud_region: pulumi.Input[Optional[_builtins.str]] = None,
                 console_url: pulumi.Input[Optional[_builtins.str]] = None,
                 disabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 router_pattern: pulumi.Input[Optional[_builtins.str]] = None,
                 ssh_host: pulumi.Input[Optional[_builtins.str]] = None,
                 ssh_port: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DeployTargetArgs.__new__(DeployTargetArgs)

            __props__.__dict__["build_image"] = build_image
            __props__.__dict__["cloud_provider"] = cloud_provider
            __props__.__dict__["cloud_region"] = cloud_region
            if console_url is None and not opts.urn:
                raise TypeError("Missing required property 'console_url'")
            __props__.__dict__["console_url"] = console_url
            __props__.__dict__["disabled"] = disabled
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["router_pattern"] = router_pattern
            __props__.__dict__["ssh_host"] = ssh_host
            __props__.__dict__["ssh_port"] = ssh_port
            __props__.__dict__["created"] = None
            __props__.__dict__["lagoon_id"] = None
        super(DeployTarget, __self__).__init__(
            'lagoon:lagoon:DeployTarget',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'DeployTarget':
        """
        Get an existing DeployTarget resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = DeployTargetArgs.__new__(DeployTargetArgs)

        __props__.__dict__["build_image"] = None
        __props__.__dict__["cloud_provider"] = None
        __props__.__dict__["cloud_region"] = None
        __props__.__dict__["console_url"] = None
        __props__.__dict__["created"] = None
        __props__.__dict__["disabled"] = None
        __props__.__dict__["lagoon_id"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["router_pattern"] = None
        __props__.__dict__["ssh_host"] = None
        __props__.__dict__["ssh_port"] = None
        return DeployTarget(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="buildImage")
    def build_image(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Custom build image.
        """
        return pulumi.get(self, "build_image")

    @_builtins.property
    @pulumi.getter(name="cloudProvider")
    def cloud_provider(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Cloud provider (e.g., 'kind', 'aws', 'gcp'). Defaults to 'kind'.
        """
        return pulumi.get(self, "cloud_provider")

    @_builtins.property
    @pulumi.getter(name="cloudRegion")
    def cloud_region(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Cloud region (e.g., 'us-east-1', 'local'). Defaults to 'local'.
        """
        return pulumi.get(self, "cloud_region")

    @_builtins.property
    @pulumi.getter(name="consoleUrl")
    def console_url(self) -> pulumi.Output[_builtins.str]:
        """
        The Kubernetes API URL.
        """
        return pulumi.get(self, "console_url")

    @_builtins.property
    @pulumi.getter
    def created(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the deploy target is disabled.
        """
        return pulumi.get(self, "disabled")

    @_builtins.property
    @pulumi.getter(name="lagoonId")
    def lagoon_id(self) -> pulumi.Output[_builtins.int]:
        return pulumi.get(self, "lagoon_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The deploy target name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="routerPattern")
    def router_pattern(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Router pattern for the deploy target.
        """
        return pulumi.get(self, "router_pattern")

    @_builtins.property
    @pulumi.getter(name="sshHost")
    def ssh_host(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        SSH host for builds.
        """
        return pulumi.get(self, "ssh_host")

    @_builtins.property
    @pulumi.getter(name="sshPort")
    def ssh_port(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        SSH port for builds.
        """
        return pulumi.get(self, "ssh_port")

