# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['ProjectArgs', 'Project']

@pulumi.input_type
class ProjectArgs:
    def __init__(__self__, *,
                 deploytarget_id: pulumi.Input[_builtins.int],
                 git_url: pulumi.Input[_builtins.str],
                 name: pulumi.Input[_builtins.str],
                 auto_idle: pulumi.Input[Optional[_builtins.int]] = None,
                 branches: pulumi.Input[Optional[_builtins.str]] = None,
                 openshift_project_pattern: pulumi.Input[Optional[_builtins.str]] = None,
                 production_environment: pulumi.Input[Optional[_builtins.str]] = None,
                 pullrequests: pulumi.Input[Optional[_builtins.str]] = None,
                 storage_calc: pulumi.Input[Optional[_builtins.int]] = None):
        """
        The set of arguments for constructing a Project resource.

        :param pulumi.Input[_builtins.int] deploytarget_id: The deploy target (Kubernetes cluster) ID.
        :param pulumi.Input[_builtins.str] git_url: The Git repository URL (SSH or HTTPS format).
        :param pulumi.Input[_builtins.str] name: The project name. Must be unique, lowercase alphanumeric with hyphens.
        :param pulumi.Input[_builtins.int] auto_idle: Whether to auto-idle environments (1=yes, 0=no).
        :param pulumi.Input[_builtins.str] branches: Regex pattern for branches to deploy.
        :param pulumi.Input[_builtins.str] openshift_project_pattern: Namespace pattern for the project on the cluster.
        :param pulumi.Input[_builtins.str] production_environment: Name of the production branch/environment.
        :param pulumi.Input[_builtins.str] pullrequests: Regex pattern for pull requests to deploy.
        :param pulumi.Input[_builtins.int] storage_calc: Whether to calculate storage (1=yes, 0=no).
        """
        pulumi.set(__self__, "deploytarget_id", deploytarget_id)
        pulumi.set(__self__, "git_url", git_url)
        pulumi.set(__self__, "name", name)
        if auto_idle is not None:
            pulumi.set(__self__, "auto_idle", auto_idle)
        if branches is not None:
            pulumi.set(__self__, "branches", branches)
        if openshift_project_pattern is not None:
            pulumi.set(__self__, "openshift_project_pattern", openshift_project_pattern)
        if production_environment is not None:
            pulumi.set(__self__, "production_environment", production_environment)
        if pullrequests is not None:
            pulumi.set(__self__, "pullrequests", pullrequests)
        if storage_calc is not None:
            pulumi.set(__self__, "storage_calc", storage_calc)

    @_builtins.property
    @pulumi.getter(name="deploytargetId")
    def deploytarget_id(self) -> pulumi.Input[_builtins.int]:
        """
        The deploy target (Kubernetes cluster) ID.
        """
        return pulumi.get(self, "deploytarget_id")

    @deploytarget_id.setter
    def deploytarget_id(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "deploytarget_id", value)

    @_builtins.property
    @pulumi.getter(name="gitUrl")
    def git_url(self) -> pulumi.Input[_builtins.str]:
        """
        The Git repository URL (SSH or HTTPS format).
        """
        return pulumi.get(self, "git_url")

    @git_url.setter
    def git_url(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "git_url", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The project name. Must be unique, lowercase alphanumeric with hyphens.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="autoIdle")
    def auto_idle(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Whether to auto-idle environments (1=yes, 0=no).
        """
        return pulumi.get(self, "auto_idle")

    @auto_idle.setter
    def auto_idle(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "auto_idle", value)

    @_builtins.property
    @pulumi.getter
    def branches(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Regex pattern for branches to deploy.
        """
        return pulumi.get(self, "branches")

    @branches.setter
    def branches(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "branches", value)

    @_builtins.property
    @pulumi.getter(name="openshiftProjectPattern")
    def openshift_project_pattern(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Namespace pattern for the project on the cluster.
        """
        return pulumi.get(self, "openshift_project_pattern")

    @openshift_project_pattern.setter
    def openshift_project_pattern(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "openshift_project_pattern", value)

    @_builtins.property
    @pulumi.getter(name="productionEnvironment")
    def production_environment(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Name of the production branch/environment.
        """
        return pulumi.get(self, "production_environment")

    @production_environment.setter
    def production_environment(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "production_environment", value)

    @_builtins.property
    @pulumi.getter
    def pullrequests(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Regex pattern for pull requests to deploy.
        """
        return pulumi.get(self, "pullrequests")

    @pullrequests.setter
    def pullrequests(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "pullrequests", value)

    @_builtins.property
    @pulumi.getter(name="storageCalc")
    def storage_calc(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Whether to calculate storage (1=yes, 0=no).
        """
        return pulumi.get(self, "storage_calc")

    @storage_calc.setter
    def storage_calc(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "storage_calc", value)


@pulumi.type_token("lagoon:lagoon:Project")
class Project(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auto_idle: pulumi.Input[Optional[_builtins.int]] = None,
                 branches: pulumi.Input[Optional[_builtins.str]] = None,
                 deploytarget_id: pulumi.Input[Optional[_builtins.int]] = None,
                 git_url: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 openshift_project_pattern: pulumi.Input[Optional[_builtins.str]] = None,
                 production_environment: pulumi.Input[Optional[_builtins.str]] = None,
                 pullrequests: pulumi.Input[Optional[_builtins.str]] = None,
                 storage_calc: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        """
        Manages a Lagoon project (application/site).


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] auto_idle: Whether to auto-idle environments (1=yes, 0=no).
        :param pulumi.Input[_builtins.str] branches: Regex pattern for branches to deploy.
        :param pulumi.Input[_builtins.int] deploytarget_id: The deploy target (Kubernetes cluster) ID.
        :param pulumi.Input[_builtins.str] git_url: The Git repository URL (SSH or HTTPS format).
        :param pulumi.Input[_builtins.str] name: The project name. Must be unique, lowercase alphanumeric with hyphens.
        :param pulumi.Input[_builtins.str] openshift_project_pattern: Namespace pattern for the project on the cluster.
        :param pulumi.Input[_builtins.str] production_environment: Name of the production branch/environment.
        :param pulumi.Input[_builtins.str] pullrequests: Regex pattern for pull requests to deploy.
        :param pulumi.Input[_builtins.int] storage_calc: Whether to calculate storage (1=yes, 0=no).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ProjectArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a Lagoon project (application/site).


        :param str resource_name: The name of the resource.
        :param ProjectArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ProjectArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 auto_idle: pulumi.Input[Optional[_builtins.int]] = None,
                 branches: pulumi.Input[Optional[_builtins.str]] = None,
                 deploytarget_id: pulumi.Input[Optional[_builtins.int]] = None,
                 git_url: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 openshift_project_pattern: pulumi.Input[Optional[_builtins.str]] = None,
                 production_environment: pulumi.Input[Optional[_builtins.str]] = None,
                 pullrequests: pulumi.Input[Optional[_builtins.str]] = None,
                 storage_calc: pulumi.Input[Optional[_builtins.int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ProjectArgs.__new__(ProjectArgs)

            __props__.__dict__["auto_idle"] = auto_idle
            __props__.__dict__["branches"] = branches
            if deploytarget_id is None and not opts.urn:
                raise TypeError("Missing required property 'deploytarget_id'")
            __props__.__dict__["deploytarget_id"] = deploytarget_id
            if git_url is None and not opts.urn:
                raise TypeError("Missing required property 'git_url'")
            __props__.__dict__["git_url"] = git_url
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["openshift_project_pattern"] = openshift_project_pattern
            __props__.__dict__["production_environment"] = production_environment
            __props__.__dict__["pullrequests"] = pullrequests
            __props__.__dict__["storage_calc"] = storage_calc
            __props__.__dict__["created"] = None
            __props__.__dict__["lagoon_id"] = None
        super(Project, __self__).__init__(
            'lagoon:lagoon:Project',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Project':
        """
        Get an existing Project resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ProjectArgs.__new__(ProjectArgs)

        __props__.__dict__["auto_idle"] = None
        __props__.__dict__["branches"] = None
        __props__.__dict__["created"] = None
        __props__.__dict__["deploytarget_id"] = None
        __props__.__dict__["git_url"] = None
        __props__.__dict__["lagoon_id"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["openshift_project_pattern"] = None
        __props__.__dict__["production_environment"] = None
        __props__.__dict__["pullrequests"] = None
        __props__.__dict__["storage_calc"] = None
        return Project(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="autoIdle")
    def auto_idle(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Whether to auto-idle environments (1=yes, 0=no).
        """
        return pulumi.get(self, "auto_idle")

    @_builtins.property
    @pulumi.getter
    def branches(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Regex pattern for branches to deploy.
        """
        return pulumi.get(self, "branches")

    @_builtins.property
    @pulumi.getter
    def created(self) -> pulumi.Output[_builtins.str]:
        """
        The creation timestamp of the project.
        """
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter(name="deploytargetId")
    def deploytarget_id(self) -> pulumi.Output[_builtins.int]:
        """
        The deploy target (Kubernetes cluster) ID.
        """
        return pulumi.get(self, "deploytarget_id")

    @_builtins.property
    @pulumi.getter(name="gitUrl")
    def git_url(self) -> pulumi.Output[_builtins.str]:
        """
        The Git repository URL (SSH or HTTPS format).
        """
        return pulumi.get(self, "git_url")

    @_builtins.property
    @pulumi.getter(name="lagoonId")
    def lagoon_id(self) -> pulumi.Output[_builtins.int]:
        """
        The Lagoon-assigned numeric ID of the project.
        """
        return pulumi.get(self, "lagoon_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The project name. Must be unique, lowercase alphanumeric with hyphens.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="openshiftProjectPattern")
    def openshift_project_pattern(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Namespace pattern for the project on the cluster.
        """
        return pulumi.get(self, "openshift_project_pattern")

    @_builtins.property
    @pulumi.getter(name="productionEnvironment")
    def production_environment(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Name of the production branch/environment.
        """
        return pulumi.get(self, "production_environment")

    @_builtins.property
    @pulumi.getter
    def pullrequests(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Regex pattern for pull requests to deploy.
        """
        return pulumi.get(self, "pullrequests")

    @_builtins.property
    @pulumi.getter(name="storageCalc")
    def storage_calc(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Whether to calculate storage (1=yes, 0=no).
        """
        return pulumi.get(self, "storage_calc")

