# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from .. import resources as _resources

__all__ = ['RouteArgs', 'Route']

@pulumi.input_type
class RouteArgs:
    def __init__(__self__, *,
                 domain: pulumi.Input[_builtins.str],
                 project_name: pulumi.Input[_builtins.str],
                 alternative_names: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 annotations: pulumi.Input[Optional[Sequence[pulumi.Input['_resources.RouteAnnotationInputArgs']]]] = None,
                 disable_request_verification: pulumi.Input[Optional[_builtins.bool]] = None,
                 environment: pulumi.Input[Optional[_builtins.str]] = None,
                 hsts_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 hsts_include_subdomains: pulumi.Input[Optional[_builtins.bool]] = None,
                 hsts_max_age: pulumi.Input[Optional[_builtins.int]] = None,
                 hsts_preload: pulumi.Input[Optional[_builtins.bool]] = None,
                 insecure: pulumi.Input[Optional[_builtins.str]] = None,
                 monitoring_path: pulumi.Input[Optional[_builtins.str]] = None,
                 path_routes: pulumi.Input[Optional[Sequence[pulumi.Input['_resources.RoutePathRouteInputArgs']]]] = None,
                 primary: pulumi.Input[Optional[_builtins.bool]] = None,
                 route_type: pulumi.Input[Optional[_builtins.str]] = None,
                 service: pulumi.Input[Optional[_builtins.str]] = None,
                 tls_acme: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a Route resource.

        :param pulumi.Input[_builtins.str] domain: The primary domain for the route (e.g., 'example.com'). Changing this forces replacement.
        :param pulumi.Input[_builtins.str] project_name: The Lagoon project name this route belongs to.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] alternative_names: Additional SAN domains for the TLS certificate (max 25).
        :param pulumi.Input[Sequence[pulumi.Input['_resources.RouteAnnotationInputArgs']]] annotations: Ingress annotations (key/value pairs, max 10).
        :param pulumi.Input[_builtins.bool] disable_request_verification: Whether to disable request verification.
        :param pulumi.Input[_builtins.str] environment: The environment to attach this route to.
        :param pulumi.Input[_builtins.bool] hsts_enabled: Whether to enable HTTP Strict Transport Security.
        :param pulumi.Input[_builtins.bool] hsts_include_subdomains: Whether to include subdomains in HSTS.
        :param pulumi.Input[_builtins.int] hsts_max_age: HSTS max-age in seconds.
        :param pulumi.Input[_builtins.bool] hsts_preload: Whether to include the preload directive in HSTS.
        :param pulumi.Input[_builtins.str] insecure: How to handle insecure (HTTP) traffic: Allow, Redirect, or None. Defaults to Redirect.
        :param pulumi.Input[_builtins.str] monitoring_path: Path to use for uptime monitoring.
        :param pulumi.Input[Sequence[pulumi.Input['_resources.RoutePathRouteInputArgs']]] path_routes: Path-based routing rules (max 10).
        :param pulumi.Input[_builtins.bool] primary: Whether this is the primary route.
        :param pulumi.Input[_builtins.str] route_type: Route type for active/standby: STANDARD, ACTIVE, or STANDBY.
        :param pulumi.Input[_builtins.str] service: The service to route traffic to (e.g., 'nginx').
        :param pulumi.Input[_builtins.bool] tls_acme: Whether to use Let's Encrypt for TLS. Defaults to true.
        """
        pulumi.set(__self__, "domain", domain)
        pulumi.set(__self__, "project_name", project_name)
        if alternative_names is not None:
            pulumi.set(__self__, "alternative_names", alternative_names)
        if annotations is not None:
            pulumi.set(__self__, "annotations", annotations)
        if disable_request_verification is not None:
            pulumi.set(__self__, "disable_request_verification", disable_request_verification)
        if environment is not None:
            pulumi.set(__self__, "environment", environment)
        if hsts_enabled is not None:
            pulumi.set(__self__, "hsts_enabled", hsts_enabled)
        if hsts_include_subdomains is not None:
            pulumi.set(__self__, "hsts_include_subdomains", hsts_include_subdomains)
        if hsts_max_age is not None:
            pulumi.set(__self__, "hsts_max_age", hsts_max_age)
        if hsts_preload is not None:
            pulumi.set(__self__, "hsts_preload", hsts_preload)
        if insecure is not None:
            pulumi.set(__self__, "insecure", insecure)
        if monitoring_path is not None:
            pulumi.set(__self__, "monitoring_path", monitoring_path)
        if path_routes is not None:
            pulumi.set(__self__, "path_routes", path_routes)
        if primary is not None:
            pulumi.set(__self__, "primary", primary)
        if route_type is not None:
            pulumi.set(__self__, "route_type", route_type)
        if service is not None:
            pulumi.set(__self__, "service", service)
        if tls_acme is not None:
            pulumi.set(__self__, "tls_acme", tls_acme)

    @_builtins.property
    @pulumi.getter
    def domain(self) -> pulumi.Input[_builtins.str]:
        """
        The primary domain for the route (e.g., 'example.com'). Changing this forces replacement.
        """
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "domain", value)

    @_builtins.property
    @pulumi.getter(name="projectName")
    def project_name(self) -> pulumi.Input[_builtins.str]:
        """
        The Lagoon project name this route belongs to.
        """
        return pulumi.get(self, "project_name")

    @project_name.setter
    def project_name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "project_name", value)

    @_builtins.property
    @pulumi.getter(name="alternativeNames")
    def alternative_names(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        Additional SAN domains for the TLS certificate (max 25).
        """
        return pulumi.get(self, "alternative_names")

    @alternative_names.setter
    def alternative_names(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "alternative_names", value)

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['_resources.RouteAnnotationInputArgs']]]]:
        """
        Ingress annotations (key/value pairs, max 10).
        """
        return pulumi.get(self, "annotations")

    @annotations.setter
    def annotations(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['_resources.RouteAnnotationInputArgs']]]]):
        pulumi.set(self, "annotations", value)

    @_builtins.property
    @pulumi.getter(name="disableRequestVerification")
    def disable_request_verification(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to disable request verification.
        """
        return pulumi.get(self, "disable_request_verification")

    @disable_request_verification.setter
    def disable_request_verification(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "disable_request_verification", value)

    @_builtins.property
    @pulumi.getter
    def environment(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The environment to attach this route to.
        """
        return pulumi.get(self, "environment")

    @environment.setter
    def environment(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "environment", value)

    @_builtins.property
    @pulumi.getter(name="hstsEnabled")
    def hsts_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to enable HTTP Strict Transport Security.
        """
        return pulumi.get(self, "hsts_enabled")

    @hsts_enabled.setter
    def hsts_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "hsts_enabled", value)

    @_builtins.property
    @pulumi.getter(name="hstsIncludeSubdomains")
    def hsts_include_subdomains(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to include subdomains in HSTS.
        """
        return pulumi.get(self, "hsts_include_subdomains")

    @hsts_include_subdomains.setter
    def hsts_include_subdomains(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "hsts_include_subdomains", value)

    @_builtins.property
    @pulumi.getter(name="hstsMaxAge")
    def hsts_max_age(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        HSTS max-age in seconds.
        """
        return pulumi.get(self, "hsts_max_age")

    @hsts_max_age.setter
    def hsts_max_age(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "hsts_max_age", value)

    @_builtins.property
    @pulumi.getter(name="hstsPreload")
    def hsts_preload(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to include the preload directive in HSTS.
        """
        return pulumi.get(self, "hsts_preload")

    @hsts_preload.setter
    def hsts_preload(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "hsts_preload", value)

    @_builtins.property
    @pulumi.getter
    def insecure(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        How to handle insecure (HTTP) traffic: Allow, Redirect, or None. Defaults to Redirect.
        """
        return pulumi.get(self, "insecure")

    @insecure.setter
    def insecure(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "insecure", value)

    @_builtins.property
    @pulumi.getter(name="monitoringPath")
    def monitoring_path(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Path to use for uptime monitoring.
        """
        return pulumi.get(self, "monitoring_path")

    @monitoring_path.setter
    def monitoring_path(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "monitoring_path", value)

    @_builtins.property
    @pulumi.getter(name="pathRoutes")
    def path_routes(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['_resources.RoutePathRouteInputArgs']]]]:
        """
        Path-based routing rules (max 10).
        """
        return pulumi.get(self, "path_routes")

    @path_routes.setter
    def path_routes(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['_resources.RoutePathRouteInputArgs']]]]):
        pulumi.set(self, "path_routes", value)

    @_builtins.property
    @pulumi.getter
    def primary(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether this is the primary route.
        """
        return pulumi.get(self, "primary")

    @primary.setter
    def primary(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "primary", value)

    @_builtins.property
    @pulumi.getter(name="routeType")
    def route_type(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Route type for active/standby: STANDARD, ACTIVE, or STANDBY.
        """
        return pulumi.get(self, "route_type")

    @route_type.setter
    def route_type(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "route_type", value)

    @_builtins.property
    @pulumi.getter
    def service(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The service to route traffic to (e.g., 'nginx').
        """
        return pulumi.get(self, "service")

    @service.setter
    def service(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "service", value)

    @_builtins.property
    @pulumi.getter(name="tlsAcme")
    def tls_acme(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to use Let's Encrypt for TLS. Defaults to true.
        """
        return pulumi.get(self, "tls_acme")

    @tls_acme.setter
    def tls_acme(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "tls_acme", value)


@pulumi.type_token("lagoon:lagoon:Route")
class Route(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 alternative_names: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 annotations: pulumi.Input[Optional[Sequence[pulumi.Input[Union['_resources.RouteAnnotationInputArgs', '_resources.RouteAnnotationInputArgsDict']]]]] = None,
                 disable_request_verification: pulumi.Input[Optional[_builtins.bool]] = None,
                 domain: pulumi.Input[Optional[_builtins.str]] = None,
                 environment: pulumi.Input[Optional[_builtins.str]] = None,
                 hsts_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 hsts_include_subdomains: pulumi.Input[Optional[_builtins.bool]] = None,
                 hsts_max_age: pulumi.Input[Optional[_builtins.int]] = None,
                 hsts_preload: pulumi.Input[Optional[_builtins.bool]] = None,
                 insecure: pulumi.Input[Optional[_builtins.str]] = None,
                 monitoring_path: pulumi.Input[Optional[_builtins.str]] = None,
                 path_routes: pulumi.Input[Optional[Sequence[pulumi.Input[Union['_resources.RoutePathRouteInputArgs', '_resources.RoutePathRouteInputArgsDict']]]]] = None,
                 primary: pulumi.Input[Optional[_builtins.bool]] = None,
                 project_name: pulumi.Input[Optional[_builtins.str]] = None,
                 route_type: pulumi.Input[Optional[_builtins.str]] = None,
                 service: pulumi.Input[Optional[_builtins.str]] = None,
                 tls_acme: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        Manages a Lagoon API-defined route on a project (requires Lagoon v2.29.0+).


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] alternative_names: Additional SAN domains for the TLS certificate (max 25).
        :param pulumi.Input[Sequence[pulumi.Input[Union['_resources.RouteAnnotationInputArgs', '_resources.RouteAnnotationInputArgsDict']]]] annotations: Ingress annotations (key/value pairs, max 10).
        :param pulumi.Input[_builtins.bool] disable_request_verification: Whether to disable request verification.
        :param pulumi.Input[_builtins.str] domain: The primary domain for the route (e.g., 'example.com'). Changing this forces replacement.
        :param pulumi.Input[_builtins.str] environment: The environment to attach this route to.
        :param pulumi.Input[_builtins.bool] hsts_enabled: Whether to enable HTTP Strict Transport Security.
        :param pulumi.Input[_builtins.bool] hsts_include_subdomains: Whether to include subdomains in HSTS.
        :param pulumi.Input[_builtins.int] hsts_max_age: HSTS max-age in seconds.
        :param pulumi.Input[_builtins.bool] hsts_preload: Whether to include the preload directive in HSTS.
        :param pulumi.Input[_builtins.str] insecure: How to handle insecure (HTTP) traffic: Allow, Redirect, or None. Defaults to Redirect.
        :param pulumi.Input[_builtins.str] monitoring_path: Path to use for uptime monitoring.
        :param pulumi.Input[Sequence[pulumi.Input[Union['_resources.RoutePathRouteInputArgs', '_resources.RoutePathRouteInputArgsDict']]]] path_routes: Path-based routing rules (max 10).
        :param pulumi.Input[_builtins.bool] primary: Whether this is the primary route.
        :param pulumi.Input[_builtins.str] project_name: The Lagoon project name this route belongs to.
        :param pulumi.Input[_builtins.str] route_type: Route type for active/standby: STANDARD, ACTIVE, or STANDBY.
        :param pulumi.Input[_builtins.str] service: The service to route traffic to (e.g., 'nginx').
        :param pulumi.Input[_builtins.bool] tls_acme: Whether to use Let's Encrypt for TLS. Defaults to true.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: RouteArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a Lagoon API-defined route on a project (requires Lagoon v2.29.0+).


        :param str resource_name: The name of the resource.
        :param RouteArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(RouteArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 alternative_names: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 annotations: pulumi.Input[Optional[Sequence[pulumi.Input[Union['_resources.RouteAnnotationInputArgs', '_resources.RouteAnnotationInputArgsDict']]]]] = None,
                 disable_request_verification: pulumi.Input[Optional[_builtins.bool]] = None,
                 domain: pulumi.Input[Optional[_builtins.str]] = None,
                 environment: pulumi.Input[Optional[_builtins.str]] = None,
                 hsts_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 hsts_include_subdomains: pulumi.Input[Optional[_builtins.bool]] = None,
                 hsts_max_age: pulumi.Input[Optional[_builtins.int]] = None,
                 hsts_preload: pulumi.Input[Optional[_builtins.bool]] = None,
                 insecure: pulumi.Input[Optional[_builtins.str]] = None,
                 monitoring_path: pulumi.Input[Optional[_builtins.str]] = None,
                 path_routes: pulumi.Input[Optional[Sequence[pulumi.Input[Union['_resources.RoutePathRouteInputArgs', '_resources.RoutePathRouteInputArgsDict']]]]] = None,
                 primary: pulumi.Input[Optional[_builtins.bool]] = None,
                 project_name: pulumi.Input[Optional[_builtins.str]] = None,
                 route_type: pulumi.Input[Optional[_builtins.str]] = None,
                 service: pulumi.Input[Optional[_builtins.str]] = None,
                 tls_acme: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = RouteArgs.__new__(RouteArgs)

            __props__.__dict__["alternative_names"] = alternative_names
            __props__.__dict__["annotations"] = annotations
            __props__.__dict__["disable_request_verification"] = disable_request_verification
            if domain is None and not opts.urn:
                raise TypeError("Missing required property 'domain'")
            __props__.__dict__["domain"] = domain
            __props__.__dict__["environment"] = environment
            __props__.__dict__["hsts_enabled"] = hsts_enabled
            __props__.__dict__["hsts_include_subdomains"] = hsts_include_subdomains
            __props__.__dict__["hsts_max_age"] = hsts_max_age
            __props__.__dict__["hsts_preload"] = hsts_preload
            __props__.__dict__["insecure"] = insecure
            __props__.__dict__["monitoring_path"] = monitoring_path
            __props__.__dict__["path_routes"] = path_routes
            __props__.__dict__["primary"] = primary
            if project_name is None and not opts.urn:
                raise TypeError("Missing required property 'project_name'")
            __props__.__dict__["project_name"] = project_name
            __props__.__dict__["route_type"] = route_type
            __props__.__dict__["service"] = service
            __props__.__dict__["tls_acme"] = tls_acme
            __props__.__dict__["created"] = None
            __props__.__dict__["lagoon_id"] = None
            __props__.__dict__["source"] = None
            __props__.__dict__["updated"] = None
        super(Route, __self__).__init__(
            'lagoon:lagoon:Route',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Route':
        """
        Get an existing Route resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = RouteArgs.__new__(RouteArgs)

        __props__.__dict__["alternative_names"] = None
        __props__.__dict__["annotations"] = None
        __props__.__dict__["created"] = None
        __props__.__dict__["disable_request_verification"] = None
        __props__.__dict__["domain"] = None
        __props__.__dict__["environment"] = None
        __props__.__dict__["hsts_enabled"] = None
        __props__.__dict__["hsts_include_subdomains"] = None
        __props__.__dict__["hsts_max_age"] = None
        __props__.__dict__["hsts_preload"] = None
        __props__.__dict__["insecure"] = None
        __props__.__dict__["lagoon_id"] = None
        __props__.__dict__["monitoring_path"] = None
        __props__.__dict__["path_routes"] = None
        __props__.__dict__["primary"] = None
        __props__.__dict__["project_name"] = None
        __props__.__dict__["route_type"] = None
        __props__.__dict__["service"] = None
        __props__.__dict__["source"] = None
        __props__.__dict__["tls_acme"] = None
        __props__.__dict__["updated"] = None
        return Route(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="alternativeNames")
    def alternative_names(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        Additional SAN domains for the TLS certificate (max 25).
        """
        return pulumi.get(self, "alternative_names")

    @_builtins.property
    @pulumi.getter
    def annotations(self) -> pulumi.Output[Optional[Sequence['_resources.outputs.RouteAnnotationInput']]]:
        """
        Ingress annotations (key/value pairs, max 10).
        """
        return pulumi.get(self, "annotations")

    @_builtins.property
    @pulumi.getter
    def created(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp when the route was created.
        """
        return pulumi.get(self, "created")

    @_builtins.property
    @pulumi.getter(name="disableRequestVerification")
    def disable_request_verification(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to disable request verification.
        """
        return pulumi.get(self, "disable_request_verification")

    @_builtins.property
    @pulumi.getter
    def domain(self) -> pulumi.Output[_builtins.str]:
        """
        The primary domain for the route (e.g., 'example.com'). Changing this forces replacement.
        """
        return pulumi.get(self, "domain")

    @_builtins.property
    @pulumi.getter
    def environment(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The environment to attach this route to.
        """
        return pulumi.get(self, "environment")

    @_builtins.property
    @pulumi.getter(name="hstsEnabled")
    def hsts_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to enable HTTP Strict Transport Security.
        """
        return pulumi.get(self, "hsts_enabled")

    @_builtins.property
    @pulumi.getter(name="hstsIncludeSubdomains")
    def hsts_include_subdomains(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to include subdomains in HSTS.
        """
        return pulumi.get(self, "hsts_include_subdomains")

    @_builtins.property
    @pulumi.getter(name="hstsMaxAge")
    def hsts_max_age(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        HSTS max-age in seconds.
        """
        return pulumi.get(self, "hsts_max_age")

    @_builtins.property
    @pulumi.getter(name="hstsPreload")
    def hsts_preload(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to include the preload directive in HSTS.
        """
        return pulumi.get(self, "hsts_preload")

    @_builtins.property
    @pulumi.getter
    def insecure(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        How to handle insecure (HTTP) traffic: Allow, Redirect, or None. Defaults to Redirect.
        """
        return pulumi.get(self, "insecure")

    @_builtins.property
    @pulumi.getter(name="lagoonId")
    def lagoon_id(self) -> pulumi.Output[_builtins.int]:
        """
        The Lagoon-assigned numeric route ID.
        """
        return pulumi.get(self, "lagoon_id")

    @_builtins.property
    @pulumi.getter(name="monitoringPath")
    def monitoring_path(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Path to use for uptime monitoring.
        """
        return pulumi.get(self, "monitoring_path")

    @_builtins.property
    @pulumi.getter(name="pathRoutes")
    def path_routes(self) -> pulumi.Output[Optional[Sequence['_resources.outputs.RoutePathRouteInput']]]:
        """
        Path-based routing rules (max 10).
        """
        return pulumi.get(self, "path_routes")

    @_builtins.property
    @pulumi.getter
    def primary(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether this is the primary route.
        """
        return pulumi.get(self, "primary")

    @_builtins.property
    @pulumi.getter(name="projectName")
    def project_name(self) -> pulumi.Output[_builtins.str]:
        """
        The Lagoon project name this route belongs to.
        """
        return pulumi.get(self, "project_name")

    @_builtins.property
    @pulumi.getter(name="routeType")
    def route_type(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Route type for active/standby: STANDARD, ACTIVE, or STANDBY.
        """
        return pulumi.get(self, "route_type")

    @_builtins.property
    @pulumi.getter
    def service(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The service to route traffic to (e.g., 'nginx').
        """
        return pulumi.get(self, "service")

    @_builtins.property
    @pulumi.getter
    def source(self) -> pulumi.Output[_builtins.str]:
        """
        The source of this route: API, YAML, or AUTOGENERATED.
        """
        return pulumi.get(self, "source")

    @_builtins.property
    @pulumi.getter(name="tlsAcme")
    def tls_acme(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to use Let's Encrypt for TLS. Defaults to true.
        """
        return pulumi.get(self, "tls_acme")

    @_builtins.property
    @pulumi.getter
    def updated(self) -> pulumi.Output[_builtins.str]:
        """
        Timestamp when the route was last updated.
        """
        return pulumi.get(self, "updated")

