# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['UserPlatformRoleArgs', 'UserPlatformRole']

@pulumi.input_type
class UserPlatformRoleArgs:
    def __init__(__self__, *,
                 role: pulumi.Input[_builtins.str],
                 user_email: pulumi.Input[_builtins.str]):
        """
        The set of arguments for constructing a UserPlatformRole resource.

        :param pulumi.Input[_builtins.str] role: The platform role: OWNER or VIEWER.
        :param pulumi.Input[_builtins.str] user_email: The user's email address.
        """
        pulumi.set(__self__, "role", role)
        pulumi.set(__self__, "user_email", user_email)

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Input[_builtins.str]:
        """
        The platform role: OWNER or VIEWER.
        """
        return pulumi.get(self, "role")

    @role.setter
    def role(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "role", value)

    @_builtins.property
    @pulumi.getter(name="userEmail")
    def user_email(self) -> pulumi.Input[_builtins.str]:
        """
        The user's email address.
        """
        return pulumi.get(self, "user_email")

    @user_email.setter
    def user_email(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "user_email", value)


@pulumi.type_token("lagoon:lagoon:UserPlatformRole")
class UserPlatformRole(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None,
                 user_email: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Assigns a platform-level role (OWNER or VIEWER) to a Lagoon user.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] role: The platform role: OWNER or VIEWER.
        :param pulumi.Input[_builtins.str] user_email: The user's email address.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: UserPlatformRoleArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Assigns a platform-level role (OWNER or VIEWER) to a Lagoon user.


        :param str resource_name: The name of the resource.
        :param UserPlatformRoleArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(UserPlatformRoleArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 role: pulumi.Input[Optional[_builtins.str]] = None,
                 user_email: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = UserPlatformRoleArgs.__new__(UserPlatformRoleArgs)

            if role is None and not opts.urn:
                raise TypeError("Missing required property 'role'")
            __props__.__dict__["role"] = role
            if user_email is None and not opts.urn:
                raise TypeError("Missing required property 'user_email'")
            __props__.__dict__["user_email"] = user_email
        super(UserPlatformRole, __self__).__init__(
            'lagoon:lagoon:UserPlatformRole',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'UserPlatformRole':
        """
        Get an existing UserPlatformRole resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = UserPlatformRoleArgs.__new__(UserPlatformRoleArgs)

        __props__.__dict__["role"] = None
        __props__.__dict__["user_email"] = None
        return UserPlatformRole(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def role(self) -> pulumi.Output[_builtins.str]:
        """
        The platform role: OWNER or VIEWER.
        """
        return pulumi.get(self, "role")

    @_builtins.property
    @pulumi.getter(name="userEmail")
    def user_email(self) -> pulumi.Output[_builtins.str]:
        """
        The user's email address.
        """
        return pulumi.get(self, "user_email")

