# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = ['VariableArgs', 'Variable']

@pulumi.input_type
class VariableArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 project_id: pulumi.Input[_builtins.int],
                 scope: pulumi.Input[_builtins.str],
                 value: pulumi.Input[_builtins.str],
                 environment_id: pulumi.Input[Optional[_builtins.int]] = None):
        """
        The set of arguments for constructing a Variable resource.

        :param pulumi.Input[_builtins.str] name: The variable name.
        :param pulumi.Input[_builtins.int] project_id: The parent project ID.
        :param pulumi.Input[_builtins.str] scope: Variable scope: 'build', 'runtime', 'global', 'container_registry', or 'internal_container_registry'.
        :param pulumi.Input[_builtins.str] value: The variable value (stored as secret).
        :param pulumi.Input[_builtins.int] environment_id: Environment ID (omit for project-level variables).
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "project_id", project_id)
        pulumi.set(__self__, "scope", scope)
        pulumi.set(__self__, "value", value)
        if environment_id is not None:
            pulumi.set(__self__, "environment_id", environment_id)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The variable name.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Input[_builtins.int]:
        """
        The parent project ID.
        """
        return pulumi.get(self, "project_id")

    @project_id.setter
    def project_id(self, value: pulumi.Input[_builtins.int]):
        pulumi.set(self, "project_id", value)

    @_builtins.property
    @pulumi.getter
    def scope(self) -> pulumi.Input[_builtins.str]:
        """
        Variable scope: 'build', 'runtime', 'global', 'container_registry', or 'internal_container_registry'.
        """
        return pulumi.get(self, "scope")

    @scope.setter
    def scope(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "scope", value)

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Input[_builtins.str]:
        """
        The variable value (stored as secret).
        """
        return pulumi.get(self, "value")

    @value.setter
    def value(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "value", value)

    @_builtins.property
    @pulumi.getter(name="environmentId")
    def environment_id(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        Environment ID (omit for project-level variables).
        """
        return pulumi.get(self, "environment_id")

    @environment_id.setter
    def environment_id(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "environment_id", value)


@pulumi.type_token("lagoon:lagoon:Variable")
class Variable(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 environment_id: pulumi.Input[Optional[_builtins.int]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.int]] = None,
                 scope: pulumi.Input[Optional[_builtins.str]] = None,
                 value: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Manages a Lagoon environment or project-level variable.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] environment_id: Environment ID (omit for project-level variables).
        :param pulumi.Input[_builtins.str] name: The variable name.
        :param pulumi.Input[_builtins.int] project_id: The parent project ID.
        :param pulumi.Input[_builtins.str] scope: Variable scope: 'build', 'runtime', 'global', 'container_registry', or 'internal_container_registry'.
        :param pulumi.Input[_builtins.str] value: The variable value (stored as secret).
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: VariableArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Manages a Lagoon environment or project-level variable.


        :param str resource_name: The name of the resource.
        :param VariableArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(VariableArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 environment_id: pulumi.Input[Optional[_builtins.int]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 project_id: pulumi.Input[Optional[_builtins.int]] = None,
                 scope: pulumi.Input[Optional[_builtins.str]] = None,
                 value: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = VariableArgs.__new__(VariableArgs)

            __props__.__dict__["environment_id"] = environment_id
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            if project_id is None and not opts.urn:
                raise TypeError("Missing required property 'project_id'")
            __props__.__dict__["project_id"] = project_id
            if scope is None and not opts.urn:
                raise TypeError("Missing required property 'scope'")
            __props__.__dict__["scope"] = scope
            if value is None and not opts.urn:
                raise TypeError("Missing required property 'value'")
            __props__.__dict__["value"] = None if value is None else pulumi.Output.secret(value)
            __props__.__dict__["lagoon_id"] = None
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["value"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(Variable, __self__).__init__(
            'lagoon:lagoon:Variable',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Variable':
        """
        Get an existing Variable resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = VariableArgs.__new__(VariableArgs)

        __props__.__dict__["environment_id"] = None
        __props__.__dict__["lagoon_id"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["project_id"] = None
        __props__.__dict__["scope"] = None
        __props__.__dict__["value"] = None
        return Variable(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="environmentId")
    def environment_id(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        Environment ID (omit for project-level variables).
        """
        return pulumi.get(self, "environment_id")

    @_builtins.property
    @pulumi.getter(name="lagoonId")
    def lagoon_id(self) -> pulumi.Output[_builtins.int]:
        """
        The Lagoon-assigned numeric ID of the variable.
        """
        return pulumi.get(self, "lagoon_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The variable name.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="projectId")
    def project_id(self) -> pulumi.Output[_builtins.int]:
        """
        The parent project ID.
        """
        return pulumi.get(self, "project_id")

    @_builtins.property
    @pulumi.getter
    def scope(self) -> pulumi.Output[_builtins.str]:
        """
        Variable scope: 'build', 'runtime', 'global', 'container_registry', or 'internal_container_registry'.
        """
        return pulumi.get(self, "scope")

    @_builtins.property
    @pulumi.getter
    def value(self) -> pulumi.Output[_builtins.str]:
        """
        The variable value (stored as secret).
        """
        return pulumi.get(self, "value")

