// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * Manages a Lagoon Kubernetes deploy target (cluster).
 */
export class DeployTarget extends pulumi.CustomResource {
    /**
     * Get an existing DeployTarget resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): DeployTarget {
        return new DeployTarget(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'lagoon:lagoon:DeployTarget';

    /**
     * Returns true if the given object is an instance of DeployTarget.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DeployTarget {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DeployTarget.__pulumiType;
    }

    /**
     * Custom build image.
     */
    declare public readonly buildImage: pulumi.Output<string | undefined>;
    /**
     * Cloud provider (e.g., 'kind', 'aws', 'gcp'). Defaults to 'kind'.
     */
    declare public readonly cloudProvider: pulumi.Output<string | undefined>;
    /**
     * Cloud region (e.g., 'us-east-1', 'local'). Defaults to 'local'.
     */
    declare public readonly cloudRegion: pulumi.Output<string | undefined>;
    /**
     * The Kubernetes API URL.
     */
    declare public readonly consoleUrl: pulumi.Output<string>;
    declare public /*out*/ readonly created: pulumi.Output<string>;
    /**
     * Whether the deploy target is disabled.
     */
    declare public readonly disabled: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly lagoonId: pulumi.Output<number>;
    /**
     * The deploy target name.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Router pattern for the deploy target.
     */
    declare public readonly routerPattern: pulumi.Output<string | undefined>;
    declare public readonly sharedBastionSecret: pulumi.Output<string | undefined>;
    /**
     * SSH host for builds.
     */
    declare public readonly sshHost: pulumi.Output<string | undefined>;
    /**
     * SSH port for builds.
     */
    declare public readonly sshPort: pulumi.Output<string | undefined>;

    /**
     * Create a DeployTarget resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DeployTargetArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.consoleUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'consoleUrl'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["buildImage"] = args?.buildImage;
            resourceInputs["cloudProvider"] = args?.cloudProvider;
            resourceInputs["cloudRegion"] = args?.cloudRegion;
            resourceInputs["consoleUrl"] = args?.consoleUrl;
            resourceInputs["disabled"] = args?.disabled;
            resourceInputs["name"] = args?.name;
            resourceInputs["routerPattern"] = args?.routerPattern;
            resourceInputs["sharedBastionSecret"] = args?.sharedBastionSecret;
            resourceInputs["sshHost"] = args?.sshHost;
            resourceInputs["sshPort"] = args?.sshPort;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["lagoonId"] = undefined /*out*/;
        } else {
            resourceInputs["buildImage"] = undefined /*out*/;
            resourceInputs["cloudProvider"] = undefined /*out*/;
            resourceInputs["cloudRegion"] = undefined /*out*/;
            resourceInputs["consoleUrl"] = undefined /*out*/;
            resourceInputs["created"] = undefined /*out*/;
            resourceInputs["disabled"] = undefined /*out*/;
            resourceInputs["lagoonId"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["routerPattern"] = undefined /*out*/;
            resourceInputs["sharedBastionSecret"] = undefined /*out*/;
            resourceInputs["sshHost"] = undefined /*out*/;
            resourceInputs["sshPort"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DeployTarget.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a DeployTarget resource.
 */
export interface DeployTargetArgs {
    /**
     * Custom build image.
     */
    buildImage?: pulumi.Input<string>;
    /**
     * Cloud provider (e.g., 'kind', 'aws', 'gcp'). Defaults to 'kind'.
     */
    cloudProvider?: pulumi.Input<string>;
    /**
     * Cloud region (e.g., 'us-east-1', 'local'). Defaults to 'local'.
     */
    cloudRegion?: pulumi.Input<string>;
    /**
     * The Kubernetes API URL.
     */
    consoleUrl: pulumi.Input<string>;
    /**
     * Whether the deploy target is disabled.
     */
    disabled?: pulumi.Input<boolean>;
    /**
     * The deploy target name.
     */
    name: pulumi.Input<string>;
    /**
     * Router pattern for the deploy target.
     */
    routerPattern?: pulumi.Input<string>;
    sharedBastionSecret?: pulumi.Input<string>;
    /**
     * SSH host for builds.
     */
    sshHost?: pulumi.Input<string>;
    /**
     * SSH port for builds.
     */
    sshPort?: pulumi.Input<string>;
}
