// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace resources {
    export interface AutogeneratedPathRouteInputArgs {
        /**
         * The source service originating the request.
         */
        fromService: pulumi.Input<string>;
        /**
         * The URL path prefix to match.
         */
        path: pulumi.Input<string>;
        /**
         * The destination service to route to.
         */
        toService: pulumi.Input<string>;
    }

    export interface RouteAnnotationInputArgs {
        /**
         * The annotation key.
         */
        key: pulumi.Input<string>;
        /**
         * The annotation value.
         */
        value: pulumi.Input<string>;
    }

    export interface RoutePathRouteInputArgs {
        /**
         * The URL path prefix to match (e.g., '/api').
         */
        path: pulumi.Input<string>;
        /**
         * The service to route matching requests to.
         */
        toService: pulumi.Input<string>;
    }

    export interface TaskArgumentInputArgs {
        /**
         * The human-readable label shown in the Lagoon UI.
         */
        displayName: pulumi.Input<string>;
        /**
         * The argument identifier (used as the variable name).
         */
        name: pulumi.Input<string>;
        /**
         * The argument type: STRING, ENVIRONMENT_SOURCE_NAME, or ENVIRONMENT_SOURCE_NAME_EXCLUDE_SELF.
         */
        type: pulumi.Input<string>;
    }
}
