// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace resources {
    export interface AutogeneratedPathRouteInput {
        fromService: string;
        path: string;
        toService: string;
    }

    export interface RouteAnnotationInput {
        key: string;
        value: string;
    }

    export interface RoutePathRouteInput {
        path: string;
        toService: string;
    }

    export interface TaskArgumentInput {
        displayName: string;
        name: string;
        type: string;
    }

}
