package client

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
)

// Route represents a Lagoon API-managed route.
type Route struct {
	ID                         int               `json:"id"`
	Domain                     string            `json:"domain"`
	Service                    string            `json:"service"`
	TLSAcme                    *bool             `json:"tlsAcme"`
	Insecure                   string            `json:"insecure"`
	Primary                    *bool             `json:"primary"`
	Source                     string            `json:"source"`
	Type                       string            `json:"type"`
	DisableRequestVerification *bool             `json:"disableRequestVerification"`
	HSTSEnabled                *bool             `json:"hstsEnabled"`
	HSTSPreload                *bool             `json:"hstsPreload"`
	HSTSIncludeSubdomains      *bool             `json:"hstsIncludeSubdomains"`
	HSTSMaxAge                 *int              `json:"hstsMaxAge"`
	MonitoringPath             string            `json:"monitoringPath"`
	Annotations                []RouteAnnotation `json:"annotations"`
	AlternativeNames           []AlternativeName `json:"alternativeNames"`
	PathRoutes                 []RoutePathRoute  `json:"pathRoutes"`
	Created                    string            `json:"created"`
	Updated                    string            `json:"updated"`
	// Normalized from nested objects
	ProjectName     string `json:"-"`
	EnvironmentName string `json:"-"`
}

// RouteAnnotation is a key/value annotation on a route.
type RouteAnnotation struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// AlternativeName is an additional domain (SAN) on a route.
type AlternativeName struct {
	ID     int    `json:"id"`
	Domain string `json:"domain"`
}

// RoutePathRoute is a path-based routing rule on a route.
type RoutePathRoute struct {
	ID        int    `json:"id"`
	Path      string `json:"path"`
	ToService string `json:"toService"`
}

// AutogeneratedRouteConfig holds the autogenerated route configuration for a project or environment.
type AutogeneratedRouteConfig struct {
	Enabled                    *bool                       `json:"enabled"`
	AllowPullRequests          *bool                       `json:"allowPullRequests"`
	Prefixes                   []string                    `json:"prefixes"`
	PathRoutes                 []AutogeneratedRoutePathRoute `json:"pathRoutes"`
	DisableRequestVerification *bool                       `json:"disableRequestVerification"`
	Insecure                   string                      `json:"insecure"`
	TLSAcme                    *bool                       `json:"tlsAcme"`
}

// AutogeneratedRoutePathRoute is a path route within an autogenerated route config.
type AutogeneratedRoutePathRoute struct {
	FromService string `json:"fromService"`
	ToService   string `json:"toService"`
	Path        string `json:"path"`
}

// routeRaw mirrors the GraphQL response shape for unmarshaling.
type routeRaw struct {
	ID                         int               `json:"id"`
	Domain                     string            `json:"domain"`
	Service                    string            `json:"service"`
	TLSAcme                    *bool             `json:"tlsAcme"`
	Insecure                   string            `json:"insecure"`
	Primary                    *bool             `json:"primary"`
	Source                     string            `json:"source"`
	Type                       string            `json:"type"`
	DisableRequestVerification *bool             `json:"disableRequestVerification"`
	HSTSEnabled                *bool             `json:"hstsEnabled"`
	HSTSPreload                *bool             `json:"hstsPreload"`
	HSTSIncludeSubdomains      *bool             `json:"hstsIncludeSubdomains"`
	HSTSMaxAge                 *int              `json:"hstsMaxAge"`
	MonitoringPath             string            `json:"monitoringPath"`
	Annotations                []RouteAnnotation `json:"annotations"`
	AlternativeNames           []AlternativeName `json:"alternativeNames"`
	PathRoutes                 []RoutePathRoute  `json:"pathRoutes"`
	Created                    string            `json:"created"`
	Updated                    string            `json:"updated"`
	Project                    json.RawMessage   `json:"project"`
	Environment                json.RawMessage   `json:"environment"`
}

func normalizeRoute(raw routeRaw) Route {
	r := Route{
		ID:                         raw.ID,
		Domain:                     raw.Domain,
		Service:                    raw.Service,
		TLSAcme:                    raw.TLSAcme,
		Insecure:                   raw.Insecure,
		Primary:                    raw.Primary,
		Source:                     raw.Source,
		Type:                       raw.Type,
		DisableRequestVerification: raw.DisableRequestVerification,
		HSTSEnabled:                raw.HSTSEnabled,
		HSTSPreload:                raw.HSTSPreload,
		HSTSIncludeSubdomains:      raw.HSTSIncludeSubdomains,
		HSTSMaxAge:                 raw.HSTSMaxAge,
		MonitoringPath:             raw.MonitoringPath,
		Annotations:                raw.Annotations,
		AlternativeNames:           raw.AlternativeNames,
		PathRoutes:                 raw.PathRoutes,
		Created:                    raw.Created,
		Updated:                    raw.Updated,
	}

	if len(raw.Project) > 0 && string(raw.Project) != "null" {
		var proj struct {
			Name string `json:"name"`
		}
		if err := json.Unmarshal(raw.Project, &proj); err == nil {
			r.ProjectName = proj.Name
		}
	}

	if len(raw.Environment) > 0 && string(raw.Environment) != "null" {
		var env struct {
			Name string `json:"name"`
		}
		if err := json.Unmarshal(raw.Environment, &env); err == nil {
			r.EnvironmentName = env.Name
		}
	}

	return r
}

// AddRouteToProject creates a new route on a project.
func (c *Client) AddRouteToProject(ctx context.Context, input map[string]any) (*Route, error) {
	data, err := c.Execute(ctx, mutationAddRouteToProject, map[string]any{"input": input})
	if err != nil {
		return nil, err
	}

	raw, err := unmarshalField[routeRaw](data, "addRouteToProject")
	if err != nil {
		return nil, err
	}

	r := normalizeRoute(raw)
	return &r, nil
}

// GetRouteByDomain retrieves a route by project name and domain.
// Routes have no standalone query; this queries through projectByName.apiRoutes.
func (c *Client) GetRouteByDomain(ctx context.Context, projectName, domain string) (*Route, error) {
	data, err := c.Execute(ctx, queryGetRouteByDomain, map[string]any{
		"name":   projectName,
		"domain": domain,
	})
	if err != nil {
		return nil, err
	}

	// Response: { projectByName: { apiRoutes: [...] } }
	var wrapper struct {
		APIRoutes []routeRaw `json:"apiRoutes"`
	}
	raw, err := extractField(data, "projectByName")
	if err != nil {
		return nil, err
	}
	if string(raw) == "null" {
		return nil, &LagoonNotFoundError{ResourceType: "Route", Identifier: fmt.Sprintf("%s:%s", projectName, domain)}
	}
	if err := json.Unmarshal(raw, &wrapper); err != nil {
		return nil, fmt.Errorf("failed to unmarshal projectByName: %w", err)
	}

	for _, rr := range wrapper.APIRoutes {
		if strings.EqualFold(rr.Domain, domain) {
			r := normalizeRoute(rr)
			return &r, nil
		}
	}

	return nil, &LagoonNotFoundError{ResourceType: "Route", Identifier: fmt.Sprintf("%s:%s", projectName, domain)}
}

// UpdateRouteOnProject updates mutable scalar fields on a route.
func (c *Client) UpdateRouteOnProject(ctx context.Context, routeID int, patch map[string]any) (*Route, error) {
	// The UpdateRouteInput requires domain+project as identity, but we use id-based internal tracking.
	// The API accepts the domain+project lookup; we pass them via the patch wrapper.
	data, err := c.Execute(ctx, mutationUpdateRouteOnProject, map[string]any{"input": patch})
	if err != nil {
		return nil, err
	}

	raw, err := unmarshalField[routeRaw](data, "updateRouteOnProject")
	if err != nil {
		return nil, err
	}

	_ = routeID // identity is domain+project in the patch; ID retained for future use
	r := normalizeRoute(raw)
	return &r, nil
}

// DeleteRoute deletes a route by its Lagoon ID.
func (c *Client) DeleteRoute(ctx context.Context, routeID int) error {
	_, err := c.Execute(ctx, mutationDeleteRoute, map[string]any{
		"input": map[string]any{"id": routeID},
	})
	if err != nil {
		var apiErr *LagoonAPIError
		if errors.As(err, &apiErr) && strings.Contains(strings.ToLower(apiErr.Message), "not found") {
			return &LagoonNotFoundError{ResourceType: "Route", Identifier: fmt.Sprintf("%d", routeID)}
		}
	}
	return err
}

// AddOrUpdateRouteOnEnvironment attaches or moves a route to an environment.
func (c *Client) AddOrUpdateRouteOnEnvironment(ctx context.Context, input map[string]any) (*Route, error) {
	data, err := c.Execute(ctx, mutationAddOrUpdateRouteOnEnvironment, map[string]any{"input": input})
	if err != nil {
		return nil, err
	}

	raw, err := unmarshalField[routeRaw](data, "addOrUpdateRouteOnEnvironment")
	if err != nil {
		return nil, err
	}

	r := normalizeRoute(raw)
	return &r, nil
}

// RemoveRouteFromEnvironment detaches a route from an environment.
func (c *Client) RemoveRouteFromEnvironment(ctx context.Context, domain, project, environment string) error {
	_, err := c.Execute(ctx, mutationRemoveRouteFromEnvironment, map[string]any{
		"input": map[string]any{
			"domain":      domain,
			"project":     project,
			"environment": environment,
		},
	})
	if err != nil {
		var apiErr *LagoonAPIError
		if errors.As(err, &apiErr) && strings.Contains(strings.ToLower(apiErr.Message), "not found") {
			return &LagoonNotFoundError{ResourceType: "Route", Identifier: domain}
		}
	}
	return err
}

// AddRouteAlternativeDomains adds alternative domain names to a route.
func (c *Client) AddRouteAlternativeDomains(ctx context.Context, routeID int, domains []string) (*Route, error) {
	data, err := c.Execute(ctx, mutationAddRouteAlternativeDomains, map[string]any{
		"input": map[string]any{
			"id":               routeID,
			"alternativeNames": domains,
		},
	})
	if err != nil {
		return nil, err
	}

	raw, err := unmarshalField[routeRaw](data, "addRouteAlternativeDomains")
	if err != nil {
		return nil, err
	}

	r := normalizeRoute(raw)
	return &r, nil
}

// RemoveRouteAlternativeDomain removes one alternative domain from a route.
func (c *Client) RemoveRouteAlternativeDomain(ctx context.Context, routeID int, domain string) (*Route, error) {
	data, err := c.Execute(ctx, mutationRemoveRouteAlternativeDomain, map[string]any{
		"input": map[string]any{
			"id":     routeID,
			"domain": domain,
		},
	})
	if err != nil {
		return nil, err
	}

	raw, err := unmarshalField[routeRaw](data, "removeRouteAlternativeDomain")
	if err != nil {
		return nil, err
	}

	r := normalizeRoute(raw)
	return &r, nil
}

// AddRouteAnnotations adds key/value annotations to a route.
func (c *Client) AddRouteAnnotations(ctx context.Context, routeID int, annotations []map[string]string) (*Route, error) {
	anns := make([]map[string]any, len(annotations))
	for i, a := range annotations {
		anns[i] = map[string]any{"key": a["key"], "value": a["value"]}
	}

	data, err := c.Execute(ctx, mutationAddRouteAnnotation, map[string]any{
		"input": map[string]any{
			"id":          routeID,
			"annotations": anns,
		},
	})
	if err != nil {
		return nil, err
	}

	raw, err := unmarshalField[routeRaw](data, "addRouteAnnotation")
	if err != nil {
		return nil, err
	}

	r := normalizeRoute(raw)
	return &r, nil
}

// RemoveRouteAnnotation removes a single annotation from a route by key.
func (c *Client) RemoveRouteAnnotation(ctx context.Context, routeID int, key string) (*Route, error) {
	data, err := c.Execute(ctx, mutationRemoveRouteAnnotation, map[string]any{
		"input": map[string]any{
			"id":  routeID,
			"key": key,
		},
	})
	if err != nil {
		return nil, err
	}

	raw, err := unmarshalField[routeRaw](data, "removeRouteAnnotation")
	if err != nil {
		return nil, err
	}

	r := normalizeRoute(raw)
	return &r, nil
}

// AddPathRoutesToRoute adds path-based routing rules to a route.
func (c *Client) AddPathRoutesToRoute(ctx context.Context, routeID int, pathRoutes []map[string]string) (*Route, error) {
	prs := make([]map[string]any, len(pathRoutes))
	for i, pr := range pathRoutes {
		prs[i] = map[string]any{"path": pr["path"], "toService": pr["toService"]}
	}

	data, err := c.Execute(ctx, mutationAddPathRoutesToRoute, map[string]any{
		"input": map[string]any{
			"id":         routeID,
			"pathRoutes": prs,
		},
	})
	if err != nil {
		return nil, err
	}

	raw, err := unmarshalField[routeRaw](data, "addPathRoutesToRoute")
	if err != nil {
		return nil, err
	}

	r := normalizeRoute(raw)
	return &r, nil
}

// RemovePathRouteFromRoute removes a path route from a route.
func (c *Client) RemovePathRouteFromRoute(ctx context.Context, routeID int, toService, path string) (*Route, error) {
	data, err := c.Execute(ctx, mutationRemovePathRouteFromRoute, map[string]any{
		"input": map[string]any{
			"id":        routeID,
			"toService": toService,
			"path":      path,
		},
	})
	if err != nil {
		return nil, err
	}

	raw, err := unmarshalField[routeRaw](data, "removePathRouteFromRoute")
	if err != nil {
		return nil, err
	}

	r := normalizeRoute(raw)
	return &r, nil
}

// UpdateAutogeneratedRouteConfigOnProject sets the autogenerated route config for a project.
func (c *Client) UpdateAutogeneratedRouteConfigOnProject(ctx context.Context, projectName string, patch map[string]any) (*AutogeneratedRouteConfig, error) {
	data, err := c.Execute(ctx, mutationUpdateAutogeneratedRouteConfigOnProject, map[string]any{
		"input": map[string]any{
			"project": projectName,
			"patch":   patch,
		},
	})
	if err != nil {
		return nil, err
	}

	cfg, err := unmarshalField[*AutogeneratedRouteConfig](data, "updateAutogeneratedRouteConfigOnProject")
	if err != nil {
		return nil, err
	}

	return cfg, nil
}

// RemoveAutogeneratedRouteConfigFromProject removes the autogenerated route config from a project.
func (c *Client) RemoveAutogeneratedRouteConfigFromProject(ctx context.Context, projectName string) error {
	_, err := c.Execute(ctx, mutationRemoveAutogeneratedRouteConfigFromProject, map[string]any{
		"project": projectName,
	})
	if err != nil {
		var apiErr *LagoonAPIError
		if errors.As(err, &apiErr) && strings.Contains(strings.ToLower(apiErr.Message), "not found") {
			return &LagoonNotFoundError{ResourceType: "AutogeneratedRouteConfig", Identifier: projectName}
		}
	}
	return err
}

// GetAutogeneratedRouteConfigForProject retrieves the autogenerated route config for a project.
func (c *Client) GetAutogeneratedRouteConfigForProject(ctx context.Context, projectName string) (*AutogeneratedRouteConfig, error) {
	data, err := c.Execute(ctx, queryGetProjectAutogeneratedRouteConfig, map[string]any{
		"name": projectName,
	})
	if err != nil {
		return nil, err
	}

	raw, err := extractField(data, "projectByName")
	if err != nil {
		return nil, err
	}
	if string(raw) == "null" {
		return nil, &LagoonNotFoundError{ResourceType: "Project", Identifier: projectName}
	}

	var wrapper struct {
		AutogeneratedRouteConfig *AutogeneratedRouteConfig `json:"autogeneratedRouteConfig"`
	}
	if err := json.Unmarshal(raw, &wrapper); err != nil {
		return nil, fmt.Errorf("failed to unmarshal autogeneratedRouteConfig: %w", err)
	}

	return wrapper.AutogeneratedRouteConfig, nil
}

// UpdateAutogeneratedRouteConfigOnEnvironment sets the autogenerated route config for an environment.
func (c *Client) UpdateAutogeneratedRouteConfigOnEnvironment(ctx context.Context, projectName, environmentName string, patch map[string]any) (*AutogeneratedRouteConfig, error) {
	data, err := c.Execute(ctx, mutationUpdateAutogeneratedRouteConfigOnEnvironment, map[string]any{
		"input": map[string]any{
			"project":     projectName,
			"environment": environmentName,
			"patch":       patch,
		},
	})
	if err != nil {
		return nil, err
	}

	cfg, err := unmarshalField[*AutogeneratedRouteConfig](data, "updateAutogeneratedRouteConfigOnEnvironment")
	if err != nil {
		return nil, err
	}

	return cfg, nil
}

// RemoveAutogeneratedRouteConfigFromEnvironment removes the autogenerated route config from an environment.
func (c *Client) RemoveAutogeneratedRouteConfigFromEnvironment(ctx context.Context, projectName, environmentName string) error {
	_, err := c.Execute(ctx, mutationRemoveAutogeneratedRouteConfigFromEnvironment, map[string]any{
		"project":     projectName,
		"environment": environmentName,
	})
	if err != nil {
		var apiErr *LagoonAPIError
		if errors.As(err, &apiErr) && strings.Contains(strings.ToLower(apiErr.Message), "not found") {
			return &LagoonNotFoundError{ResourceType: "AutogeneratedRouteConfig", Identifier: projectName + ":" + environmentName}
		}
	}
	return err
}

// GetAutogeneratedRouteConfigForEnvironment retrieves the autogenerated route config for an environment.
// It requires the project ID to look up the environment by name.
func (c *Client) GetAutogeneratedRouteConfigForEnvironment(ctx context.Context, projectName, environmentName string) (*AutogeneratedRouteConfig, error) {
	// First get the project ID needed for environmentByName
	proj, err := c.GetProjectByName(ctx, projectName)
	if err != nil {
		return nil, err
	}

	data, err := c.Execute(ctx, queryGetEnvironmentAutogeneratedRouteConfig, map[string]any{
		"name":    environmentName,
		"project": proj.ID,
	})
	if err != nil {
		return nil, err
	}

	raw, err := extractField(data, "environmentByName")
	if err != nil {
		return nil, err
	}
	if string(raw) == "null" {
		return nil, &LagoonNotFoundError{ResourceType: "Environment", Identifier: fmt.Sprintf("%s/%s", projectName, environmentName)}
	}

	var wrapper struct {
		AutogeneratedRouteConfig *AutogeneratedRouteConfig `json:"autogeneratedRouteConfig"`
	}
	if err := json.Unmarshal(raw, &wrapper); err != nil {
		return nil, fmt.Errorf("failed to unmarshal autogeneratedRouteConfig: %w", err)
	}

	return wrapper.AutogeneratedRouteConfig, nil
}
