package client

import (
	"context"
	"errors"
	"strings"
	"testing"
)

// --- Project Autogenerated Route Config Tests ---

func TestUpdateAutogeneratedRouteConfigOnProject(t *testing.T) {
	server := mockGraphQLServer(t, func(query string, variables map[string]any) (any, error) {
		if !strings.Contains(query, "updateAutogeneratedRouteConfigOnProject") {
			t.Errorf("expected updateAutogeneratedRouteConfigOnProject mutation")
		}
		enabled := true
		allowPR := true
		tlsAcme := true
		return map[string]any{
			"updateAutogeneratedRouteConfigOnProject": map[string]any{
				"enabled":          &enabled,
				"allowPullRequests": &allowPR,
				"prefixes":         []string{"www", "staging"},
				"tlsAcme":          &tlsAcme,
			},
		}, nil
	})
	defer server.Close()

	c := NewClient(server.URL, "token")
	cfg, err := c.UpdateAutogeneratedRouteConfigOnProject(context.Background(), "my-project", map[string]any{
		"enabled": true,
	})
	if err != nil {
		t.Fatalf("UpdateAutogeneratedRouteConfigOnProject failed: %v", err)
	}
	if cfg.Enabled == nil || !*cfg.Enabled {
		t.Error("expected enabled=true")
	}
	if len(cfg.Prefixes) != 2 {
		t.Errorf("expected 2 prefixes, got %d", len(cfg.Prefixes))
	}
}

func TestGetAutogeneratedRouteConfigForProject(t *testing.T) {
	server := mockGraphQLServer(t, func(query string, variables map[string]any) (any, error) {
		if !strings.Contains(query, "projectByName") {
			t.Errorf("expected projectByName query")
		}
		enabled := true
		return map[string]any{
			"projectByName": map[string]any{
				"autogeneratedRouteConfig": map[string]any{
					"enabled":  &enabled,
					"prefixes": []string{"prod"},
				},
			},
		}, nil
	})
	defer server.Close()

	c := NewClient(server.URL, "token")
	cfg, err := c.GetAutogeneratedRouteConfigForProject(context.Background(), "my-project")
	if err != nil {
		t.Fatalf("GetAutogeneratedRouteConfigForProject failed: %v", err)
	}
	if cfg.Enabled == nil || !*cfg.Enabled {
		t.Error("expected enabled=true")
	}
}

func TestGetAutogeneratedRouteConfigForProject_ProjectNotFound(t *testing.T) {
	server := mockGraphQLServer(t, func(query string, variables map[string]any) (any, error) {
		return map[string]any{"projectByName": nil}, nil
	})
	defer server.Close()

	c := NewClient(server.URL, "token")
	_, err := c.GetAutogeneratedRouteConfigForProject(context.Background(), "nonexistent")
	if err == nil {
		t.Fatal("expected error")
	}
	var notFoundErr *LagoonNotFoundError
	if !errors.As(err, &notFoundErr) {
		t.Errorf("expected LagoonNotFoundError, got %T", err)
	}
}

func TestGetAutogeneratedRouteConfigForProject_NullConfig(t *testing.T) {
	server := mockGraphQLServer(t, func(query string, variables map[string]any) (any, error) {
		return map[string]any{
			"projectByName": map[string]any{
				"autogeneratedRouteConfig": nil,
			},
		}, nil
	})
	defer server.Close()

	c := NewClient(server.URL, "token")
	cfg, err := c.GetAutogeneratedRouteConfigForProject(context.Background(), "my-project")
	if err != nil {
		t.Fatalf("expected nil error for null config, got %v", err)
	}
	if cfg != nil {
		t.Error("expected nil config")
	}
}

func TestRemoveAutogeneratedRouteConfigFromProject(t *testing.T) {
	server := mockGraphQLServer(t, func(query string, variables map[string]any) (any, error) {
		if !strings.Contains(query, "removeAutogeneratedRouteConfigFromProject") {
			t.Errorf("expected removeAutogeneratedRouteConfigFromProject mutation")
		}
		return map[string]any{"removeAutogeneratedRouteConfigFromProject": "success"}, nil
	})
	defer server.Close()

	c := NewClient(server.URL, "token")
	err := c.RemoveAutogeneratedRouteConfigFromProject(context.Background(), "my-project")
	if err != nil {
		t.Fatalf("RemoveAutogeneratedRouteConfigFromProject failed: %v", err)
	}
}

func TestRemoveAutogeneratedRouteConfigFromProject_NotFound(t *testing.T) {
	server := mockGraphQLServer(t, func(query string, variables map[string]any) (any, error) {
		return nil, &LagoonAPIError{Message: "Config not found"}
	})
	defer server.Close()

	c := NewClient(server.URL, "token")
	err := c.RemoveAutogeneratedRouteConfigFromProject(context.Background(), "nonexistent")
	if err == nil {
		t.Fatal("expected error")
	}
	var notFoundErr *LagoonNotFoundError
	if !errors.As(err, &notFoundErr) {
		t.Errorf("expected LagoonNotFoundError, got %T", err)
	}
}

// --- Environment Autogenerated Route Config Tests ---

func TestUpdateAutogeneratedRouteConfigOnEnvironment(t *testing.T) {
	server := mockGraphQLServer(t, func(query string, variables map[string]any) (any, error) {
		if !strings.Contains(query, "updateAutogeneratedRouteConfigOnEnvironment") {
			t.Errorf("expected updateAutogeneratedRouteConfigOnEnvironment mutation")
		}
		enabled := false
		return map[string]any{
			"updateAutogeneratedRouteConfigOnEnvironment": map[string]any{
				"enabled": &enabled,
			},
		}, nil
	})
	defer server.Close()

	c := NewClient(server.URL, "token")
	cfg, err := c.UpdateAutogeneratedRouteConfigOnEnvironment(context.Background(), "my-project", "main", map[string]any{
		"enabled": false,
	})
	if err != nil {
		t.Fatalf("UpdateAutogeneratedRouteConfigOnEnvironment failed: %v", err)
	}
	if cfg.Enabled == nil || *cfg.Enabled {
		t.Error("expected enabled=false")
	}
}

func TestGetAutogeneratedRouteConfigForEnvironment(t *testing.T) {
	callCount := 0
	server := mockGraphQLServer(t, func(query string, variables map[string]any) (any, error) {
		callCount++
		if callCount == 1 {
			// First call: GetProjectByName
			if !strings.Contains(query, "projectByName") || strings.Contains(query, "autogeneratedRouteConfig") {
				t.Errorf("expected projectByName query (without autogeneratedRouteConfig)")
			}
			return map[string]any{
				"projectByName": map[string]any{
					"id":   42,
					"name": "my-project",
				},
			}, nil
		}
		// Second call: environmentByName
		if !strings.Contains(query, "environmentByName") {
			t.Errorf("expected environmentByName query")
		}
		enabled := true
		return map[string]any{
			"environmentByName": map[string]any{
				"autogeneratedRouteConfig": map[string]any{
					"enabled": &enabled,
				},
			},
		}, nil
	})
	defer server.Close()

	c := NewClient(server.URL, "token")
	cfg, err := c.GetAutogeneratedRouteConfigForEnvironment(context.Background(), "my-project", "main")
	if err != nil {
		t.Fatalf("GetAutogeneratedRouteConfigForEnvironment failed: %v", err)
	}
	if cfg.Enabled == nil || !*cfg.Enabled {
		t.Error("expected enabled=true")
	}
	if callCount != 2 {
		t.Errorf("expected 2 calls (GetProjectByName + environmentByName), got %d", callCount)
	}
}

func TestGetAutogeneratedRouteConfigForEnvironment_ProjectNotFound(t *testing.T) {
	server := mockGraphQLServer(t, func(query string, variables map[string]any) (any, error) {
		return map[string]any{"projectByName": nil}, nil
	})
	defer server.Close()

	c := NewClient(server.URL, "token")
	_, err := c.GetAutogeneratedRouteConfigForEnvironment(context.Background(), "nonexistent", "main")
	if err == nil {
		t.Fatal("expected error when project not found")
	}
	var notFoundErr *LagoonNotFoundError
	if !errors.As(err, &notFoundErr) {
		t.Errorf("expected LagoonNotFoundError, got %T", err)
	}
}

func TestGetAutogeneratedRouteConfigForEnvironment_EnvironmentNotFound(t *testing.T) {
	callCount := 0
	server := mockGraphQLServer(t, func(query string, variables map[string]any) (any, error) {
		callCount++
		if callCount == 1 {
			return map[string]any{
				"projectByName": map[string]any{"id": 42, "name": "my-project"},
			}, nil
		}
		return map[string]any{"environmentByName": nil}, nil
	})
	defer server.Close()

	c := NewClient(server.URL, "token")
	_, err := c.GetAutogeneratedRouteConfigForEnvironment(context.Background(), "my-project", "nonexistent")
	if err == nil {
		t.Fatal("expected error when environment not found")
	}
	var notFoundErr *LagoonNotFoundError
	if !errors.As(err, &notFoundErr) {
		t.Errorf("expected LagoonNotFoundError, got %T", err)
	}
}

func TestRemoveAutogeneratedRouteConfigFromEnvironment(t *testing.T) {
	server := mockGraphQLServer(t, func(query string, variables map[string]any) (any, error) {
		if !strings.Contains(query, "removeAutogeneratedRouteConfigFromEnvironment") {
			t.Errorf("expected removeAutogeneratedRouteConfigFromEnvironment mutation")
		}
		return map[string]any{"removeAutogeneratedRouteConfigFromEnvironment": "success"}, nil
	})
	defer server.Close()

	c := NewClient(server.URL, "token")
	err := c.RemoveAutogeneratedRouteConfigFromEnvironment(context.Background(), "my-project", "main")
	if err != nil {
		t.Fatalf("RemoveAutogeneratedRouteConfigFromEnvironment failed: %v", err)
	}
}

func TestRemoveAutogeneratedRouteConfigFromEnvironment_NotFound(t *testing.T) {
	server := mockGraphQLServer(t, func(query string, variables map[string]any) (any, error) {
		return nil, &LagoonAPIError{Message: "not found"}
	})
	defer server.Close()

	c := NewClient(server.URL, "token")
	err := c.RemoveAutogeneratedRouteConfigFromEnvironment(context.Background(), "my-project", "nonexistent")
	if err == nil {
		t.Fatal("expected error")
	}
	var notFoundErr *LagoonNotFoundError
	if !errors.As(err, &notFoundErr) {
		t.Errorf("expected LagoonNotFoundError, got %T", err)
	}
}
