// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Tag1Consulting.Lagoon.Resources.Inputs
{

    public sealed class AutogeneratedPathRouteInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("fromService", required: true)]
        public Input<string> FromService { get; set; } = null!;

        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        [Input("toService", required: true)]
        public Input<string> ToService { get; set; } = null!;

        public AutogeneratedPathRouteInputArgs()
        {
        }
        public static new AutogeneratedPathRouteInputArgs Empty => new AutogeneratedPathRouteInputArgs();
    }
}
