// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Tag1Consulting.Lagoon.Resources.Inputs
{

    public sealed class RouteAnnotationInputArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The annotation key.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The annotation value.
        /// </summary>
        [Input("value", required: true)]
        public Input<string> Value { get; set; } = null!;

        public RouteAnnotationInputArgs()
        {
        }
        public static new RouteAnnotationInputArgs Empty => new RouteAnnotationInputArgs();
    }
}
