# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('lagoon')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def api_url(self) -> str:
        """
        The Lagoon GraphQL API endpoint URL.
        """
        return __config__.get('apiUrl') or (_utilities.get_env('LAGOON_API_URL') or 'https://api.lagoon.sh/graphql')

    @_builtins.property
    def insecure(self) -> bool:
        """
        Disable SSL certificate verification when connecting to the Lagoon API.
        """
        return __config__.get_bool('insecure') or (_utilities.get_env_bool('LAGOON_INSECURE') or False)

    @_builtins.property
    def jwt_audience(self) -> str:
        """
        The audience claim for generated JWT tokens. Defaults to 'api.dev'.
        """
        return __config__.get('jwtAudience') or (_utilities.get_env('LAGOON_JWT_AUDIENCE') or 'api.dev')

    @_builtins.property
    def jwt_secret(self) -> Optional[str]:
        """
        The Lagoon core JWTSECRET. Used to generate admin tokens on-the-fly.
        """
        return __config__.get('jwtSecret') or _utilities.get_env('LAGOON_JWT_SECRET')

    @_builtins.property
    def token(self) -> Optional[str]:
        """
        A pre-configured JWT authentication token for the Lagoon API.
        """
        return __config__.get('token') or _utilities.get_env('LAGOON_TOKEN')

