// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'lagoon';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * The Lagoon GraphQL API endpoint URL.
     */
    declare public readonly apiUrl: pulumi.Output<string | undefined>;
    /**
     * The audience claim for generated JWT tokens. Defaults to 'api.dev'.
     */
    declare public readonly jwtAudience: pulumi.Output<string | undefined>;
    /**
     * The Lagoon core JWTSECRET. Used to generate admin tokens on-the-fly.
     */
    declare public readonly jwtSecret: pulumi.Output<string | undefined>;
    /**
     * A pre-configured JWT authentication token for the Lagoon API.
     */
    declare public readonly token: pulumi.Output<string | undefined>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            resourceInputs["apiUrl"] = (args?.apiUrl ? pulumi.secret(args.apiUrl) : undefined) ?? (utilities.getEnv("LAGOON_API_URL") || "https://api.lagoon.sh/graphql");
            resourceInputs["insecure"] = pulumi.output((args?.insecure) ?? (utilities.getEnvBoolean("LAGOON_INSECURE") || false)).apply(JSON.stringify);
            resourceInputs["jwtAudience"] = (args?.jwtAudience) ?? (utilities.getEnv("LAGOON_JWT_AUDIENCE") || "api.dev");
            resourceInputs["jwtSecret"] = (args?.jwtSecret ? pulumi.secret(args.jwtSecret) : undefined) ?? utilities.getEnv("LAGOON_JWT_SECRET");
            resourceInputs["token"] = (args?.token ? pulumi.secret(args.token) : undefined) ?? utilities.getEnv("LAGOON_TOKEN");
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiUrl", "jwtSecret", "token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * The Lagoon GraphQL API endpoint URL.
     */
    apiUrl?: pulumi.Input<string | undefined>;
    /**
     * Disable SSL certificate verification when connecting to the Lagoon API.
     */
    insecure?: pulumi.Input<boolean | undefined>;
    /**
     * The audience claim for generated JWT tokens. Defaults to 'api.dev'.
     */
    jwtAudience?: pulumi.Input<string | undefined>;
    /**
     * The Lagoon core JWTSECRET. Used to generate admin tokens on-the-fly.
     */
    jwtSecret?: pulumi.Input<string | undefined>;
    /**
     * A pre-configured JWT authentication token for the Lagoon API.
     */
    token?: pulumi.Input<string | undefined>;
}
